### ISSUE TITLE
Mocha unit testing with PhantomJS

### ISSUE THREAD

**Issue by sindresorhus** [yeoman/generator-webapp#120]
https://github.com/mrhooray/gulp-mocha-phantomjs

**Comment by arthurvr** [comment]
> I tried, but didn't manage to get it working. How about Karma?

Just tried to integrate it and it's a PITA. I'm also +1 for Mocha though.

**Comment by addyosmani** [comment]
:+1: Mocha.

**Comment by silvenon** [comment]
What do you guys think about [this](http://twin.github.io/selenium-testing-workflow-with-webdriverio/) kind of setup for testing with PhantomJS & Mocha? Users would be able to easily switch browsers or use external services like Sauce Labs, Browerstack etc. Or is it a tad too opinionated?

**Comment by RehanSaeed** [comment]
I was also unable to get gulp-mocha-phantomjs to work. I raised this https://github.com/mrhooray/gulp-mocha-phantomjs/issues/47 issue. This plugin seems easier to use than Karma, although Karma does provide code coverage too as an added bonus.

**Comment by silvenon** [comment]
[WebdriverIO](https://github.com/webdriverio/webdriverio) is a great Nodey way to test, so that's probably the right way to go. I'm already quite experienced with it.

**Comment by UlisesGascon** [comment]
This issue has been open for a while, and it seems no volunteers are currently interested in working on it. I will proceed to close it for now, but we can reopen it if the idea gains more traction in the future.
