### ISSUE TITLE
Clean task doesn't run before serve/watch

### ISSUE THREAD

**Issue by callumlocke** [yeoman/generator-webapp#124]
The `clean` task is only set as a dep of `default`. I expected it to run before serve/watch also (probably as a dep of `connect`).

Is there any reason for this? If not I'll PR

**Comment by w0rd-driven** [comment]
I may have jumped the gun for creating a pull request for an issue over a year old now with no mention here first. I've had a `clean` dependency using the same del package become a red-headed step-child for a long time before I realized updating the package to 2.x (and syntax) fixed it. Fortunately, it looks to be the same here.
