### ISSUE TITLE
Generating files in the wrong path

### ISSUE THREAD

**Issue by changalberto** [yeoman/generator-webapp#158]
Something is awkward about the generator with the latest update.

When I create a new directory and cd into it, then do `yo gulp-webapp`
The files get generated outside of the folder I cd in.
What's even more weird is, when I create a sub directory within this directory to generate the files (hoping that it'll now treat the first directory as parent) the files would still be generated outside of the previous dir. To illustrate:

First attempt:
Inside of `~/Downloads/new_dir
Excute`yo gulp-webapp
Files are generated in `~/Downloads/`

Second attempt:
Inside of `~/Downnloads/new_dir/a_new_sub_dir
Excute`yo gulp-webapp
Files are still being generated to `~/Downloads/`

I'm looking at the latest logs and and diffs to find the culprit to no avail...

**Comment by doxxx** [comment]
Just wanted to say that I ran into this same problem and it was caused by the presence of a .yo-rc.json file in the parent directory.

**Comment by silvenon** [comment]
Thanks, that was probably it :smile:

**Comment by changalberto** [comment]
Sorry, just got this. It was buried in my inbox.

I didn't check, but that was probably it too. I managed to avoid the bug by creating a folder outside of it.
