### ISSUE TITLE
Server configs out of scope?

### ISSUE THREAD

**Issue by austinpray** [yeoman/generator-webapp#195]
This was touched on a bit in: https://github.com/yeoman/generator-gulp-webapp/pull/181

Certainly a lot of people are just dumping their static sites on s3 buckets/cloudfront or perhaps are using nginx. Why not remove the server config functionality or at least hide it behind a flag?

**Comment by arthurvr** [comment]
I just opened a PR: #262, if people want the h5bp server configs they should just use [generator-server-configs](https://github.com/h5bp/generator-server-configs).

**Comment by austinpray** [comment]
gj team
