### ISSUE TITLE
Minify HTML

### ISSUE THREAD

**Issue by mrtonyhuynh** [yeoman/generator-webapp#215]
Everything goes perfectly. However, the addition of optional minify-html when build dist is a good thing :) This is recommended by Google Pagespeed.

**Comment by Trost123** [comment]
I came up into bunch of troubles while using `<br>` tags like this: `<h1>Foo<br> bar1 bar2</h1>`, because any whitespace after `<br>` gets removed and I get "Foobar1 bar2" if I copy the text.
`conservativeCollapse:true` fixed it for me.

**Comment by eddiemonge** [comment]
@Trost123 you shouldn't use spaces as spacing elements. If you really want it, then you should be using `&nbsp;`.  `conservativeCollapse:true` may not have existed when this went it but has been added for those that continue to use spaces as spacing.

**Comment by Trost123** [comment]
It's not about spacing between elements.
Here is my situation:
`<h1>Foo<br> bar1 bar2</h1>`
(H1 is floated to right, and the designer wants the line to break after first word)
Example http://prntscr.com/ccowlp
After minification I get:
`<h1>Foo<br>bar1 bar2</h1>`
Space before bar1 is removed. This _looks_ the same, but if you try to copy h1, it gets copied as "Foobar1 bar2" (which is bad for SEO, right?), where with conservativeCollapse it's "Foo bar1 bar2" as expected.

**Comment by eddiemonge** [comment]
oh thats an interesting use case. i'm not sure about copying since i rarely do it like that. most times, the text that needs to be copied doesn't have brs. it usually has width with the words auto wrapping. Maybe the words after the br should be wrapped in a span?

**Comment by Trost123** [comment]
I guess I'm just [misusing the 'br' tag](http://stackoverflow.com/a/13221418).
Sorry for overreacting, modified/deleted previous posts accordingly.
