### ISSUE TITLE
when jade added, build process is failing with TypeError

### ISSUE THREAD

**Issue by chyngyz** [yeoman/generator-webapp#229]
It throws TypeError in html task, it says 'events.js:74 throw TypeError('Uncaught, unspecified "error" event.')'. Help needed plz

**Comment by SundarRajS** [comment]
gulp.task('html',function(){
  return gulp.src('app/**/*.html')
  
   .pipe($.useref.assets({searchPath: '{.tmp,app}'}))
   // Concatenate And Minify JavaScript
    .pipe($.if('*.js', $.uglify({
     preserveComments: 'some'
    })))
    // Concatenate And Minify Styles
    .pipe($.if('*.css', $.csso()))
    .pipe($.useref.restore())
    .pipe($.useref())
    // Update Production Style Guide Paths
    .pipe($.replace('styles/main.css'))
    // Minify Any HTML Output Files
    .pipe(gulp.dest('dist'))
    .pipe($.size({title: 'html'}));
});

facing issue as 

events.js:74
        throw TypeError('Uncaught, unspecified "error" event.');
              ^
TypeError: Uncaught, unspecified "error" event.
    at TypeError (<anonymous>)
    at Transform.emit (events.js:74:15)

has any one came across this issue in gulp-useref 
please suggest what could be the source of issue and how to fix this 


Thanks
Sundar

**Comment by silvenon** [comment]
Run

```sh
$ npm install --save-dev gulp-useref
```

and try again. Recent versions of gulp-useref have more useful error messages.
