### ISSUE TITLE
Add PHP file

### ISSUE THREAD

**Issue by rizqinizamil** [yeoman/generator-webapp#233]
Hi, I'm new on Yeoman and Gulp, sorry if my question is not related or looks dumb.

How is step by step adding php file in this generator?

**Comment by isaacalves** [comment]
You can create a server with gulp-connect-php and use it as BrowserSync proxy.

```
gulp.task('connect-php', function() {
  connectPHP.server({
    hostname: '0.0.0.0',
    bin: '/Applications/MAMP/bin/php/php5.5.3/bin/php',
    ini: '/Applications/MAMP/bin/php/php5.5.3/conf/php.ini',
    port: 8000,
    base: 'dev'
  });
});
```

```
gulp.task('serve-php',  ['styles','connect-php'],function () {
  browserSync({
    proxy: "localhost:8000"
  });

  // watch for changes
  gulp.watch([
    'app/*.php',
    'app/styles/**/*.css',
    'app/scripts/**/*.js',
    'app/images/**/*'
  ]).on('change', reload);

  gulp.watch('app/styles/**/*.scss', ['styles, reload]);
  gulp.watch('bower.json', ['wiredep', 'fonts', reload]);
});
```

I haven't figured out yet how to support multiple base directories and routes, though.

I've just posted about it: http://stackoverflow.com/questions/27990781/gulp-webapp-running-browsersync-and-php

**Comment by ymeiner** [comment]
Sorry for waking this up from the dead. How did you end up fixing wiredep and what's the strategy there?
