### ISSUE TITLE
AssetGraph-builder

### ISSUE THREAD

**Issue by silvenon** [yeoman/generator-webapp#243]
What do you guys think about [AssetGraph-builder](https://github.com/assetgraph/assetgraph-builder)? Just [look](https://github.com/assetgraph/assetgraph-builder#features) at those sweet features.

I've been using it heavily on my project now, so I have some insight how it impacts the workflow.

Some of the pros:
- no gulp-useref task
- no imagemin task
- no JSX task, if you happen to use it (with [express-jsxtransform](https://github.com/gustavnikolaj/express-jsxtransform))
  Sass + Autoprefixer (with [express-compile-sass](https://github.com/Munter/express-compile-sass) and [express-autoprefixer](https://github.com/gustavnikolaj/express-autoprefixer))
- in simple cases, these express plugins can eliminate the `.tmp` directory
- just give it your `index.html` and it will figure out all of the related HTML files and assets by following links
- rev & gzip **all** assets (gulp streams could only cover CSS & JS)
- the best solution for responsive images I've ever seen, with URL parameters:
  - `images/kitten.jpg?resize=400&gravity=Center&crop=300+300`
  - `images/icon.png?sprite=mySprite`
  - goes really well with [express-processimage](https://github.com/papandreou/express-processimage)
  - if you're not sure what that means, check out [these](https://github.com/assetgraph/assetgraph-builder#image-optimization-and-processing) examples
- IE9 CSS selector limit fallback
- inline images under a certain byte limit
- can overwrite asset base URL for CDN
- awesome maintainers
- etc.

Cons:
- probably trying to do too much
- maybe it's a bit slow
- requires some workarounds, mainly having to move everything to `.tmp` before running it, because it will look for assets in whatever directory `index.html` is

**Comment by KingScooty** [comment]
>I found it to be very powerful and very flexible. I have never used it with a single page app, but I would be willing to wire it up to a couple toy projects and share my notes with you.

@austinpray That'd be great if you could do that! I'm currently in the process of looking through the docs to try and get it setup in a test pipeline, and would love to see some examples as a kick starter.

**Comment by KingScooty** [comment]
Also, quoting from https://github.com/mrtnbroder/gulp-reduce/issues/1

> As much as I love seeing assetgraph being put to use, I have to agree with @sindresorhus. Assetgraph does not fit into the gulp paradigm as set out by the plugin guidelines.

> Assetgraph is in itself a data model that has to be kept intact in its entirety. This is why it has high level transforms that can make changes and take all the consequences into account. But this is also why it doesn't fit well with Gulp. It is not a single file type that can be streamed in the same way.

> For all intents and purposes Assetgraph-builder completely replaces the need for Gulp when we are talking about the steps of going from development to production. It has similarities in that it only reads files once and does its work in memory, but apart from that the paradigms differ quite a lot.

In terms of the `generator-gulp-webapp`, would Assetgraph thus replace a lot of the core gulp functionality in this generator?

**Comment by silvenon** [comment]
Good point, @KingScooty, Assetgraph is not very gulpy. I'll close this then, but further discussion is welcome :smiley:

**Comment by KingScooty** [comment]
I'm almost inclined to say keep it open to let the discussion flow further. I use gulp a lot in my pipeline currently, so i follow the issues/discussions on this generator often, but if Assetgraph can do a lot of the heavy lifting, perhaps we either look at another experimental generator or looking at using them in tandem? So gulp handles the edge cases that Assetgraph doesn't?

**Comment by silvenon** [comment]
Yeah, I'll keep it open for a while. I used it heavily and it certainly does a lot of the heavy lifting, especially responsive images, which actually became a joy to do if you can believe it :smiley: 

But I think this generator is intended for web apps, which are usually not image heavy and get most images via an API. So we have to keep the intention in mind, which can be hard :confused:

**Comment by KingScooty** [comment]
I read an interesting article yesterday that gave me a bit more perspective on the Gulp / Assetgraph partnership. 

The goal would be to optimise the gulp workflow for speed, so cut out anything that isn't required for getting the dev files into the browser. Then we'd use Assetgraph to handle all of the real post processing and optimising during the *deployment* step.

**Comment by austinpray** [comment]
@KingScooty that is not a good idea. Ideally you would have one command that builds for dev and prod. That way you do not run into surprises when you run your deployed code for the first time.

**Comment by KingScooty** [comment]
I guess, but I'm talking optimisations, like minification, spriting etc. You wouldn't want those running during the watch task. So Assetgraph could pick these up in the build task just before deployment. Integration would pick up most issues (if there were issues at all) if you've got tests written.

**Comment by silvenon** [comment]
Yeah, Assetgraph would be used for the build step, that's where it shines.

**Comment by silvenon** [comment]
I let this idea sink in for quite a while now, and it hasn't. I don't see AssetGraph-builder fitting into this generator, it's currently fairly unwieldy IMO, it's not very modular and will probably raise more issues than it will solve.
