### ISSUE TITLE
Generator always return a conflict on app/favicon.ico

### ISSUE THREAD

**Issue by zckrs** [yeoman/generator-webapp#251]
with v0.18.\* yeoman-generator. https://github.com/yeoman/generator-gulp-webapp/blob/master/package.json#L33

https://github.com/yeoman/generator/issues/717

**Comment by arthurvr** [comment]
This was fixed, actually: https://github.com/yeoman/generator/issues/717

**Comment by silvenon** [comment]
Yay!
