### ISSUE TITLE
where is the compass?

### ISSUE THREAD

**Issue by que01** [yeoman/generator-webapp#254]
the compass lib i still needed,but where is it?
the new vesion removed it? it mean i want use it must get the older version from git?

**Comment by sindresorhus** [comment]
Not clear what you're talking about. Please try to me more explicit.

**Comment by arthurvr** [comment]
He talks about [Compass, the Sass library](http://compass-style.org/). This can be closed down IMHO, compass is ruby-sass only, and we switched to libsass: https://github.com/yeoman/generator-gulp-webapp/pull/247. 

The new version didn't removed it, but in `gulp-ruby-sass` there was an option `compass` you could set to use compass.
