### ISSUE TITLE
Sass sourcemap

### ISSUE THREAD

**Issue by djmtype** [yeoman/generator-webapp#256]
The Sass sourcemap is being generated under .tmp. But, why is it not being exposed to Web Inspector? 
I must be missing something because the same "issue" occurs using the grunt version of generator webapp.

**Comment by isaacalves** [comment]
I had that too then I realized no sourcemaps plugin was installed in this new release. So I just installed `gulp-sourcemaps` and used it in the `styles` task in the following way:

```
gulp.task('styles', function () {
  return gulp.src('app/styles/main.scss')
    .pipe($.sourcemaps.init())
    .pipe($.sass({
      outputStyle: 'nested', // libsass doesn't support expanded yet
      precision: 10,
      includePaths: ['.'],
      onError: console.error.bind(console, 'Sass error:')
    }))
    .pipe($.postcss([
      require('autoprefixer-core')({browsers: ['last 1 version']})
    ]))
    .pipe($.sourcemaps.write())
    .pipe(gulp.dest('.tmp/styles'));
});
```

**Comment by ptim** [comment]
I needed to update [gulp-ruby-sass]:

> Note: Pre-1.0 versions are no longer supported. Please try 1.0.0-alpha

See the updated docs here: https://github.com/sindresorhus/gulp-ruby-sass/tree/rw/1.0#sourcemap

> Inline sourcemaps are recommended, as they "just work".

However, I've used an external sourcemap like so:

```
// using $.rubySass didn't work for me, so:
var sass = require('gulp-ruby-sass');

gulp.task('styles', function() {
    return sass('app/styles/main.scss', { sourcemap: true })
        .on('error', function (err) {
            console.error('Error!', err.message);
        })
        .pipe($.sourcemaps.write('.', {
            includeContent: false,
            sourceRoot: '../../app/styles',
            sourcemapPath: '.'
        }))
        .pipe(gulp.dest('.tmp/styles'));
});
```

Add your source folder to the workspace, then follow the prompts in the sources tab of the chrome inspector to map a source file to the network resource.

----

There's an issue with [autoprefixer], I believe, but I haven't waded into that yet.
I'll probably created a separate build task without sourcemaps.


[gulp-ruby-sass]: https://github.com/sindresorhus/gulp-ruby-sass
[autoprefixer]: https://github.com/sindresorhus/gulp-autoprefixer/issues/20

**Comment by ptim** [comment]
Not sure if this is the best way to do this, but I've tested autoprefixer with the following:

```
:fullscreen a {
    display: flex
}
```

...and found that it is behaving nicely with and without sourcemaps.

I've set the watch task to use 'styles' and the html task to use 'styles:dist', which doesn't output the sourcemap.


```
gulp.task('styles', function() {
    return sass('app/styles/main.scss', { sourcemap: true })
        .on('error', function (err) {
            console.error('Error!', err.message);
        })
        .pipe($.autoprefixer({browsers: ['last 1 version']}))
        .pipe($.sourcemaps.write())
        .pipe(gulp.dest('.tmp/styles'));
});

gulp.task('styles:dist', function() {
    return sass('app/styles/main.scss', { sourcemap: false })
        .on('error', function (err) {
            console.error('Error!', err.message);
        })
        .pipe($.autoprefixer({browsers: ['last 1 version']}))
        .pipe(gulp.dest('.tmp/styles'));
});
````

Feedback welcome, tx!

**Comment by ptim** [comment]
ah! sorry people, I was running an outdated generator, and since #205 libsass has been in use, so my solutions may not be relevant for others...
