### ISSUE TITLE
Bootstrap glyphicons not working

### ISSUE THREAD

**Issue by doublemarked** [yeoman/generator-webapp#260]
In development, a fresh project scaffolded with SASS+Bootstrap does not have working glyphicons. The browser hints at the problem with 404s on the following URLs:

```
(index):88 GET http://localhost:9000/fonts/glyphicons-halflings-regular.woff2 
(index):1 GET http://localhost:9000/fonts/glyphicons-halflings-regular.woff 
(index):1 GET http://localhost:9000/fonts/glyphicons-halflings-regular.ttf 
```

The icons work fine with a production build.

**Comment by silvenon** [comment]
Does it work after running `gulp fonts`?

**Comment by doublemarked** [comment]
No, does not seem to affect it. But ``gulp fonts`` deals with the dist output, right? The problem I see is only in development (``gulp serve``). Production works fine.

**Comment by silvenon** [comment]
`gulp fonts` should put those fonts in `.tmp/fonts` (and `dist/fonts`), and we are serving from `.tmp` so the paths should work. Which version of the generator are you using?

**Comment by doublemarked** [comment]
Hmmm...yes, you're right, ``gulp fonts`` did fix it! Sorry for the confusion from my last message - I did not test it properly.

Should ``gulp fonts`` maybe be added to the tasks kicked off with ``gulp serve`` ?

**Comment by silvenon** [comment]
Yes, absolutely. Thanks for reminding me :smiley:

**Comment by silvenon** [comment]
Done.

**Comment by rizqinizamil** [comment]
Hi there,

Sorry I posted here, because it also relevant to my problems. The glyphicons seem not work for me too. I got 404 error on browser console:
```
http://localhost:9000/bower_components/bootstrap-sass/assets/fonts/glyphicons-halflings-regular.woff 
```

I think, It should be:
```
 http://localhost:9000/bower_components/bootstrap-sass/assets/fonts/bootstrap/glyphicons-halflings-regular.woff 
```

I use `generator-gulp-webapp 1.0.3.` How to fix it?

**Comment by silvenon** [comment]
Hm, I should have worked. The path inside `bootstrap-sass` directory doesn't matter because we're extracting Glyphicons with the `fonts` task, which puts them in `.tmp/fonts` (and `dist/fonts`). Try running `gulp fonts` explicitly and try again.

**Comment by marcelorxaviers** [comment]
I'm having the same problem as described by @rizqinizamil and running the `gulp fonts` didn't work.
![screenshot from 2016-07-08 21-10-57](https://cloud.githubusercontent.com/assets/1873442/16704663/8158748e-4550-11e6-82ee-c139cf0758a5.png)
