### ISSUE TITLE
Bower doesn't inject dependencies.

### ISSUE THREAD

**Issue by harrisrobin** [yeoman/generator-webapp#261]
Sometimes bower simply does not inject the file on bower install (with --save). Having the server running seems to make a difference, sometimes. Has anyone else encountered this issue ?

**Comment by sindresorhus** [comment]
What packages? If the package doesn't have a `main` field in bower.json there's nothing the plugin can do.

**Comment by HarrisRobin** [comment]
@sindresorhus ok I see. That could be it, i thought all bower packages are injected.

Thanks

**Comment by sindresorhus** [comment]
Ideally yes, but the situation with Bower the opposite of ideal tbh.
