### ISSUE TITLE
Transformed JavaScript files from JSX files do not get updated when running 'gulp serve'

### ISSUE THREAD

**Issue by yuchuan1** [yeoman/generator-webapp#263]
I followed the instruction here [https://github.com/yeoman/generator-gulp-webapp/blob/master/docs/recipes/react.md](https://github.com/yeoman/generator-gulp-webapp/blob/master/docs/recipes/react.md) to setup my project. After I edited and saved my react jsx file, the generated scripts under .tmp/scripts did not get overwritten with the new version.
I have to manually stop the server and run gulp serve again for the files to get updated.

**Comment by silvenon** [comment]
Are you sure your `.jsx` file is under the `app/scripts` directory?

**Comment by yuchuan1** [comment]
They are under app/scripts/react directory

**Comment by silvenon** [comment]
It works for me. Which version of the generator are you using? Could you share your `gulpfile.js`?

**Comment by yuchuan1** [comment]
I tried the same code on another computer, and it worked. Closing the issue.

**Comment by silvenon** [comment]
Hm, I hope you manage to get it working on the first computer. If you want further help, feel free to ask.
