### ISSUE TITLE
Nunjucks Recipe

### ISSUE THREAD

**Issue by atwoodjw** [yeoman/generator-webapp#265]
After following the Nunjucks recipe, if I add a new Bower dependency and run the `wiredep` task, the path to the resources is made relative from the layouts folder.

app/layouts/default.html

```
<!-- build:css styles/vendor.css -->
<!-- bower:css -->
<link rel="stylesheet" href="../../bower_components/magnific-popup/dist/magnific-popup.css" />
<!-- endbower -->
<!-- endbuild -->
```

So in this example, the path should be `../bower_components/magnific-popup/dist/magnific-popup.css`, not `../../bower_components/magnific-popup/dist/magnific-popup.css`.

**Comment by silvenon** [comment]
With the current setup, they should both be `/bower_components/...`. Are you sure your `wiredep` task matches [this one](https://github.com/yeoman/generator-gulp-webapp/blob/63ac9380f6e4a04fb96e3314fefae9c48a22d2f4/docs/recipes/nunjucks.md#7-configure-wiredep-task-to-wire-bower-components-on-layout-templates-only)? More specifically the `ignorePath`.

**Comment by atwoodjw** [comment]
That did it. The ignorePath isn't formatted as an addition in the recipe, so I missed it. Thanks.

**Comment by silvenon** [comment]
That `ignorePath` is already a part of this generator since 64cf7be0979bbba494d56341ba3102fb2b4d07eb, it just hasn't been released yet, that's why it's not marked as a change.
