### ISSUE TITLE
Once-a-month official release?

### ISSUE THREAD

**Issue by fernoftheandes** [yeoman/generator-webapp#273]
Should we strive for having a once-a-month official release of this awesome generator, like Addy Osmani once proposed [here](https://github.com/yeoman/generator-gulp-webapp/issues/193)?

**Comment by sindresorhus** [comment]
That would be nice, but as with all Open Source, it requires someone to actually do the work of manually testing everything works, writing a release note, and release it.

**Comment by addyosmani** [comment]
+1 on Sindre's comment. The release portion of this takes the least amount of time - to enable a more regular release cycle, we need more help with pre-release testing to ensure breakage can be minimised.

**Comment by eddiemonge** [comment]
Sometimes there also isn't any new development to justify a new release.

**Comment by fernoftheandes** [comment]
@eddiemonge Well, obviously in this case, we wouldn't care about a release. 

Basically, I was trying to address the ideal situation of providing a release once there was a significant amount of improvements, etc. However, I understand the lack of resources and since I myself cannot provide aid, I cannot think of much more to say about it.
