### ISSUE TITLE
Always getting a previous version

### ISSUE THREAD

**Issue by Berrayti** [yeoman/generator-webapp#275]
Hi

Everytime I create a new app using yo gulp-webapp, I find myself with older version of the generator.

I updated the generator, npm and even Yo to use the 0.2 v of the generator, but without any results,

please help !

**Comment by silvenon** [comment]
So you have v0.2 installed? How do you know that your system is still using an older version?

**Comment by Berrayti** [comment]
@silvenon I did a little comparaison between the package.json and gulpfile in the repo and the ones in my folder and I see the difference.

I think I didn't updated well or something. Please if you can give the way to update maybe the problem will be fixed.

**Comment by silvenon** [comment]
Were you looking at the files on the `master` branch or did you specifically go to [v0.2.0](https://github.com/yeoman/generator-gulp-webapp/tree/v0.2.0)? There is a comment at the top of your scaffolded `gulpfile.js` which says which version generated it, could you take a look at it?

**Comment by Berrayti** [comment]
@silvenon Oh right !! It seems I was looking in the master branch, in my gulpfile it's 0.2.0.
If it's possible, could you please tell me if there is a way to use this master branch instead of the 0.2 version ?? 

Thank you !

**Comment by silvenon** [comment]
```sh
$ npm install --global --force yeoman/generator-gulp-webapp
```

I think that should do it.
