### ISSUE TITLE
New version

### ISSUE THREAD

**Issue by sindresorhus** [yeoman/generator-webapp#279]
[gulp-sass now has node-sass 2.0](https://github.com/dlmanning/gulp-sass/blob/master/CHANGELOG.md#133), so I think it's time for an npm update.

First we need to do some manual testing to make sure everything works correctly.

@silvenon Would you be interested in doing the release?

**Comment by silvenon** [comment]
What does node-sass 2.0 have that we were waiting for? I wanted merged `@media` queries, but I have no problem in making a release without that feature, then adding the `@media` update as a patch version or something.

Sure, I'll see if I can do some automatic testing as well.

**Comment by sindresorhus** [comment]
@silvenon I think the fixed some broken source map thingy. But doesn't matter. It's time for a release anyways.

**Comment by silvenon** [comment]
[0.3.0](https://github.com/yeoman/generator-gulp-webapp/releases/tag/v0.3.0) released.

**Comment by arthurvr** [comment]
Thanks @silvenon!

**Comment by silvenon** [comment]
:+1:

**Comment by fernoftheandes** [comment]
:+1:
