### ISSUE TITLE
add optional jscs task ?  

### ISSUE THREAD

**Issue by gaboesquivel** [yeoman/generator-webapp#284]
what are your thoughts on jscs,
would it be a good idea to make it an optional task?

**Comment by SBoudrias** [comment]
I like it, it definitively help reduce the style comments in code reviews. It's been working really well on the yeoman core packages.

**Comment by gaboesquivel** [comment]
actually we could add it both to the generator itself and generated boilerplate ( optional )

**Comment by silvenon** [comment]
Sure, PR welcome :smiley:

**Comment by gaboesquivel** [comment]
@SBoudrias do you recommend a specific setup or just use the defaults ?

**Comment by SBoudrias** [comment]
@gaboesquivel I'm not sure, we could use the default we use on yeoman - or provide a prompt asking for the preferred styleguide?

**Comment by gaboesquivel** [comment]
preferred styleguide would be nice if we had predefined set, but for now I think editing the config json .jscsrc is more practical. so maybe simply using defaults and adding an empty .jscsrc file? -  that for generated boilerplate.

for the generator itself not sure what´s the styleguide you are following, or if you are willing to introduce/enforce a new style guide... and yes it should be the same across yeoman´s projects.

**Comment by hzoo** [comment]
You could possibly prompt from a list of jscs presets (http://jscs.info/overview.html#presets) and then set the .jscsrc to it ex. for google: ``` { preset: "google" }```. There's a similar functionality in the `--auto-configure` feature

**Comment by gaboesquivel** [comment]
yeah, thanks @hzoo

**Comment by silvenon** [comment]
We switched to [ESLint](http://eslint.org/), which, apart from low-level stuff, offers advanced code style linting, similar to JSCS.
