### ISSUE TITLE
localhost list directory

### ISSUE THREAD

**Issue by mu7amad** [yeoman/generator-webapp#285]
When i start gulp localhost and i has no index.html i got "Cannot GET /"

**Comment by silvenon** [comment]
Did you run `gulp serve`?

**Comment by mu7amad** [comment]
yes and gulp work really fine, my problem happen when i don't use index.html it should show the directory files list

**Comment by silvenon** [comment]
Of course. All servers are automatically searching for the index.html, otherwise they can't display anything. The files list is a bonus, which helps you to locate the file you want to view, instead of just displaying a 404 error (page not found).

**Comment by silvenon** [comment]
Could you elaborate what is the problem and what were you expecting?

**Comment by mu7amad** [comment]
please check this screen shoot https://cloud.githubusercontent.com/assets/1523107/4010715/eb887b66-29f9-11e4-9472-312bc3912231.jpg
i need that happen when i don't use index.html

**Comment by francoiscote** [comment]
Like @silvenon said, this is not a default behavior. You have to set it up.

In our case, Browser-sync provides the server. Take a look at the [documentation](http://www.browsersync.io/docs/), you can add a `directory: true` option to BrowserSync in the serve task of the gulpfile.

**Comment by silvenon** [comment]
I misunderstood you, my bad. I thought we had this and this behavior was confusing you. Thanks @francoiscote for the tip, I'll probably add this to the core.

**Comment by mu7amad** [comment]
it's working fine but i had also to change the baseDir to : ['app','.tmp']. Thanks @francoiscote @silvenon

**Comment by silvenon** [comment]
Added in 70cceb1a12652003f4717f7da331367e078693b3.

Oh. Yeah, since we server from multiple directories, it's a trade-off. The order of `baseDir` matters, so be careful. Make sure you don't have files with the same name, e.g. a template `app/index.html` and a compiled `.tmp/index.html`, because `app/index.html` will get served, which isn't what you want.

**Comment by mu7amad** [comment]
i'm very thankful you @silvenon you did great work in gulp-webapp, i just recommend if you add requirejs task to gulp as i had added it and it's really work nice with me. i can share it to you if you want.

**Comment by silvenon** [comment]
You can write a Require.js [recipe](https://github.com/yeoman/generator-gulp-webapp/tree/master/docs/recipes) if you want, or send over a gist and I can write it. We had it, but dropped it because it was too presumptuous, i.e. many people don't/can't use it.
