### ISSUE TITLE
Recipe for Ruby Sass

### ISSUE THREAD

**Issue by callumlocke** [yeoman/generator-webapp#286]
Would you like a recipe for swapping out gulp-sass for gulp-ruby-sass?

**Comment by silvenon** [comment]
Sure, but isn't it just this?

```diff
-return gulp.src('app/styles/main.scss')
-  .pipe($.sourcemaps.init())
-  .pipe($.sass({
-    outputStyle: 'nested', // libsass doesn't support expanded yet
-    precision: 10,
-    includePaths: ['.'],
-    onError: console.error.bind(console, 'Sass error:')
-  }))
+return $.rubySass('app/styles/main.scss', {
+  sourcemap: true,
+  style: 'expanded',
+  precision: 10,
+  loadPath: ['.']
+)
+  .on('errror', function(err) { console.log(err.message); })
```

But if you want it, I'd accept a PR, no problem :wink:

**Comment by callumlocke** [comment]
yeah that's pretty much it, but it's always nice to have a recipe, just to reassure you that that *is* all it is :)

I'll do one at some point but won't leave this issue open

**Comment by silvenon** [comment]
Ok :smiley:

**Comment by radum** [comment]
This is a more complete and accurate example:

```js
gulp.task('styles', function () {
  return $.rubySass('app/styles/main.scss', {
      sourcemap: true,
      style: 'expanded',
      precision: 10,
      loadPath: ['.']
    }).on('error', function(err) {
        console.log('Sass error:'+err.message);
    })
    .pipe($.postcss([
      require('autoprefixer-core')({browsers: ['last 1 version']})
    ]))
    .pipe($.sourcemaps.write())
    .pipe(gulp.dest('.tmp/styles'))
    .pipe(reload({stream: true}));  
});
```

**Comment by silvenon** [comment]
Thanks, this will be a good reference for people who want to revert to Ruby Sass.

**Comment by rizqinizamil** [comment]
Is ruby sass doesn't support Susy anymore? I've already added <code>require: 'susy'</code> but it doesn't work. I should import Susy manually from bower then it works.

<pre>
 gulp.task('styles', function () {
  return $.rubySass('app/styles/main.scss', {
      sourcemap: true,
      style: 'expanded',
      compass: true,
      require: 'susy',
      precision: 10,
      loadPath: ['.']
    }).on('error', function(err) {
        console.log('Sass error:'+err.message);
    })
    .pipe($.postcss([
      require('autoprefixer-core')({browsers: ['last 1 version']})
    ]))
    .pipe($.sourcemaps.write())
    .pipe(gulp.dest('.tmp/styles'))
    .pipe(reload({stream: true}));  
});
</pre>

**Comment by silvenon** [comment]
You need to install Susy with Bower (`bower install --save susy`), not RubyGems if you want it to get automatically `@import`ed.

**Comment by silvenon** [comment]
Also, in future please ask support questions on StackOverflow :wink: This question clearly wasn't related to the Ruby Sass recipe.
