### ISSUE TITLE
Add gulp task for running / serving test directory?

### ISSUE THREAD

**Issue by al-the-x** [yeoman/generator-webapp#289]
Thanks for including some boilerplate for `mocha` + `chai` in `test/index.html`, but I can't find a way to run / serve the tests with a `gulp` task or similar. I can run `gulp serve` and `gulp serve:dist` but what about `gulp serve:test`...? Happy to open a PR to add this feature.

**Comment by silvenon** [comment]
A PR would be cool, yes :smiley:

**Comment by al-the-x** [comment]
I'll get right on it: `gulp serve:test`...?

**Comment by silvenon** [comment]
Yes, that sounds good.

**Comment by al-the-x** [comment]
Closed in favor of #292
