### ISSUE TITLE
Duplicated images being ignored on OS X

### ISSUE THREAD

**Issue by jdahdah** [yeoman/generator-webapp#294]
I'm observing a strange phenomenon on OS X Yosemite (10.10.2).

I've duplicated a PNG file in Finder (**⌘+D**) and given it a new name. When creating a build, the `images` task ignores this duplicate entirely even though it has no issues with the original file.

In contrast, if I 
a) open the duplicate in Photoshop and re-save it as a new PNG via "Save for Web", or
b) delete it and just re-export the image from the original PSD,
`images` works as expected.

This issue is not specific to one file or file format, I can reproduce it with any PNG or even an SVG.

Excerpt from my gulpfile, I believe it's unchanged from the original version that `generator-gulp-webapp` creates:

```
gulp.task('images', function () {
  return gulp.src('app/images/**/*')
    .pipe($.cache($.imagemin({
      progressive: true,
      interlaced: true,
      // don't remove IDs from SVGs, they are often used
      // as hooks for embedding and styling
      svgoPlugins: [{cleanupIDs: false}]
    })))
    .pipe(gulp.dest('dist/images'));
});
```

**Comment by kevva** [comment]
Does it work if you remove `$.cache`?

**Comment by jdahdah** [comment]
Yes, that seems to fix it.

**Comment by silvenon** [comment]
You have to [clear the cache](https://github.com/jgable/gulp-cache#clearing-the-cache) if things like that happen.

**Comment by jdahdah** [comment]
Alright then, I thought it was a bug that needed to be reported. Thanks both of you.
