### ISSUE TITLE
Gulp serve doesn't watch Bootstrap

### ISSUE THREAD

**Issue by Shonetow** [yeoman/generator-webapp#297]
Hi,

I just try to edit some Bootstrap's variable, and nothing happened.
It only works if I change something in main.scss!

Why is that?

**Comment by Shonetow** [comment]
I added this line into gulpfile.js and it works:
```
gulp.watch('bower_components/bootstrap-sass-official/assets/stylesheets/**/*.scss', ['styles']);
```

**Comment by silvenon** [comment]
See https://github.com/yeoman/generator-gulp-webapp/issues/296#issuecomment-88288293 for explanation why you shouldn't change aynthing in `bower_components`. Copy the `_variables.scss` from Bootstrap, `@import` it before Bootstrap in `main.scss` and override your variables there.

**Comment by Shonetow** [comment]
Yeah, tnx, I figured that later... :)
