### ISSUE TITLE
Add JS Beautifier settings to document / enforce code style?

### ISSUE THREAD

**Issue by al-the-x** [yeoman/generator-webapp#299]
Re #292, I ran into a couple of snags regarding coding style that seemed undocumented. I prefer to write in a natural style and have the robot follow the rules for me, vice the robot that just barks at me when I do violate style.

[JS Beautify](/beautify-web/js-beautify) can provide this correction automatically, given [the appropriate options](/beautify-web/js-beautify#options). I would propose adding a `.jsbeautifyrc` file and `devDependency` on JS Beautify to better enforce the coding style for JS, HTML, and CSS files.

**Comment by arthurvr** [comment]
We already have an issue about that, or am I wrong? https://github.com/yeoman/generator-gulp-webapp/issues/284

**Comment by al-the-x** [comment]
Similar. The `jscs` tool just barks at messy code like a linter might; it doesn't correct anything. Instead, `js-beautifier` will output a modified version of the code with certain rules applied... `html-tidy` anyone? They're not mutually exclusive, either. Let `js-beautify` handle the details of whitespace handling and tabs vs spaces, let `jscs` and `js-hint` handle more esoteric concepts like missing `var` statements or IIFE's, the proper use of identifiers, etc.

**Comment by SBoudrias** [comment]
It'd be nice to see how this could fit with a git pre-commit hook too.

**Comment by sindresorhus** [comment]
We're not going to use `js-beautifier` as it's too fragile. Though we will consider adding [`jscs`](http://jscs.info/) with the `--fix` flag.

**Comment by arthurvr** [comment]
> Though we will consider adding jscs with the --fix flag.

Thought so, :+1:. Am I totally wrong or do we already have an open issue about that: https://github.com/yeoman/generator-gulp-webapp/issues/284 ?

> The jscs tool just barks at messy code like a linter might; it doesn't correct anything. Instead, js-beautifier will output a modified version of the code with certain rules applied...

As mentioned by Sindre above, jscs does that as well ;)

**Comment by kevva** [comment]
@arthurvr, I don't think the intent of that issue was adding the `--fix` flag (since that option was added after the issue was created), but I guess it fits there anyway. Closing in favor of that issue.
