### ISSUE TITLE
Assets not loading with `gulp serve`

### ISSUE THREAD

**Issue by swashcap** [yeoman/generator-webapp#306]
When I fire up the local server via `gulp serve` I see this:

![yo-oh-noes](https://cloud.githubusercontent.com/assets/1858316/7245353/a19f6c22-e79e-11e4-968e-6d40dd1d93f5.jpg)

No stylesheet, and it isn’t loading jQuery. Happens in all the browsers. Here’s the debug info:

```
1.4.6
/Users/username/.rvm/gems/ruby-2.1.3/bin:/Users/username/.rvm/gems/ruby-2.1.3@global/bin:/Users/username/.rvm/rubies/ruby-2.1.3/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/username/.rvm/bin
darwin { http_parser: '2.3',
  node: '0.12.2',
  v8: '3.28.73',
  uv: '1.4.2-node1',
  zlib: '1.2.8',
  modules: '14',
  openssl: '1.0.1m' }
```
- generator-gulp-webapp: **0.3.0**
- OS: **OS X 10.10.3**

**Comment by swashcap** [comment]
_Ahh._ `wiredep`. I’m guessing https://github.com/yeoman/generator-gulp-webapp/blob/884b2877ed02b545c280b22c296c64da5bd5a7a0/app/index.js#L214-L233 didn’t run for whatever reason. Running `gulp wiredep` fixed the issue. I was unable to reproduce this bug with a fresh Gulp Webapp install.

**Comment by silvenon** [comment]
Glad you worked it out :+1:
