### ISSUE TITLE
coffeescript recipe not working anymore

### ISSUE THREAD

**Issue by a14m** [yeoman/generator-webapp#307]
I followed the recipe to use coffeescript... and it works perfectly fine when I use `gulp serve`

but when I use `gulp` to generate the build (that will be shipped) it doesn't work fine...
Instead of generating the files in JS (specifically the html task) results in the following structure...
- project structure

```
app/
├── favicon.ico
├── fonts
├── images
├── index.html
├── robots.txt
├── scripts
│   └── main.coffee
└── styles
    └── main.scss
```
- dist structure

```
dist/
├── app
│   └── app.module-2ad88588.coffee  # WRONG
├── favicon.ico
├── index.html
├── robots.txt
├── scripts
│   ├── vendor
│   │   └── modernizr-9d550bd1.js
│   └── vendor-267882b8.js
└── styles
    ├── main-0e7a37fd.css
    └── vendor-3639dd9f.css
```

and in the console it outputs

```
Resource interpreted as Script but transferred with MIME type text/coffeescript: "http://localhost:9000/app/app.module-2ad88588.coffee".
```

**Comment by artmees** [comment]
I mistakenly changed `<!-- build:js scripts/main.js -->` to `<!-- build:js app/app.module.coffee -->`

which caused the error...
