### ISSUE TITLE
Warnings at installation and post-errors on NPM

### ISSUE THREAD

**Issue by poliveira89** [yeoman/generator-webapp#308]
I'm struggling with some `UNMET DEPENDENCY` on my `npm list -g`so I have removed all of those modules and started to install one by one. Until I encountered some of this messages on some Yeoman Generators.

``` bash
$ sudo npm install -g generator-gulp-webapp
npm WARN peerDependencies The peer dependency yo@>=1.0.0 included from generator-gulp-webapp will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency generator-mocha@>=0.1.0 included from generator-gulp-webapp will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```

This block o text (warnings) appears as well on other generators, majority of people say to ignore it and look for the log after the installation or tries the command/module if it works.

As you can see on this next block of text retrievied from my bash, the installation went successfully, at least appears this way:

``` bash
sudo npm install -g generator-gulp-webapp
npm WARN peerDependencies The peer dependency yo@>=1.0.0 included from generator-gulp-webapp will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency generator-mocha@>=0.1.0 included from generator-gulp-webapp will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency gulp@>=3.5.0 included from generator-gulp-webapp will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
npm WARN peerDependencies The peer dependency yo@>=1.0.0 included from generator-mocha will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
generator-mocha@0.1.7 /usr/local/lib/node_modules/generator-mocha
└── yeoman-generator@0.17.7 (dargs@2.1.0, rimraf@2.3.2, diff@1.3.2, class-extend@0.1.1, text-table@0.2.0, mime@1.3.4, underscore.string@2.4.0, async@0.9.0, isbinaryfile@2.0.3, debug@1.0.4, grouped-queue@0.3.0, nopt@3.0.1, cross-spawn@0.2.9, chalk@0.5.1, shelljs@0.3.0, run-async@0.1.0, mkdirp@0.5.0, iconv-lite@0.4.8, file-utils@0.2.2, glob@4.5.3, findup-sync@0.1.3, github-username@1.1.1, download@1.0.7, lodash@2.4.2, request@2.55.0, gruntfile-editor@0.2.0, cheerio@0.17.0, inquirer@0.7.3)

generator-gulp-webapp@0.3.0 /usr/local/lib/node_modules/generator-gulp-webapp
├── chalk@0.5.1 (ansi-styles@1.1.0, escape-string-regexp@1.0.3, supports-color@0.2.0, strip-ansi@0.3.0, has-ansi@0.1.0)
├── yosay@1.0.3 (string-length@1.0.0, ansi-regex@1.1.1, ansi-styles@2.0.1, word-wrap@1.0.3, strip-ansi@2.0.1, pad-component@0.0.1, minimist@1.1.1, taketalk@1.0.0, chalk@1.0.0)
├── wiredep@2.2.2 (propprop@0.3.0, minimist@1.1.1, lodash@2.4.2, through2@0.6.5, glob@4.5.3, bower-config@0.5.2)
└── yeoman-generator@0.18.10 (read-chunk@1.0.1, dargs@3.0.1, detect-conflict@1.0.0, yeoman-welcome@1.0.1, xdg-basedir@1.0.1, user-home@1.1.1, rimraf@2.3.2, diff@1.3.2, class-extend@0.1.1, text-table@0.2.0, mime@1.3.4, underscore.string@2.4.0, async@0.9.0, istextorbinary@1.0.2, chalk@1.0.0, debug@2.1.3, nopt@3.0.1, run-async@0.1.0, cross-spawn@0.2.9, yeoman-assert@1.0.0, shelljs@0.3.0, mkdirp@0.5.0, through2@0.6.5, cli-table@0.3.1, pretty-bytes@1.0.4, dateformat@1.0.11, glob@4.5.3, findup-sync@0.2.1, github-username@1.1.1, file-utils@0.2.2, lodash@2.4.2, sinon@1.14.1, download@3.3.0, gruntfile-editor@0.2.0, cheerio@0.18.0, mem-fs-editor@1.2.3, yeoman-environment@1.2.5, inquirer@0.8.2)
```

The truth is that after that a LOT of `UNMET DEPENDENCY` flags emerged on my  `npm list -g` like this:

``` bash
$ npm list -g
(...)
npm ERR! missing: esprima@~1.0.4, required by redeyed@0.4.4
npm ERR! missing: cheerio@^0.13.1, required by w3counter@1.1.0
npm ERR! missing: got@^2.7.2, required by w3counter@1.1.0
npm ERR! missing: prepend-http@^1.0.0, required by protocolify@1.0.0
npm ERR! missing: base64-stream@^0.1.2, required by screenshot-stream@1.3.0
npm ERR! missing: parse-cookie-phantomjs@^1.0.0, required by screenshot-stream@1.3.0
npm ERR! missing: phantom-bridge@^1.0.0, required by screenshot-stream@1.3.0
npm ERR! missing: minimist@^1.1.0, required by subarg@1.0.0
npm ERR! missing: chalk@^1.0.0, required by sudo-block@1.2.0
npm ERR! missing: is-docker@^1.0.0, required by sudo-block@1.2.0
npm ERR! missing: is-root@^1.0.0, required by sudo-block@1.2.0
npm ERR! missing: chalk@^1.0.0, required by update-notifier@0.3.2
npm ERR! missing: configstore@^0.3.1, required by update-notifier@0.3.2
npm ERR! missing: is-npm@^1.0.0, required by update-notifier@0.3.2
npm ERR! missing: package-json@^1.0.0, required by latest-version@1.0.0
npm ERR! missing: osx-release@^1.0.0, required by os-name@1.0.3
npm ERR! missing: win-release@^1.0.0, required by os-name@1.0.3
npm ERR! missing: walk@2.3.x, required by twig@0.7.2
npm ERR! missing: minimatch@0.2.x, required by twig@0.7.2
```

And affects every other non-related module, for example: [pageres](https://github.com/sindresorhus/pageres).

**Comment by poliveira89** [comment]
EDIT: 

````bash
$ node --version
v0.10.32
$ npm --version
2.8.3
````

**Comment by poliveira89** [comment]
EDIT1: This happens with others generators as well (at least with me): [generator-gulp-angular](https://github.com/Swiip/generator-gulp-angular)

EDIT2: This error, only to this generator (generator-gulp-webapp) only happens on OS X with others global modules installed. I tried, now, with Ubuntu and installed everything successful without errors, and when I do `npm install -g` I do not have `UNMET DEPENDENCY` tag anywhere

**Comment by silvenon** [comment]
Is this causing any actual problems?

**Comment by poliveira89** [comment]
Receiving `WARN` on installation and `UNMET DEPENDENCY`after that... making a lot of other modules installed globally with `UNMET DEPENDENCY` error, when I execute `npm install -g`

**Comment by Uttammgr** [comment]
any solution to this problem having same problem

**Comment by kileyohl** [comment]
Same errors/Warnings.

**Comment by poliveira89** [comment]
What I have done, it wasn't a properly "fix".

I have deleted every NPM global package, I have uninstalled NPM/Node (previously installed with DMG).

And reinstalled Node/NPM with brew. And installed all NPM Global dependencies all over again.

**Comment by silvenon** [comment]
Are you guys having this issue with the latest release, v1.0.0?

**Comment by silvenon** [comment]
I used to have these warnings too, but not anymore, after I reinstalled node & npm. Try doing the same, it should work. I suggest using [nvm](https://github.com/creationix/nvm), it makes installing and uninstalling this stuff pretty elegant.

If the issue persists after all that, I'll reopen.

**Comment by wgmiller** [comment]
I am receiving this error:
/Users/wgmiller/.nvm/versions/node/v0.12.7/lib
└─┬ steroids@4.1.19 
  └── UNMET PEER DEPENDENCY yo@>=1.0.0

But when I ran: npm install -g yo, it returns:

Everything looks all right!
/Users/wgmiller/.nvm/versions/node/v0.12.7/lib
└─┬ yo@1.4.8

For some reason it's not seeing my yo install. I think it may be a permissions issue as I've tried a few things during install using Sudo...

**Comment by neiromendez** [comment]
I have the same problem with
 npm i generator-sails-polymer 
└── UNMET PEER DEPENDENCY yo@>=1.0.0

npm WARN enoent ENOENT: no such file or directory, open '/Users/NeiroMendez/package.json'
npm WARN generator-sails-polymer@0.0.0 requires a peer of yo@>=1.0.0 but none was installed.

But i have already install yeoman 
Yeoman Doctor
Running sanity checks on your system

✔ Global configuration file is valid
✔ NODE_PATH matches the npm root
✔ Node.js version
✔ No .bowerrc file in home directory
✔ No .yo-rc.json file in home directory
✔ npm version

Everything looks all right!
/usr/local/lib
└─┬ yo@1.7.0
