### ISSUE TITLE
Change name of images not found

### ISSUE THREAD

**Issue by jolugama** [yeoman/generator-webapp#309]
Generated on 2015-05-01 using generator-gulp-webapp 0.3.0 with yeoman.

I tried to change the 'images' folder to 'img' folder. The problem is that it does not create the 'img' folder. Just create 'images'. I only change the gulpfile.js file. 

;)

**Comment by sindresorhus** [comment]
Please elaborate. This is not a good issue.

**Comment by sindresorhus** [comment]
You need to change all the paths that references `images`.

Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gulp
Paste in the link to the question here so others can follow ;)
