### ISSUE TITLE
Paths in index.html not updating on build

### ISSUE THREAD

**Issue by jaysunwalter123** [yeoman/generator-webapp#319]
Didn't have this issue with a previous project but now, for some reason, even though the css and script files are being output in the 'dist' folder on build, the index.html doesn't get updated - it still looks for the bower component versions instead of the generated 'vendor.css', 'modernizr.js', 'vendor.js' and 'main.js' files.

I also followed your directions on setting up Less instead of Sass in case that might have something to do with it.

Can you help at all? What am I doing wrong?

Thanks

**Comment by silvenon** [comment]
Can you post your `gulpfile.js`?

**Comment by jaysunwalter123** [comment]
/*global -$ */
'use strict';
// generated on 2015-05-14 using generator-gulp-webapp 0.3.0
var gulp = require('gulp');
var $ = require('gulp-load-plugins')();
var browserSync = require('browser-sync');
var reload = browserSync.reload;

gulp.task('styles', function () {
  return gulp.src('app/styles/main.less')
  	.pipe($.sourcemaps.init())
		.pipe($.less({
			paths: ['.']
    }))
    .pipe($.postcss([
      require('autoprefixer-core')({browsers: ['last 1 version']})
    ]))
    .pipe($.sourcemaps.write('.'))
    .pipe(gulp.dest('.tmp/styles'))
    .pipe(reload({stream: true}));
});

gulp.task('jshint', function () {
  return gulp.src('app/scripts/**/*.js')
    .pipe(reload({stream: true, once: true}))
    .pipe($.jshint())
    .pipe($.jshint.reporter('jshint-stylish'))
    .pipe($.if(!browserSync.active, $.jshint.reporter('default')));
});

gulp.task('html', ['styles'], function () {
  var assets = $.useref.assets({searchPath: ['.tmp', 'app', '.']});

  return gulp.src('app/*.html')
    .pipe(assets)
    .pipe($.if('*.js', $.uglify()))
    .pipe($.if('*.css', $.csso()))
    .pipe(assets.restore())
    .pipe($.useref())
    .pipe($.if('*.html', $.minifyHtml({conditionals: true, loose: true})))
    .pipe(gulp.dest('dist'));
});

gulp.task('images', function () {
  return gulp.src('app/images/**/*')
    .pipe($.cache($.imagemin({
      progressive: true,
      interlaced: true,
      // don't remove IDs from SVGs, they are often used
      // as hooks for embedding and styling
      svgoPlugins: [{cleanupIDs: false}]
    })))
    .pipe(gulp.dest('dist/images'));
});

gulp.task('fonts', function () {
  return gulp.src(require('main-bower-files')({
    filter: '**/*.{eot,svg,ttf,woff,woff2}'
  }).concat('app/fonts/**/*'))
    .pipe(gulp.dest('.tmp/fonts'))
    .pipe(gulp.dest('dist/fonts'));
});

gulp.task('extras', function () {
  return gulp.src([
    'app/*.*',
    '!app/*.html'
  ], {
    dot: true
  }).pipe(gulp.dest('dist'));
});

gulp.task('clean', require('del').bind(null, ['.tmp', 'dist']));

gulp.task('serve', ['styles', 'fonts'], function () {
  browserSync({
    notify: false,
    port: 9000,
    server: {
      baseDir: ['.tmp', 'app'],
      routes: {
        '/bower_components': 'bower_components'
      }
    }
  });

  // watch for changes
  gulp.watch([
    'app/*.html',
    'app/scripts/**/*.js',
    'app/images/**/*',
    '.tmp/fonts/**/*'
  ]).on('change', reload);

  gulp.watch('app/styles/**/*.less', ['styles', reload]);
  gulp.watch('app/fonts/**/*', ['fonts']);
  gulp.watch('bower.json', ['wiredep', 'fonts']);
});

// inject bower components
gulp.task('wiredep', function () {
  var wiredep = require('wiredep').stream;

  gulp.src('app/styles/*.less')
    .pipe(wiredep({
      ignorePath: /^(\.\.\/)+/
    }))
    .pipe(gulp.dest('app/styles'));

  gulp.src('app/*.html')
    .pipe(wiredep({
      ignorePath: /^(\.\.\/)*\.\./
    }))
    .pipe(gulp.dest('app'));
});

gulp.task('build', ['jshint', 'html', 'images', 'fonts', 'extras'], function () {
  return gulp.src('dist/**/*').pipe($.size({title: 'build', gzip: true}));
});

gulp.task('default', ['clean'], function () {
  gulp.start('build');
});

**Comment by silvenon** [comment]
Oh, it's seems the same as the original, except the Less part. What is your directory structure? What does your `index.html` look like?

**Comment by jaysunwalter123** [comment]
This is what it looks like in the 'app' folder, minus the content between the body tags:

<!doctype html>
<html class="no-js" lang="">
  <head>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Milpark Education</title>
    

    
    
    <link rel="stylesheet" href="/bower_components/bootstrap/dist/css/bootstrap.css" />
    
    

    
    <link rel="stylesheet" href="styles/main.css">
    

    
    <script src="/bower_components/modernizr/modernizr.js"></script>
    
  </head>
<body>
...

    <script>
      (function(b,o,i,l,e,r){b.GoogleAnalyticsObject=l;b[l]||(b[l]=
      function(){(b[l].q=b[l].q||[]).push(arguments)});b[l].l=+new Date;
      e=o.createElement(i);r=o.getElementsByTagName(i)[0];
      e.src='//www.google-analytics.com/analytics.js';
      r.parentNode.insertBefore(e,r)}(window,document,'script','ga'));
      ga('create','UA-XXXXX-X');ga('send','pageview');
    </script>

    
    
    <script src="/bower_components/jquery/dist/jquery.js"></script>

    
    
		
				<script src="/bower_components/bootstrap/js/affix.js"></script>
		    <script src="/bower_components/bootstrap/js/alert.js"></script>
		    <script src="/bower_components/bootstrap/js/dropdown.js"></script>
		    <script src="/bower_components/bootstrap/js/tooltip.js"></script>
		    <script src="/bower_components/bootstrap/js/modal.js"></script>
		    <script src="/bower_components/bootstrap/js/transition.js"></script>
		    <script src="/bower_components/bootstrap/js/button.js"></script>
		    <script src="/bower_components/bootstrap/js/popover.js"></script>
		    
		    <script src="scripts/_carousel.js"></script>
		    <script src="/bower_components/bootstrap/js/scrollspy.js"></script>
		    <script src="/bower_components/bootstrap/js/collapse.js"></script>
		    <script src="/bower_components/bootstrap/js/tab.js"></script>

			
        
        <script src="scripts/main.js"></script>
        
</body>
</html>

**Comment by jaysunwalter123** [comment]
And I didn't change the folder structure from that which was generated:

.bower.rrc
.editorconfig
.git
.gitattributes
.gitignore
.jshintrc
.tmp
.yo-rc.json
app
bower_components
bower.json
dist
gulpfile.js
node_modules
package.json
test

**Comment by jaysunwalter123** [comment]
Any idea why it's not working?

**Comment by silvenon** [comment]
I edited your comment to include code tags, read more about [GitHub-Flavored Markdown](https://guides.github.com/features/mastering-markdown/) to understand why your code wasn't showing right.

Ok, I see what's wrong. If you do a fresh install, you'll see that those Bootstrap `<script>` tags used to be surrounded by comments which signaled [gulp-useref](https://github.com/jonkemp/gulp-useref) to concatenate them, you must've removed them accidentally. Read more about that in gulp-useref's docs.

I'm closing this because it's not an issue with our generator.
