### ISSUE TITLE
Add support for uncss

### ISSUE THREAD

**Issue by aweary** [yeoman/generator-webapp#320]
[uncss](https://github.com/giakki/uncss) is a great tool for removing unused CSS. It can also be safely used in conjunction with Bootstrap, as long as a proper `ignore` list is included. 

What do you guys think about adding it as an optional task?

**Comment by sindresorhus** [comment]
:-1: https://github.com/yeoman/generator-webapp/issues/215

Too fragile for highly dynamic webapps which this generator targets.

You can easily add it yourself if you need it ;)

**Comment by jsdevtom** [comment]
**[Purifycss](https://github.com/purifycss/gulp-purifycss) is better:**

1. Do: `npm i -S -D gulp-purifycss`

2. In `gulpfile.js` add the task like so:

```
gulp.task('styles', () => {
  return gulp.src('app/styles/*.scss')
    .pipe($.plumber())
    .pipe($.if(dev, $.sourcemaps.init()))
    .pipe($.sass.sync({
      outputStyle: 'expanded',
      precision: 10,
      includePaths: ['.']
    }).on('error', $.sass.logError))
    .pipe($.autoprefixer({browsers: ['> 1%', 'last 2 versions', 'Firefox ESR']}))
    .pipe($.if(dev, $.sourcemaps.write()))
    .pipe($.purifycss(['./app/**/*.js', './**/*.html'])) //<-- **INSERT THIS HERE**
    .pipe(gulp.dest('.tmp/styles'))
    .pipe(reload({stream: true}))
})
```

**Comment by silvenon** [comment]
@1db8k thanks for providing a better solution. I would still like people to add it on their own risk, but purifycss seems like a nice solution. 👍
