### ISSUE TITLE
Suggestion: Switching from csso to clean-css

### ISSUE THREAD

**Issue by MattDiMu** [yeoman/generator-webapp#324]
As you can see from the issue list, [csso](https://github.com/css/csso/issues) doesn't look well-supported anymore. Furthermore you cannot pass options to it to disable flawed optimizations.

Because of these two reasons I've switched to clean-css, by using [gulp-minify-css](/jonathanepollack/gulp-minify-css) and you should too, imo.

Regards
Matt

**Comment by sindresorhus** [comment]
:+1: PR welcome.

**Comment by fernoftheandes** [comment]
+1
