### ISSUE TITLE
Overriding/Customizing a Bootstrap script

### ISSUE THREAD

**Issue by jaysunwalter123** [yeoman/generator-webapp#326]
Hi. I copied the Bootstrap carousel script out of the bower_components folder and into the 'app/scripts' folder so I could customize the carousel indicators (Bootstrap doesn't allow you to simply do this any other way). The problem is that now, it's picking up errors in the script on 'gulp serve' (errors that already existed in the script), and also not allowing 'gulp' to complete, creating an incomplete 'dist' folder.

Is there a specific way I should be overriding this script? I've looked into excluding in the Gulpfile.js as well as 'override' in bower.json but just can't figure it out.

Thanks
Jason

**Comment by fernoftheandes** [comment]
If these are jshint errors (I cannot tell from your description), you can add the script to `.jshintignore`.

**Comment by silvenon** [comment]
Yeah, those sound like JSHint errors. Let us know if @fernoftheandes's solution doesn't work.
