### ISSUE TITLE
gulp serve stop when error compiling sass

### ISSUE THREAD

**Issue by rizqinizamil** [yeoman/generator-webapp#327]
I've got this error while I put the wrong Sass code, then `gulp serve` is stop.

<pre>
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: app/styles/page/_home.scss
  65:10  Incompatible units: 'px' and '%'.
    at options.error (/Applications/XAMPP/xamppfiles/htdocs/new-petsites/node_modules/node-sass/lib/index.js:276:32)
</pre>

Is there any solution to prevent `gulp serve` stop when I put the wrong Sass code?
I've tried to use gulp-plumber but it doesn't work.

**Comment by silvenon** [comment]
Hey, I was also bummed by this, perhaps it's better to ask this on [gulp-sass](https://github.com/dlmanning/gulp-sass/issues) and also add it to their docs. (I'll keep this open.)

**Comment by silvenon** [comment]
Check [this part](https://github.com/dlmanning/gulp-sass/wiki/Common-Issues-and-Their-Fixes#gulp-watch-stops-working-on-an-error) of gulp-sass docs for more info.

**Comment by rizqinizamil** [comment]
Thanks @silvenon, it works :)
