### ISSUE TITLE
1.0.0

### ISSUE THREAD

**Issue by sindresorhus** [yeoman/generator-webapp#328]
Been a while since last release. @silvenon Would you mind doing one?

Changes: https://github.com/yeoman/generator-gulp-webapp/compare/v0.3.0...master

Should probably land https://github.com/yeoman/generator-gulp-webapp/pull/325 and bump dependencies in the template and the generator first.

**Comment by silvenon** [comment]
No problem, I love writing changelogs anyway. It's been way to long since the last release :sweat_smile:

**Comment by arthurvr** [comment]
:+1: Just wondering, did we ever have plans when to release a 1.0?

**Comment by sindresorhus** [comment]
I guess we could make it 1.0.0.

**Comment by fernoftheandes** [comment]
:+1: Go for it! It's a great rig already.

**Comment by arthurvr** [comment]
:+1: Awesome!

**Comment by sindresorhus** [comment]
`yeoman-generator` will also need to be bumped to latest before release.

**Comment by silvenon** [comment]
Should I make updates according to API updates then?

**Comment by sindresorhus** [comment]
Yes :)

**Comment by arthurvr** [comment]
:tada: Woohooo :tada:

**Comment by silvenon** [comment]
Yep, our very own major release :tada:

**Comment by ragingwind** [comment]
Great job guys :tada:
