### ISSUE TITLE
Maps

### ISSUE THREAD

**Issue by Shonetow** [yeoman/generator-webapp#330]
Hi,

After successfully generated dist, I expect I'll find .map file in the folder styles.
But it's not there?

```
gulp.task('styles', function () {
  return gulp.src('app/styles/main.scss')
    .pipe($.sourcemaps.init())
    .pipe($.sass({
      outputStyle: 'nested', // libsass doesn't support expanded yet
      precision: 10,
      includePaths: ['.'],
      onError: console.error.bind(console, 'Sass error:')
    }))
    .pipe($.postcss([
      require('autoprefixer-core')({browsers: ['last 1 version']})
    ]))
    .pipe($.sourcemaps.write())
    .pipe(gulp.dest('.tmp/styles'))
    .pipe(reload({stream: true}));
});
```

**Comment by kevva** [comment]
You need to set a destination in `.pipe($.sourcemaps.write())`.

**Comment by Shonetow** [comment]
I tried this: `.pipe($.sourcemaps.write('.'))` and this `.pipe($.sourcemaps.write('test'))` and nothing happened...

**Comment by silvenon** [comment]
Something else must be the case, then. Try updating to latest gulp-sass and follow their [sourcemaps example](https://github.com/dlmanning/gulp-sass#source-maps). Does that work?
