### ISSUE TITLE
Generates a gulpfile.babel.js, which isn't supported in Gulp 3.9.0

### ISSUE THREAD

**Issue by Peeja** [yeoman/generator-webapp#336]
Unless I'm mistaken, which I may be, because I'm new to the whole ecosystem. But after following the directions on the Readme, I get

```
$ gulp serve
[19:51:43] No gulpfile found
```

If I'm reading [this issue](https://github.com/gulpjs/gulp/issues/830) correctly, `gulpfile.babel.js` support won't be available until 4.0?

**Comment by sindresorhus** [comment]
No, it was backported to 3.9. You probably need to upgrade your global gulp.

**Comment by Peeja** [comment]
Ah, got it, thanks. I'm still used to Ruby, and I was thinking that a bare `gulp` would pick up the local version. Cheers!

**Comment by rizqinizamil** [comment]
Also got this error on my fresh install. What can I do?
Try to run <code>sudo npm update gulp -g</code> but got this error <code>cb() never called!</code>.
Already ran <code>npm cache clean</code> too.

**Comment by kevva** [comment]
Don't use `sudo` for global packages (see https://github.com/sindresorhus/guides/blob/master/npm-global-without-sudo.md). For the `cb() never called issue`. Try upgrading `npm` and try again.

**Comment by rizqinizamil** [comment]
Thanks @kevva !

**Comment by CreativeKoen** [comment]
you can use gulp 4 with a gulpfile.babel.js, just install babel local and then it will be fine.
