### ISSUE TITLE
Stuck on html

### ISSUE THREAD

**Issue by rizqinizamil** [yeoman/generator-webapp#340]
Hi there,

Is there anybody know why when I'm running <code>gulp</code> the process take so long, and stuck on <code>html</code> task. How can I track the process so I know what happened?

Anyway I use Jade recipe.

Thanks,
Rizqi

**Comment by silvenon** [comment]
Do you have a **lot** of dependencies? gulp-useref takes a while if there are a lot of JS and CSS files to find.

**Comment by silvenon** [comment]
Maybe link your `gulpfile.js` and `index.html`.

**Comment by rizqinizamil** [comment]
@silvenon I think you are right. 
First I tried to delete <code>uglify</code> task then it worked. Then I removed tinymce (which has a lot of js files) then it worked too.

So how can I ignore all tinymce js from uglify task?
I tried to edit <code>html</code> task like this, but it doesn't work.
<pre>
gulp.task('html', ['views','styles'], function () {
  var assets = $.useref.assets({searchPath: ['.tmp', 'app', '.']});

  return gulp.src(['app/*.html', '.tmp/*.html'])
    .pipe(assets)
    .pipe($.if(['*.js', '!bower_components/tinymce/*.js'], $.uglify()))
    .pipe($.if('*.css', $.csso()))
    .pipe(assets.restore())
    .pipe($.useref())
    .pipe(gulp.dest('dist'));
});
</pre>

**Comment by silvenon** [comment]
Yeah, tinymce has a lot of files. Well, in this case I suggest you just include a concatenated version, perhaps [tinymce-dist](https://github.com/tinymce/tinymce-dist)?
