### ISSUE TITLE
Error ["$" is not defined no-undef] on gulp

### ISSUE THREAD

**Issue by shashvattrip** [yeoman/generator-webapp#342]
In my scripts/main.js file, I have,

```
'use strict';
$(document).ready(function () {
console.log('doc page');
  var a = $('.animateText').typed({
    strings: ['Blah Blah.'],
    typeSpeed: 0
  });
});
```

On running Gulp, I get this:

```
 2:0   error  "$" is not defined           no-undef
  4:6   error  a is defined but never used  no-unused-vars
  4:10  error  "$" is not defined           no-undef

✖ 3 problems (3 errors, 0 warnings)

[02:20:23] 'lint' errored after 2.85 s
[02:20:23] ESLintError in plugin 'gulp-eslint'
```

Also, I have included the main.js file below bower components.

```
<!-- endbower -->

<!-- endbuild -->
<script src="scripts/main/main.js"></script>
```

I don't understand how it is not able to find jQuery. Please help!

**Comment by sindresorhus** [comment]
That is a linting error coming from [ESLint](http://eslint.org/) that  says you're using a variable without it being defined. You can ignore it in the file or in the ESLint config. See the ESLint docs.

**Comment by shashvattrip** [comment]
But because of this my build gets blocked. Also, I cant seem to find how to locally config eslint. Can you help me?

**Comment by silvenon** [comment]
As far as I can tell, you just need to specify the `jquery` environment to `true`. See [here](http://eslint.org/docs/user-guide/configuring#specifying-environments) for more info.

The ESLint config is located in `package.json`.

**Comment by shashvattrip** [comment]
Yes, setting the env jquery to true solved it. Thanks a lot @silvenon!

**Comment by shahzadns** [comment]
In each JavaScript file, We have to define every global variable that are used across the file.
For example <code>$, angular, Backbone</code>

So, the solution is to insert following line on top of our <code>main.js</code> file.
<code> /* global $</code> */

And if we are using other libraries with JQuery. we need to add each seperated with comma.
For example.
<code> /* global $, angular, React</code> */

I know shashvattrip have solved his issue, but I want to help those folks who might face this issue.
Cheers

**Comment by thinkman99** [comment]
Read docs. You need 'Specifying Environments' in file 'package.json'
"eslintConfig": {
    "env": {
      "jquery" : true
    },
  }
http://eslint.org/docs/user-guide/configuring.html#specifying-environments

**Comment by dendrochronology** [comment]
I know this thread is wicked old, but shouldn't I get `"jquery" : true` for free when choosing jQuery from yo's options? Seems like a reasonable assumption that `$` should work out of the box.

**Comment by silvenon** [comment]
@dendrochronology good point, I fixed that in b65a1d6eccdc4af38bd38f1a128dd325b017c737.

**Comment by nathanemmanuel** [comment]
this is the error i recieve when ever am trying to run my app

 Line 3:   'React' is not defined                   no-undef
  Line 6:   'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 7:   'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 8:   'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 9:   'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 10:  'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 12:  'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 15:  'React' must be in scope when using JSX  react/react-in-jsx-scope
  Line 19:  'React' must be in scope when using JSX  react/react-in-jsx-scope

**Comment by silvenon** [comment]
@nathanemmanuel please open a new issue and specify steps to reproduce form a clean install.
