### ISSUE TITLE
No Styles in dist

### ISSUE THREAD

**Issue by XavRsl** [yeoman/generator-webapp#345]
Hello,
I can't figure out what I'm doing wrong. Using gulp serve works well. But then when I try to build it, everything is published to dist folder, no error are outputted, but I find no styles directory in the dist folder and obviously, gulp serve:dist displays a page with no style.

Please help !

Xavier

**Comment by silvenon** [comment]
If you modified your files since you finished scaffolding, that classifies as a **support** question and is best asked on [StackOverflow](http://stackoverflow.com/), providing your `gulpfile.babel.js` and `index.html`. Post a link to the question here so people can follow and answer it.

If you haven't modified anything, please post your `gulpfile.babel.js` and `index.html` here.

**Comment by silvenon** [comment]
On StackOverflow use `#yeoman` and `#gulp` tags.

**Comment by XavRsl** [comment]
I didn't change anything in the gulpfile.babel.js. I've actually generated a new project, tried gulp to generate the dist files and it worked. Then, after some time adding my app files, using gulp serve for development, I've run gulp again and styles were gone. I've changed my main.scss file to insert very basic style, but it's still not generating the folder. So is that support or generator related ?

**Comment by XavRsl** [comment]
OK. Got it. Sorry.
I was calling the css directly from my html file, without using the bower comment syntax. As it was working in "watch" mode, I didn't think it was necessary. The fact that you asked for my index.html made me wonder. I thought : "Why is he asking for my index.html ? What has that got to do with my problem anyway ???". Sorry ;)

**Comment by silvenon** [comment]
No problem. Could you explain exactly what you did wrong? That way other people who stumble upon this issue will also know.

**Comment by XavRsl** [comment]
In my html file, I was only using the code : 
```html
<link rel="stylesheet" href="styles/main.css">
```
Without requiring it to go through the build process like so : 
```html
    <!-- build:css styles/main.css -->
    <link rel="stylesheet" href="styles/main.css">
    <!-- endbuild -->
```

This was working with gulp serve but didn't generate the files when building the dist folder.

Xavier

**Comment by silvenon** [comment]
Oh, right. gulp-useref couldn't find it then.

**Comment by jsdevtom** [comment]
Thanks for explaining how the problem was solved :-D

**Comment by ghost** [comment]
@XavRsl thanks for the solution

**Comment by Coderkobe** [comment]
the correct solution？
