### ISSUE TITLE
gulp serve = No gulpfile found

### ISSUE THREAD

**Issue by s10wen** [yeoman/generator-webapp#346]
Guessing this is something to do with `gulpfile.babel.js`

**Comment by sindresorhus** [comment]
Upgrade your global gulp. `npm i -g gulp`

**Comment by s10wen** [comment]
@sindresorhus :+1:

**Comment by arthurvr** [comment]
@sindresorhus should we have that in the release notes?

**Comment by sindresorhus** [comment]
It should be a given that you keep the global gulp up to date, but sure, done.
