### ISSUE TITLE
What is gulpfile.babel.js

### ISSUE THREAD

**Issue by csablons** [yeoman/generator-webapp#353]
All my apologize if my question seem not relevant but what is this file?

Il generate a project with the last version of the generator.
When I use the gulp serve command I get an error message saying there is no gulpfile.js.
When I look my directory I found only gulpfile.babel.js.

Did I miss something?

**Comment by arthurvr** [comment]
It's a new feature introduced in Gulp 3.9. You just need the latest Gulp version installed on your system as mentioned in the release notes.

```
$ npm install -g gulp
```

**Comment by csablons** [comment]
Ok Thank you very much.

I think it could be very useful to add this line in the Getting Started part of the readme :)

**Comment by silvenon** [comment]
I added it, but I think it would be much nicer if the global gulp was picking up the locally installed gulp, like jspm does.

**Comment by arthurvr** [comment]
@silvenon it might also be worth mentioning that Babel isn't supported on node 0.10.
