### ISSUE TITLE
Sass error in gulp serve

### ISSUE THREAD

**Issue by claudioviola** [yeoman/generator-webapp#355]
When I try to lunch gulp serve Chrome show me localhost:9000
but there is an error that says:
"Properties are only allowed within rules directives, mixin includes or other properties on line 13..."
I tried to change glypicons.scss. Change the "@font-face {" in "font-face {"
But I don't think this is the correct way.
Can you help me? Where I wrong?
Screenshot in attach.
Thanks a lot!
Claudio
![schermata-2015-07-06-alle-22 36 24](https://cloud.githubusercontent.com/assets/6689594/8532696/5cd5bffa-2430-11e5-90af-28e2f684bc8f.jpg)

**Comment by silvenon** [comment]
Which version of the generator are you using? Does this happen on a fresh install or did you modify something?

**Comment by claudioviola** [comment]
How can  I check generator version?




Nothing is append on fresh install and I did not modify anything?




Can I try to uninstall and install again via node?




Thank you!


-- 

Claudio Viola

Front end Interactive developerTel. +39 320 45 244 21


www.claudioviola.net

**Comment by silvenon** [comment]
Run this:

```sh
npm ls -g | grep generator-gulp-webapp
```

We'll start from there.

**Comment by claudioviola** [comment]
Hi

the version is: generator-gulp-webapp@0.2.0




Thanks


-- 

Claudio Viola

Front end Interactive developerTel. +39 320 45 244 21


www.claudioviola.net

**Comment by silvenon** [comment]
There have been a [fair amount](https://github.com/yeoman/generator-gulp-webapp/releases) of releases since then. Could you upgrade to the latest version and try again?

```
npm install --global generator-gulp-webapp
```

**Comment by claudioviola** [comment]
Hi,

after updated generator I had to update npm too. Now it works :)

Thank you so much for your support!

Have nice day!








-- 

Claudio Viola

Front end Interactive developerTel. +39 320 45 244 21


www.claudioviola.net

**Comment by arthurvr** [comment]
Glad to hear it's fixed!
