### ISSUE TITLE
gulp serve: Failed to load external module babel-core/register

### ISSUE THREAD

**Issue by loljoho** [yeoman/generator-webapp#356]
Followed the directions in `README.md` and I receive this error when I run `gulp serve`:

``` shell
$ gulp serve
[11:26:22] Failed to load external module babel-core/register
[11:26:22] Requiring external module babel/register
```

It does, however, serve the boilerplate welcome page successfully.

**System/Software Information**

``` shell
$ sw_vers && node -e 'console.log(process.platform, process.versions)'
ProductName:    Mac OS X
ProductVersion: 10.10.3
BuildVersion:   14D136
darwin { http_parser: '2.3',
  node: '0.12.5',
  v8: '3.28.71.19',
  uv: '1.6.1',
  zlib: '1.2.8',
  modules: '14',
  openssl: '1.0.1o' }
$ npm -v
2.12.1
$ yo --version
1.4.7
$ bower -v
1.4.1
$ gulp -v
[11:28:30] CLI version 3.9.0
```

I attempted a clean install, and retraced every step for a second time in a new directory and I am still encountering the same error.

I must note that I am new to Babel, so I have no idea whether or not this has any consequence; I apologise in advance if this is benign.

**Comment by silvenon** [comment]
Thanks for a well-composed issue :+1: This error happened because for some reason you don't have [babel](https://github.com/babel/babel) installed in your project, i.e. in the `node_modules` directory. We put it in `devDependencies` in `package.json`, so the `npm install` command which ran after scaffolding should've installed it. Could you poke around to see why this is not the case?

**Comment by paulballesty** [comment]
Had the same issue. Managed to fix it installing babel-core with `npm install --save-dev babel-core`.

**Comment by timdiacon** [comment]
I'm getting this error too with latest version of generator - can be fixed as per comment from paulballesty but surely should just be in the package.json so gets installed to begin with no?

**Comment by silvenon** [comment]
It was fixed in 31348ff1acc393af507a7b8a192d767cf9737021, as the reference above your comment says, it just wasn't released yet :wink:

Now it's released in [v1.0.3](https://github.com/yeoman/generator-gulp-webapp/releases/tag/v1.0.3).

**Comment by rish** [comment]
@timdiacon I managed to monkey patch this by adding babel pack into the devDependencies for the package.json that this generator creates, like so:

    "babel-core": "^5.5.6",
    "babel": "^5.5.6",
    ....

**Comment by silvenon** [comment]
The fix is released, though :wink:

**Comment by rish** [comment]
@silvenon Yes I was trying to simulate this via the fix but this doesn't work on a fresh version of a generated app.

**Comment by rish** [comment]
Ok so I have resolved this by upgrading my node version to **iojs-v2.3.4** which would start with a fresh copy of the **~/.npm** directory. This may have been an npm caching issue.

But I was able to successfully run the generator with a global install of just **yo, gulp, bower**.

Thank you for the assistance though @silvenon. :smiley:

**Comment by silvenon** [comment]
Glad you got it working :+1: Yeah, probably a caching issue. What was the error you were encountering when trying with the latest release?

**Comment by rish** [comment]
So trying this out on another machine where I'm using iojs-2.2.1 and ensuring it's not an npm caching issue:-

```
[22:32:43] Failed to load external module babel/register
/Users/{user}/{project_dir}/gulpfile.babel.js:2
import gulp from 'gulp';
^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:409:25)
    at Object.Module._extensions..js (module.js:444:10)
    at Module.load (module.js:351:32)
    at Function.Module._load (module.js:306:12)
    at Module.require (module.js:361:17)
    at require (module.js:380:17)
    at Liftoff.handleArguments (/Users/{user}/.nodenv/versions/iojs-2.2.1/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/Users/{user}/.nodenv/versions/iojs-2.2.1/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/Users/{user}/.nodenv/versions/iojs-2.2.1/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
```

Installing **iojs-2.3.4** and it works.

May be worth mentioning this as a requisite on the README?

I can create a pull request if you would prefer to identify this.

I don't have any spare time to test this out on previous iojs-2.3.* versions or other official versions but it would be could so set the minimum version required due to breaking changes from multiple dependencies.

Thank you for the patches though, for this very useful generator, none the less! :beer:

**Comment by silvenon** [comment]
The problem is that gulp is still searching for `babel/register` instead of `babel-core/register` (babel module was renamed to babel-core). You should reset it by reinstalling it – `npm install --global gulp` did it for me. (This is probably what you did as part of reinstalling iojs).

**Comment by gerbil** [comment]
Not working even after gulp reinstall

**Comment by dowsanjack** [comment]
I'm still having this issue, where gulp is searching for `babel/register`. 
`gulp serve` is echoing the following output:
```
[13:14:40] Failed to load external module babel/register
/Users/ankit/dev/coffee/gulpfile.babel.js:2
import gulp from 'gulp';
^^^^^^
SyntaxError: Unexpected reserved word
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Liftoff.handleArguments (/usr/local/lib/node_modules/gulp/bin/gulp.js:116:3)
    at Liftoff.<anonymous> (/usr/local/lib/node_modules/gulp/node_modules/liftoff/index.js:192:16)
    at module.exports (/usr/local/lib/node_modules/gulp/node_modules/liftoff/node_modules/flagged-respawn/index.js:17:3)
```

Gulp version : 3.9.0

When I do `gulp -v`: 
```
[13:53:28] Failed to load external module babel/register
[13:53:28] CLI version 3.9.0
[13:53:28] Local version 3.9.0
```

Can anyone guide where things are going wrong.

**Comment by silvenon** [comment]
`npm install -g global`, doesn't help?

**Comment by dowsanjack** [comment]
:-1: nopes.

**Comment by silvenon** [comment]
Couple of ideas:

* `npm cache clean`
* `npm uninstall -g gulp`, open a new Terminal tab, `npm install -g gulp`
* reinstall node, as a last resort

Try them out. The last one should work, but it shouldn't really come to that.

**Comment by dowsanjack** [comment]
Did what you advised, but no change in output. :( . Even reinstalled node.

**Comment by silvenon** [comment]
Whoa… that should've worked :confused: Are you on OS X? Are you up for pairing with [tmate](http://tmate.io/)?

**Comment by shadowmint** [comment]
I'm seeing this on ubuntu too.

```
[10:4:00] Failed to load external module babel/register
[10:44:00] CLI version 3.9.0
[10:44:00] Local version 3.9.0
```

To fix I had to install babel, not babel-core.

```
doug@doug-VirtualBox:~/wok$ gulp --version
[10:55:23] Requiring external module babel-core/register
[10:55:23] CLI version 3.9.0
[10:55:23] Local version 3.9.0
doug@doug-VirtualBox:~/wok$ node --version
v0.10.25
```

Weirdly this does work on OSX without any problem. 

No idea, but it's weird.

**Comment by silvenon** [comment]
Gulp searches for both. First `babel-core/register`, then `babel/register`. I'm not sure anymore whether Babel wants us to install `babel` or `babel-core`?

**Comment by Revod** [comment]
I have the same problem, tried that https://github.com/yeoman/generator-gulp-webapp/issues/356#issuecomment-126231339 and nope :-1:

**Comment by rish** [comment]
@Revod I have posted a new issue on the gulp repo here:

https://github.com/gulpjs/gulp/issues/1364 it might be related?

**Comment by blackfyre** [comment]
Installing the `babel-core`locally with `npm install --save-dev babel-core` solved my problem, but the `SyntaxError: Unexpected reserved word` problem still remains when trying to run `gulp serve`.

**Comment by Revod** [comment]
I solved my problem uninstalling Node and NPM and reinstall using [this guide of Team Tree House](http://blog.teamtreehouse.com/install-node-js-npm-linux)

**Comment by blackfyre** [comment]
[This](https://markgoodyear.com/2015/06/using-es6-with-gulp/) article held the solution for my problems.

**Comment by silvenon** [comment]
Might be better to raise an issue in gulp's repo, if there isn't one already.

**Comment by rish** [comment]
If you are using Babel Core 6.0.0 onwards you need to use the **plugin presets** as outlined in the announcements:

https://babeljs.io/blog/2015/10/29/6.0.0/

**Comment by wangchi** [comment]
@blackfyre The article helped me too :+1:

**Comment by baermowei** [comment]
然而还是没什么用

```
 gulp serve
[18:14:03] Requiring external module babel-core/register
E:\mygit\gobuy\gulp-two\node_modules\babel-core\lib\transformation\file\options\option-manager.js:126
      if (!option) this.log.error("Unknown option: " + alias + "." + key, ReferenceError);
                           ^

TypeError: Cannot read property 'error' of undefined
    at OptionManager.mergeOptions (E:\mygit\gobuy\gulp-two\node_modules\babel-core\lib\transformation\file\options\option-manager.js:126:28)
    at OptionManager.addConfig (E:\mygit\gobuy\gulp-two\node_modules\babel-core\lib\transformation\file\options\option-manager.js:107:10)
    at OptionManager.findConfigs (E:\mygit\gobuy\gulp-two\node_modules\babel-core\lib\transformation\file\options\option-manager.js:168:35)
    at OptionManager.init (E:\mygit\gobuy\gulp-two\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:12)
    at compile (E:\mygit\gobuy\gulp-two\node_modules\babel-core\lib\api\register\node.js:117:22)
    at normalLoader (E:\mygit\gobuy\gulp-two\node_modules\babel-core\lib\api\register\node.js:199:14)
    at Object.require.extensions.(anonymous function) [as .js] (E:\mygit\gobuy\gulp-two\node_modules\babel-core\lib\api\register\node.js:216:7)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)

```

**Comment by wangchi** [comment]
@baermowei  "Cannot read property 'error' of undefined"：this.log没有error这个属性，可以试着把这个if判断去掉试试

**Comment by aa8562373** [comment]
我擦。然而并没什么卵用。我测试了很多啊~

**Comment by jolugama** [comment]
hi!. the solution:
create a file .babelrc with:
{
  "presets": [
    "es2015"
  ]
}

**Comment by xiao-ai** [comment]
@jolugama Solved my problem, thanks!
@aa8562373 可以试试这个~
Also you can refer to: http://babeljs.io/docs/plugins/preset-es2015/

**Comment by Khrotan** [comment]
@jolugama Solved my problem also, thank you.

**Comment by axe-me** [comment]
I solved this problem by using node 4.x instead of 5.x.

**Comment by timothylombrana** [comment]
Im having this problem when I run gulp serve, I've tried all the above solutions with no success. Help please!

`Requiring external module babel-register
/node_modules/babel-core/lib/transformation/file/options/option-manager.js:372
          throw new Error("Couldn't find preset " + JSON.stringify(val) + " relative to directory " + JSON.stringify(dirname));`

**Comment by acauamontiel** [comment]
This helped me to run Gulp without problems: https://markgoodyear.com/2015/06/using-es6-with-gulp/

**Comment by timothylombrana** [comment]
@acauamontiel thanks for the resource,  but I had ran updates exactly like those that I gather from other threads. No luck, had to remove the generator and reinstall. Which is I was trying to avoid, luckily not as much work as I thought post reinstall. I mean comparatively speaking to trying the above mentioned solutions, none the less appreciate the response as no one had tried to help.

**Comment by silvenon** [comment]
@alphapilgrim this problem happens with a fresh install? Or did you use a nonexistent Babel preset?

**Comment by timothylombrana** [comment]
@silvenon no this happened after I had add some new dependencies. I did have the gulp server running, also had tried to gulp wiredep just in case.

**Comment by silvenon** [comment]
Did you then try to gradually get from the fresh install to that state to see where it went wrong?

**Comment by frankgraave** [comment]
Hi there! I just started to use gulp, so I have a fresh install. Everything is working fine, but this error keeps showing everytime when I do gulp serve. Tried several thing's mentioned in this post that helped others, but still no succes.

**Comment by dpalomar** [comment]
Same issue here.
Fresh install.
- Ubuntu 14.04
- nvm v0.31.0
- node v4.4.1
- npm v3.8.3
- yo v1.7.0
- bower v1.7.7
- gulp v3.9.1
- grunt-cli v1.1.0
- grunt v0.4.5

After run command `gulp serve` shows:

```
`Failed to load external module babel-register
[15:34:42] Failed to load external module babel-core/register
[15:34:42] Failed to load external module babel/register
/home/vagrant/prueba/gulpfile.babel.js:2
import gulp from 'gulp';
^^^^^^

SyntaxError: Unexpected reserved word
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:373:25)
at Object.Module._extensions..js (module.js:416:10)
at Module.load (module.js:343:32)
at Function.Module._load (module.js:300:12)
at Module.require (module.js:353:17)
at require (internal/module.js:12:17)
at Liftoff.handleArguments     (/home/vagrant/.nvm/versions/node/v4.4.1/lib/node_modules/gulp/bin/gulp.js:116:3)
at Liftoff.<anonymous> (/home/vagrant/.nvm/versions/node/v4.4.1/lib/node_modules/gulp/node_modules/liftoff/index.js:193:16)
at module.exports (/home/vagrant/.nvm/versions/node/v4.4.1/lib/node_modules/gulp/node_modules/flagged-respawn/index.js:17:3)`
```

**Comment by timothylombrana** [comment]
@frankgraave, just covering all bases did you run gulp serve from the project root? Also what is the error message exactly?

**Comment by silvenon** [comment]
@dpalomar could you make sure that latest `babel-register`, `gulp` (both locally) and `gulp-cli` (globally) are installed?

**Comment by Marshevskyy** [comment]
try to run "npm install -g gulp@3.9.0"

looks like CLI version to 3.9.1 is buggy

**Comment by dpalomar** [comment]
Thanks @Marshevskyy I'ill try.
Fixed using **node version:0.12.12** and  `npm rebuild node-sass`

**Comment by ebuyuran** [comment]
"npm install -g gulp@3.9.0" worked for me, thanks @Marshevskyy.

**Comment by kevin-kang** [comment]
在你gulp文件相同路径下创建一个.babelrc文件，里面内容为：
{
  "presets": ["es2015"]
}

就能解决你的问题了，同时记得安装babel-core babel-preset-es2015

**Comment by mqliutie** [comment]
@kevin-kang 还是看中文解决快- -

**Comment by SpadeRubick** [comment]
**Tasks completed with the error**

```
run 'gulp dist'
[11:27:20] Failed to load external module babel-register
[11:27:20] Requiring external module babel-core/register
[11:27:25] Using gulpfile F:\Gary\gulpfile.babel.js
[11:27:25] Starting 'js'...
[11:27:25] Finished 'js' after 8.57 ms
[11:27:25] Starting 'css'...
[11:27:25] Finished 'css' after 3.91 ms
[11:27:25] Starting 'html'...
[11:27:25] Finished 'html' after 1.84 ms
[11:27:25] Starting 'dist'...
[11:27:25] Finished 'dist' after 6.53 μs
```

package.json:

``` js
"devDependencies": {
    "babel": "^6.5.2",
    "babel-core": "^6.8.0",
    "babel-preset-es2015": "^6.6.0",
    "gulp": "^3.9.1",
    ……
  }
```

**Comment by richyrb00** [comment]
I found that i was using node v6

i moved it back down to v4.4.4

this then fixed the issue but still getting an error with failed to load external module babel-register so i installed that which then took me back to square one which a lot of you posted. i think uninstalled that again and although it hows failed to load external module babel-register.. it works :)

I think is you too node down to 4.2.6 (as i have another system on this version) it should work as required with no issues.

**Comment by silvenon** [comment]
A new version was released where we don't parse gulpfile with Babel anymore (i.e. we renamed `gulpfile.babel.js` to `gulpfile.js`), because Node v4+ support a lot of ES2015 features. So this issue should be gone. Hopefully people will stop torturing this poor thread 😓

**Comment by wenfp0803** [comment]
hello:
  I am is run 'gulp wiredep' ,  There is an error 'must start with number, buffer, array or string', excuse me how should solve? 
Thanks! 
------------------ Original ------------------

**Comment by silvenon** [comment]
@bleedkaga please raise a new issue, this is not related to babel-register.

**Comment by wenfp0803** [comment]
Can you tell me how to solve this problem? @silvenon

**Comment by silvenon** [comment]
@bleedkaga Maybe. If you open a new issue 😁

**Comment by amaalzohny** [comment]
in index.js 
`
if (env === 'development' || env === 'test') {
  // Register the Babel require hook
  //require('babel-register');
  require('babel-register')({
   presets: [ 'es2015' ]
});
}

`

**Comment by thecreation** [comment]
I am using ubuntu 14.04. And i am using `nvm` managing the nodejs.

Runing `gulp -v` getting the error below

```
[20:54:47] Failed to load external module babel/register
[20:54:47] CLI version 3.9.0
[20:54:47] Local version 3.9.1
```

And the issue was solved by the steps below:

```
sudo rm -r /usr/lib/node_modules/
sudo rm /usr/bin/gulp
npm cache clear
npm uninstall gulp-cli -g
npm uninstall gulp -g
npm install gulp-cli -g
```

Hope it will be helped for whom that using `nvm`.

**Comment by karthikeyana** [comment]
i found solution 
`
npm install babel-cli babel-preset-es2015`

**Comment by quangthien27** [comment]
Adding **.babelrc** file may help
```
{
  "presets": [
    "es2015"
  ]
}
```

**Comment by NeverMore93** [comment]
@baermowei @mqliutie @kevin-kang @xiao-ai 你们TM能用英语嘛？丢人丢到外国去了，shame on you!!!

**Comment by NeverMore93** [comment]
@mqliutie  觉得好用点赞就行，别TM废话，你以为csdn还是贴吧啊

**Comment by mqliutie** [comment]
@NeverMore93 满足脏话在这和我说丢人? 我回的是国人,讲中文有问题?和国人还要拽英文?你英语多厉害?嫌丢人你别出来不就好了?

**Comment by YDD9** [comment]
@Marshevskyy 
Thanks, this `npm install -g gulp@3.9.0` works !
then I just `npm i gulp && gulp build` for my app.

**Comment by msangel** [comment]
Yes, gulp 3.9.0 make this as an warning, not an error, but I still feel like I am doing something wrong.

**Comment by lipis** [comment]
Can someone just fix this sh*t? Obviously is not working..

**Comment by silvenon** [comment]
@lipis what isn't working?

**Comment by lipis** [comment]
@silvenon I think I found the appropriate project to post the issue: https://github.com/gulpjs/gulp-cli/issues/150 sorry for "aggresive" post.. but this issue is circling the web for the last two years..

**Comment by silvenon** [comment]
Ah, I didn't realize that this threw an actual error, that's bad… I hope someone will fix it.

**Comment by markgreve** [comment]
For me this was a gulp v3.9.1  issue
deleted node_modules folder
ran 
npm uninstsall gulp
npm install gulp@3.9.0

npm unistall --save-dev gulp
deleted node_modules folder
npm install --save-dev gulp@3.9.0

gulp -v
Requiring external module babel-core/register
CLI version 3.9.0
Local version 3.9.0

Everything now works.

**Comment by silvenon** [comment]
Yeah, that is a Gulp issue and should be dealt with in their issue tracker.

If someone finds an issue with this generator, please open a new issue.

P.S. The reason for locking this issue says "too heated" because that was the most appropriate one on the list. I don't think anyone here was out of line, just that the discussion got a bit chaotic and that the issue has been identified.
