### ISSUE TITLE
Can I use MAMP as server of "serve" task?

### ISSUE THREAD

**Issue by altaywtf** [yeoman/generator-webapp#357]
Hey, I want to use MAMP for the serve tasks but I could not integrated it with them.

I assigned port 80 for MAMP and tried to use same port for serve but it didn't work. 

Any suggestions?

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gulp
Paste in the link to the question here so others can follow ;)

**Comment by aydieneue** [comment]
http://stackoverflow.com/questions/31352194/can-i-use-mamp-as-server-of-gulp-serve-task

**Comment by aydieneue** [comment]
Okay, it's here: http://stackoverflow.com/questions/31352194/how-can-i-use-mamp-as-server-of-gulp-serve-task
