### ISSUE TITLE
Remove javscript console.log when building

### ISSUE THREAD

**Issue by zackexplosion** [yeoman/generator-webapp#358]
I can't find the option to remove console.log when I running `gulp build`.

Is there a option?

**Comment by silvenon** [comment]
Just remove the `console.log` line in [`main.js`](https://github.com/yeoman/generator-gulp-webapp/blob/b839b0e67770effbeae691f0dcf48c5dea36d5a5/app/templates/main.js).

**Comment by cstony0917** [comment]
I was looking for something like this https://github.com/gruntjs/grunt-contrib-uglify#turn-off-console-warnings

**Comment by silvenon** [comment]
Oh, I misunderstood the question :smile:

**Comment by cstony0917** [comment]
Yes, Could you reopen the issue? Thanks. :wheelchair:

**Comment by silvenon** [comment]
This is not really an issue with our generator, you were asking where you can pass options to UglifyJS. You can pass them [here](https://github.com/yeoman/generator-gulp-webapp/blob/b839b0e67770effbeae691f0dcf48c5dea36d5a5/app/templates/gulpfile.babel.js#L55), like so:

```js
.pipe($.if('*.js', $.uglify({compress: {drop_console: true}})))
```

**Comment by cstony0917** [comment]
It works, thank you for the reply , I was look for this for a long time :+1:
