### ISSUE TITLE
gulp file missing

### ISSUE THREAD

**Issue by johnfumaster** [yeoman/generator-webapp#361]
I just yo'd the generator, and when I tried to run `gulp serve`, it says No gulp file found.  Any ideas?

**Comment by ptim** [comment]
You may have an old version of gulp-cli installed..

```
npm uninstall -g gulp-cli
npm install -g gulp-cli
```
is recommended over in gulp-cli issues: https://github.com/gulpjs/gulp-cli/issues/27

Now `gulp serve` works as expected.

**Comment by kevva** [comment]
Yup, that should fix it.
