### ISSUE TITLE
Gulp file comprehension

### ISSUE THREAD

**Issue by landed1** [yeoman/generator-webapp#362]
Can't find anything online to help me get a handle on this weird syntax you use in your gulpfile...

gulp.task('styles', () => {

is this the same as 

gulp.task('styles', function() {

**Comment by oskarrough** [comment]
It's the shorthand syntax `arrow functions` from ES2015, which is available since this generator is using a `gulpfile.babel.js`.

Check https://babeljs.io/docs/learn-es2015/#arrows

**Comment by landed1** [comment]
TY
