### ISSUE TITLE
how to move swf files to * folder when i build this app?

### ISSUE THREAD

**Issue by wangningx** [yeoman/generator-webapp#363]
some plugin depend on .swf files, such as zeroclipboard and uploader, and my problem is how to move swf files to \* folder when i build this app?

**Comment by wangningx** [comment]
gulp.task('extras', () => {
  return gulp.src([
    'app/*.*',
    '!app/*.html'
  ], {
    dot: true
  }).pipe(gulp.dest('dist'));
});

gulp.task('extras', () => {
  return gulp.src([
    'app/*.swf'
  ], {
    dot: true
  }).pipe(gulp.dest('dist/scripts'));
});



how to Merger it?

**Comment by sindresorhus** [comment]
Support questions are better asked on StackOverflow:
http://stackoverflow.com/questions/tagged/gulp
Paste in the link to the question here so others can follow ;)

**Comment by wangningx** [comment]
i solved it~
http://stackoverflow.com/questions/32043376/how-to-move-swf-files-to-some-folder-when-i-build-it
