### ISSUE TITLE
App fonts folder location not according to gruntfile

### ISSUE THREAD

**Issue by SerbanC** [yeoman/generator-webapp#366]
When generating the folder structure there is a `fonts` folder created directly under `app`. I placed my local fonts there but they weren't being copied `dist`, so I looked inside `gruntfile.js` and the paths are different:

``` js
// Renames files for browser caching purposes
    filerev: {
      dist: {
        src: [
          '<%= config.dist %>/scripts/{,*/}*.js',
          '<%= config.dist %>/styles/{,*/}*.css',
          '<%= config.dist %>/images/{,*/}*.*',
          '<%= config.dist %>/styles/fonts/{,*/}*.*',
          '<%= config.dist %>/*.{ico,png}'
        ]
      }
    },
```

and 

``` js
    copy: {
      dist: {
        files: [{
          expand: true,
          dot: true,
          cwd: '<%= config.app %>',
          dest: '<%= config.dist %>',
          src: [
            '*.{ico,png,txt}',
            'images/{,*/}*.webp',
            '{,*/}*.html',
            'styles/fonts/{,*/}*.*'
          ]
```

Unless I'm missing something, the generator should create `app/styles/fonts` instead of `app/fonts` or `gruntfile.js` should be modified.

**Comment by SerbanC** [comment]
Sorry, I meant to post this in generator-webapp (the grunt version). I'm not sure if it applies here as well, but it might :)

**Comment by silvenon** [comment]
It doesn't apply here, but thanks for reporting.
