### ISSUE TITLE
Recommend to add CSS and Javascript concatenating and minimizing features

### ISSUE THREAD

**Issue by Loyalsoldier** [yeoman/generator-webapp#368]
As we all know, CSS and Javascript **concatenating and minimizing features** are needed when at development and production procedure.
**Hope to have it by default.**

**Comment by silvenon** [comment]
Could you clarify the issue? What do you mean by default? Why would you need to have it in development?

**Comment by Loyalsoldier** [comment]
@silvenon Oh sorry, it's my mistake. Just production needs.

**Comment by silvenon** [comment]
But you already do have it. [gulp-useref](https://github.com/jonkemp/gulp-useref) is taking care of that [here](https://github.com/yeoman/generator-gulp-webapp/blob/c136136f810f6bf9e9359665d3c8b9a8b58a0ce7/app/templates/gulpfile.babel.js#L50-L61).

What precisely do you want that this gulpfile is not offering?

**Comment by Loyalsoldier** [comment]
@silvenon Excellent! Thanks for reminding. A few days ago I just built my own front-end workflow, then I saw yours today. And this solves the dependencies that I had troubled with. Everything seems great!
