### ISSUE TITLE
How to upgrade project created by old generator-gulp-webapp

### ISSUE THREAD

**Issue by zackexplosion** [yeoman/generator-webapp#372]
I have a project created with old generator

```
// generated on 2015-06-12 using generator-gulp-webapp 0.3.0
```

How can I upgrade the dependency with the newest release? just update the package.json or any tips?

thank you for your reply

**Comment by arthurvr** [comment]
There isn't a super easy way to update. The best way is probably to go through the release notes and see what changes are of value to you and apply those updates yourself (that's going to be in more files than package.json).

**Comment by arthurvr** [comment]
Actually you can run `yo gulp-webapp` again and skip the files that contain things you modified but you'll need to fix a bunch of conflicts (definitely if you're still on 0.3).

**Comment by cstony0917** [comment]
OK. I will try it , thank for your reply :)
