### ISSUE TITLE
Now bootstrap4 alpha is used for scss

### ISSUE THREAD

**Issue by wenerme** [yeoman/generator-webapp#373]
Please allowed choose twbs4

**Comment by silvenon** [comment]
We will update once it's stable.

**Comment by tbredin** [comment]
this sounds good

**Comment by bagusflyer** [comment]
But it seems there is no scss for twbs4 yet.

**Comment by wenerme** [comment]
twbs4 write in scss instead of less in twbs3.

**Comment by silvenon** [comment]
Fixed by @MarkyMarkNo1 in #621. I'll drop a comment when I release this.
