### ISSUE TITLE
Add Heroku recipe

### ISSUE THREAD

**Issue by mcauser** [yeoman/generator-webapp#376]
For deploying to heroku.com

**Comment by silvenon** [comment]
I don't think Heroku supports static sites, but I guess it can be faked :smile:

**Comment by sindresorhus** [comment]
https://github.com/jamiew/heroku-static-site

**Comment by silvenon** [comment]
:+1:

**Comment by mcauser** [comment]
Of course it can. It has a read-only filesystem, but it supports write on build/deploy.
I was able to get something working. I'll package it up into a recipe once I iron out the kinks.

**Comment by silvenon** [comment]
Great!

**Comment by gaboesquivel** [comment]
Here's a recipe using express.js https://gist.github.com/gaboesquivel/d493a8fe91c4836de41f

**Comment by zackexplosion** [comment]
@gaboesquivel Thank you , this link is very helpful . Can you put it in the documents?.

**Comment by gaboesquivel** [comment]
PR https://github.com/yeoman/generator-gulp-webapp/pull/398
