### ISSUE TITLE
How do I make scss files work?

### ISSUE THREAD

**Issue by Vvaltz** [yeoman/generator-webapp#381]
I change 

gulp.task('styles', () => {
  return gulp.src('app/styles/*.css') 
    .pipe($.sourcemaps.init())
    .pipe($.autoprefixer({browsers: ['last 1 version']}))
    .pipe($.sourcemaps.write())
    .pipe(gulp.dest('.tmp/styles'))
    .pipe(reload({stream: true}));
});

To 

gulp.task('styles', () => {
  return gulp.src('app/styles/*.scss') 
    .pipe($.sourcemaps.init())
    .pipe($.autoprefixer({browsers: ['last 1 version']}))
    .pipe($.sourcemaps.write())
    .pipe(gulp.dest('.tmp/styles'))
    .pipe(reload({stream: true}));
});

This only creates new scss file in .tmp, but doesn't create in dist, I guess I have to write custom scss compile code in gulpfile? This generator doesn't support out-of-the-box Sass? Sorry, I'm a beginner

**Comment by silvenon** [comment]
It does. When you run `yo gulp-webapp`, the generator asks you whether you want to include Sass (it's on by default). If it's included, you shouldn't have to do any extra work to compile Sass files. Run it again and let us know how it went.

**Comment by Vvaltz** [comment]
Sorry, you were correct, there was something wrong with my node 4.0.0 and npm or something. After uninstalling node, downloading nvm and using node 0.12.6 everything installed normally with scss file by default in place, sorry for this

**Comment by silvenon** [comment]
Great to hear that! :+1:
