### ISSUE TITLE
Wiredep task not working?

### ISSUE THREAD

**Issue by KristjanLiiva** [yeoman/generator-webapp#383]
I installed the gulp webapp generator and ran it (excluded bootstrap). Gulp serve/build, all works. Then installed toastr with bower:

```
bower install --save toastr
```

It is included in the bower.json

``` javascript
{
  "name": "test2",
  "private": true,
  "dependencies": {
    "jquery": "~2.1.1",
    "modernizr": "~2.8.1",
    "toastr": "~2.1.2"
  },
  "devDependencies": {
    "chai": "~3.3.0",
    "mocha": "~2.3.2"
  }
}
```

Toastr bower file:

``` javascript
{
  "name": "toastr",
  "version": "2.1.2",
  "main": ["toastr.js", "toastr.css"],
  "dependencies": {
        "jquery": ">=1.6.3"
  }
}
```

Running default/build/serve does not inject the toastr.js nor toastr.css in index.html, and it is also not found when I serve it.

Are we supposed to modify the gulp file?

running 

```
$ node
> require('wiredep')({ src: 'app/index.html' });
```

Modifies the index.html and everything works as I would expect.

**Comment by silvenon** [comment]
You should run `bower install --save` **while** `gulp serve` is running or explicitly run `gulp wiredep` if you installed Bower deps while gulp wasn't watching :wink: Read [this](https://github.com/yeoman/generator-gulp-webapp/blob/aaed8ff08bcaccfb47721af270979a9b71bccab9/docs/README.md#bower) for more info.

**Comment by KristjanLiiva** [comment]
Thank you! Works
