### ISSUE TITLE
Semantic-UI crashed when using generator-gulp-webapp

### ISSUE THREAD

**Issue by Loyalsoldier** [yeoman/generator-webapp#387]
It seems can't run `gulp` while using Semantic-UI. The problem looks like this:

![ps](https://cloud.githubusercontent.com/assets/10487845/10013072/9d7c5bde-6140-11e5-9be9-41948dd266ee.png)

I find it was the problem of this line:

``` css
@import url('https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic&subset=latin');
```

and it was solved after I comment this line and add the `font-face` of google fonts myself.

Or if my network problem?

I have also consulted the `semantic-org` and waiting for help.

**Comment by silvenon** [comment]
Interesting… The CSS minification module is actually downloading that stylesheet and inlining it, I had no idea :smile: If you update gulp-minify-css:

```sh
$ npm install --save-dev gulp-minify-css
```

Does it work then?

**Comment by silvenon** [comment]
gulp-minify-css uses clean-css, so jakubpawlowicz/clean-css#612 might be related.

**Comment by Loyalsoldier** [comment]
Hi @silvenon . After I ran:
```
$ npm install --save-dev gulp-minify-css
```
and everything was okay!

Thanks!

I think you should update the devDependencies.

**Comment by Loyalsoldier** [comment]
Hi @silvenon . 

I find it crash again. And I really don't know how it would be successful yesterday.

After I manually update the version of Clean-css to the newest v3.4.4, one of the devDependencies of gulp-minify-css. It fails again.Now I really have no idea……

It seems update the devDependencies of ```generator-gulp-webapp``` is not the solution.

Sorry about that.

**Comment by silvenon** [comment]
Could you provide a demo, where you do a fresh scaffold of the latest version, then update gulp-minify-css and do a minimal set of changes to reproduce the issue?

**Comment by Loyalsoldier** [comment]
@silvenon 
The same problem remains there.
I think it's the problem of the GFW in China. See https://github.com/Semantic-Org/Semantic-UI/issues/2220
And it need to manually import the google font-face CSS into the Semantic-UI. And then everything seems good.

Thanks a lot.

**Comment by silvenon** [comment]
That's too bad :confused: But I'm glad you figured it out.
