### ISSUE TITLE
Minify CSS in the production

### ISSUE THREAD

**Issue by OnkelTem** [yeoman/generator-webapp#389]
I didn't find how to minify CSS in the production builds. Would be great to have it either.

**Comment by silvenon** [comment]
[This line](https://github.com/yeoman/generator-gulp-webapp/blob/master/app/templates/gulpfile.babel.js#L56) minifies it. Is this not the case for you?

**Comment by OnkelTem** [comment]
Holy git! I got confused repositories :) It was intended for [yeogurt] (https://github.com/larsonjj/generator-yeogurt)

**Comment by silvenon** [comment]
"Holy git"?! Hahaha, awesome, totally stealing that one :+1:
