### ISSUE TITLE
Old version 

### ISSUE THREAD

**Issue by m-pokrovskii** [yeoman/generator-webapp#391]
When i run yo gulp-webapp i get old version with gulpfile.js and livereload. What i'm doing wrong?

**Comment by silvenon** [comment]
```
$ npm install --global generator-gulp-webapp
```

**Comment by m-pokrovskii** [comment]
it's 2.12.1

**Comment by m-pokrovskii** [comment]
npm --global generator-gulp-webapp -v
2.12.1

npm list --global | grep webapp
├─┬ generator-gulp-webapp@1.0.3

**Comment by alferov** [comment]
Have you tried to clear the cache?
`npm cache clean`

**Comment by m-pokrovskii** [comment]
Yes. I've removed package, cleaned the cache and installed it again. Still the same.
generated on 2015-09-25 using generator-gulp-webapp 0.2.0

Where generator-gulp-webapp 0.2.0 can be located?

**Comment by m-pokrovskii** [comment]
just delete /usr/local/lib/node_modules/generator-gulp-webapp
This problem exist if user uses brew

**Comment by sindresorhus** [comment]
Use https://github.com/npm/npm/issues for npm support. Installing a generator is just installing a normal npm package and nothing specifically to do with this project.
