### ISSUE TITLE
Managing API Location

### ISSUE THREAD

**Issue by kldeb** [yeoman/generator-webapp#393]
Does this generator support managing api location? 

For example, I'm connecting to different api domains for different environments: production, development, test etc. 

I'd rather not expose all the domains in production. 

Is there a way to build (replace) the api domain? 

I'm using the git subtree deployment and I'm new to gulp.

**Comment by gaboesquivel** [comment]
http://addyosmani.com/blog/environment-specific-builds-with-grunt-gulp-or-broccoli/

**Comment by silvenon** [comment]
There are many ways to do this, what @gaboesquivel linked seems good. I hope you managed to solve the problem.

**Comment by aireater** [comment]
Thanks for the tips. I ended up wrapping the gulp html task - passing in the values I need to change and using gulp replace. Maybe not the most sophisticated approach but it works for now.
