### ISSUE TITLE
Error: Cannot find module 'gulp-protractor'

### ISSUE THREAD

**Issue by Stefanbracke** [yeoman/generator-webapp#395]
After the initial yeoman action, i just wanted to test gulp help and I get this error: "Error: Cannot find module 'gulp-protractor'".  Is this not included in the package? Do i need to download it separately?

**Comment by gaboesquivel** [comment]
that's weird, protractor is the E2E test framework for Angular apps. It is not related to this generator.
This generator sets mocha for testing.

**Comment by silvenon** [comment]
Maybe you were referring to [generator-angular](https://github.com/yeoman/generator-angular).
