### ISSUE TITLE
Jasmine support

### ISSUE THREAD

**Issue by gaboesquivel** [yeoman/generator-webapp#396]
Is Jasmine no longer supported? [there's still code for jasmine support](https://github.com/yeoman/generator-gulp-webapp/blob/master/app/index.js#L33) but no prompt so you always get mocha

**Comment by neilhem** [comment]
If you want Jasmine as a test framework you should pass `--test-framework` with `jasmine` value as it documented here https://github.com/yeoman/generator-gulp-webapp#options
