### ISSUE TITLE
UNMET PEER DEPENDENCY yo@>=1.0.0

### ISSUE THREAD

**Issue by TusharPandya** [yeoman/generator-webapp#402]
Getting this error while creating new AngularJs project using Yeoman using bellow command
---> npm install --global generator-angular@0.11.1

For which my requirement details are as bellow
node --version = v4.2.1
npm --version  = 3.3.6

Which is perfect because I can install Yeoman toolset using : npm install --global yo bower grunt-cli command.But when I try to install an AngularJS generator it generates 2 errors
1) UNMET PEER DEPENDENCY generator-karma@>=0.9.0
2) UNMET PEER DEPENDENCY yo@>=1.0.0

**Comment by silvenon** [comment]
This is not related to generator-gulp-webapp, but to [generator-angular](https://github.com/yeoman/generator-angular). Please raise the issue there.
