### ISSUE TITLE
"Cannot GET /"

### ISSUE THREAD

**Issue by stivyw** [yeoman/generator-webapp#403]
`Cannot GET /` with `gulp serve:dist`

**Comment by silvenon** [comment]
Can you elaborate? What are you trying to achieve?

**Comment by stivyw** [comment]
Yeap. 
My bad. I do the `gulp dist` before `gulp serve:dist`
Some generators make the `gulp dist` automaticaly, this not.
Thank's.

**Comment by stivyw** [comment]
Yeap
My bad. I did `gulp dist` before `gulp serve:dist`.
Some generators make `gulp dist` automaticaly, this not and I like that.
Thank's :)

**Comment by silvenon** [comment]
:+1:

**Comment by aahoo** [comment]
I just installed this generator and used the following two commands:
- `gulp serve` which works showing the default page
- `gulp serve:dist` which shows "Cannot GET /"!
What I am I doing wrong?

**Comment by sscarduzio** [comment]
Issues = best docs around

**Comment by silvenon** [comment]
@sscarduzio we haven't yet released the change where `serve:dist` automatically runs `build` as well, but that's coming with the next release.
