### ISSUE TITLE
Generator app in Jade

### ISSUE THREAD

**Issue by bagusflyer** [yeoman/generator-webapp#404]
I read the recipe about installing jade. But I'm wondering if it's possible to add an option to support Jade so that the jade is supported directly by running the generator? Thanks.

**Comment by silvenon** [comment]
We don't favor one templating language over another, because it usually depends on the situation. Sometimes you can get away with Mustache, but if you need more control, you might choose Lo-dash or Jade. We don't think there's a single right choice, so we leave it up to the user.

**Comment by bagusflyer** [comment]
Thanks for your replay. Then my question is if it's possible to customize the generator to suit my purpose? Please give me a hint on this (I'm quite new to generator). Thank you so much.

**Comment by bagusflyer** [comment]
I found some document about this. http://yeoman.io/authoring/index.html

My question is if I can modify your generator a bit as a new generator. Thanks.

**Comment by silvenon** [comment]
Yes, of course :+1: You can just fork this generator, make required changes for Jade support and publish it.
