### ISSUE TITLE
Nunjucks gulp task hangs after build

### ISSUE THREAD

**Issue by joehand** [yeoman/generator-webapp#406]
I added the nunjucks recipe and the gulp tasks are all working fine but the `gulp build` task never completes - it just hangs after finishing everything. 

The site still successfully builds but it seems like the nunjucks views task is causing it not to finish. 

I am using the tasks as written in the recipe.

**Comment by Parataku** [comment]
Can Confirm. Same happens with an new gulp-webapp project and after adding the nunjucks recipe.

**Comment by IanLunn** [comment]
Confirmed.

**Comment by ivojacobs** [comment]
you can fix it by adding watch:false parameter as described here: https://github.com/carlosl/gulp-nunjucks-render

'$.nunjucksRender.nunjucks.configure(['app/'], {watch: false});'

**Comment by joehand** [comment]
👍 that fixed it. Thanks!
