### ISSUE TITLE
imagemin will not work when isFile condition is checked

### ISSUE THREAD

**Issue by Dev-Force** [yeoman/generator-webapp#414]
images are not minified after the building process.
if we remove the isFile condition the minification is done as it should
Is there any way to fullfil that condition there?
I wanted to fix it myself but i couldnt.
i searched about gulp-match and gulp-if but i didnt find anything as far as the fulfilling of the condition is concerned.

**Comment by dmahipus** [comment]
+1

**Comment by skipin1** [comment]
+1

**Comment by silvenon** [comment]
I never liked that condition either, it was added because of some errors, probably imagemin trying to optimize non-images. But AFAIK imagemin ignores non-image files, right @kevva?

**Comment by Dev-Force** [comment]
well, what the point of checking? the images will be in a seperate folder if the project structure is nice. u know what u are filtering anyways. whatever.

**Comment by silvenon** [comment]
It was added by #323, there was a discussion about it in https://github.com/google/web-starter-kit/issues/579#issuecomment-75457434. Could you check if this works with the latest version of gulp-cache?

**Comment by Dev-Force** [comment]
thats right. I think i should close the issue now

**Comment by Dev-Force** [comment]
well i cant right now i am too busy. sorry :(

**Comment by Dev-Force** [comment]
anyone to verify thats all ok after the latest gulp-cache version?

**Comment by silvenon** [comment]
It works fine, so I removed the condition.
