### ISSUE TITLE
No gulpfile found

### ISSUE THREAD

**Issue by fionnbharra** [yeoman/generator-webapp#415]
After running `yo gulp-webapp` and `gulp serve` I get `No gulp file found` 

Do I need to do something with the babel file?

**Comment by rgksugan** [comment]
@fionnbharra  You will need to update your gulp. try running npm install -g gulp
https://github.com/yeoman/generator-gulp-webapp/issues/353

**Comment by fionnbharra** [comment]
thanks, will do.
