### ISSUE TITLE
CLI Directions are backwards

### ISSUE THREAD

**Issue by robertwalsh0** [yeoman/generator-webapp#424]
![screen shot 2015-12-06 at 6 21 25 pm](https://cloud.githubusercontent.com/assets/88433/11616667/c6150de8-9c46-11e5-97fb-cac97e909150.jpg)

The directions are actually, "Press space to UNselect"

I always mess up this step because of the directions. I'm sure I'm not the only one.

**Comment by hemanth** [comment]
`Press <space> to toggle selection`

**Comment by neilhem** [comment]
@robertwalsh0 is trying to say that by default everything is selected, should be written `(Press <space> to unselect)`.

**Comment by silvenon** [comment]
It would probably be better to suggest this in [Inquirer.js](https://github.com/SBoudrias/Inquirer.js) repo.

**Comment by silvenon** [comment]
Closing this as it should be raised at Inquirer.js, we can't change it.
