### ISSUE TITLE
Upgrading Gulp & Babel?

### ISSUE THREAD

**Issue by OwenMelbz** [yeoman/generator-webapp#426]
Love the generator! So thanks has helped me get started understanding gulp and bower!

However I was curious as to if you would consider updating it to work with the latest babel and gulp?

Thanks

**Comment by silvenon** [comment]
Sure :smiley: Is the Babel ecosystem ready, though?

**Comment by sindresorhus** [comment]
We're already using latest Gulp. Gulp4 is not yet officially released.

From experience using Babel 6, I don't feel it's ready yet. I would wait a month and reconsider then.

**Comment by silvenon** [comment]
We'll update to gulp v4 when it's stable. #124 is the issue that's waiting for v4, so we don't have too keep this open.

**Comment by silvenon** [comment]
Released in [v1.1.0](https://github.com/yeoman/generator-gulp-webapp/releases/tag/v1.1.0).
