### ISSUE TITLE
gulp-karma is deprecated

### ISSUE THREAD

**Issue by MaybeThisIsRu** [yeoman/generator-webapp#427]
Upon running `yo angular` with Gulp as the choice of workflow tool, receive the following error:

`npm WARN deprecated gulp-karma@0.0.4: Please use Karma directly: https://github.com/karma-runner/gulp-karma`

**Comment by silvenon** [comment]
I don't understand why so many people thought that generator-gulp-webapp is [generator-angular](https://github.com/yeoman/generator-angular) :confused: Thanks for reporting the issue, could you please raise it there as well?

**Comment by ruppalsingh** [comment]
I came here because I saw this [blog post on Yeoman's website][yeoman-gulp]. Please update me if the case is otherwise. I was under the impression this is the Yeoman Angular generator using Gulp.
[yeoman-gulp]: http://yeoman.io/blog/gulp-explore.html

**Comment by silvenon** [comment]
This generator is the gulp version of [generator-webapp](https://github.com/yeoman/generator-webapp). (There’s no mention of Angular in that blog post.)
