### ISSUE TITLE
Updating the NPM package?

### ISSUE THREAD

**Issue by DaBs** [yeoman/generator-webapp#429]
I feel like the NPM package feels a little left out. It hasn't had an update the last 5 months, after all. Is this something we can do anything about? The README is recommending installing via npm, but since the package is far outdated, it doesn't make much sense, and you will encounter errors in relation to gulp-useref being installed as version 3.0.0, whereas the NPM package still runs with the syntax from some 1.x.x version. The gulpfie.babel.js is also looking different from the two repos. [Reference here](https://www.npmjs.com/package/generator-gulp-webapp)

**Comment by arthurvr** [comment]
Hmm, we still have a draf release in [October](https://github.com/yeoman/generator-gulp-webapp/releases) but I wonder why we never released it. Maybe @silvenon remembers?

**Comment by silvenon** [comment]
Just released [v1.0.4](https://github.com/yeoman/generator-gulp-webapp/releases/tag/v1.0.4), thanks for the push.
