### ISSUE TITLE
Unable to include external code in mocha unit testing

### ISSUE THREAD

**Issue by agiantwhale** [yeoman/generator-webapp#431]
In app/scripts/main.js

```
var temp = "test";
```

In test/index.html

```
  <!-- include source files here... -->
  <script src="../app/scripts/main.js"></script>
```

After running gulp serve:text

```
ReferenceError: temp is not defined
    at Context.<anonymous> (spec/test.js:7:22)
```

Is this an issue, or am I doing something wrong?
I cannot find any documentation to do so.

**Comment by silvenon** [comment]
Sorry for the late response, did you try `scripts/main.js` instead of `../app/scripts/main.js`?
