### ISSUE TITLE
Bower dependencies not automatically wired up

### ISSUE THREAD

**Issue by agiantwhale** [yeoman/generator-webapp#432]
After installing some dependencies through bower install, the script files are not included in index.html when serving.

**Comment by pcooney10** [comment]
think the app needs to be needs to be running when installing bower components (`gulp serve`).  Also make sure to include the `--save` param

**Comment by silvenon** [comment]
[This](https://github.com/yeoman/generator-gulp-webapp/tree/master/docs#bower) part of the docs might be helpful.

**Comment by agiantwhale** [comment]
Thank you, works as intended.
