### ISSUE TITLE
Deprecation Warnings on Install

### ISSUE THREAD

**Issue by arcseldon** [yeoman/generator-webapp#435]
npm WARN deprecated gulp-minify-html@1.0.5: Consider using gulp-htmlmin instead
npm WARN deprecated gulp-minify-css@1.2.3: Please use gulp-cssnano instead.

Looks like there are gulp dependencies that should be updated with recommended alternates.

This is very off-putting for someone new to the generator - it looks like it has not been maintained in some time.

**Comment by jonkemp** [comment]
+1

**Comment by silvenon** [comment]
Thanks for the push, will be releasing a new version very soon.

**Comment by arcseldon** [comment]
Thanks for taking care of this, appreciate it.

**Comment by silvenon** [comment]
Released in [v1.0.4](https://github.com/yeoman/generator-gulp-webapp/releases/tag/v1.0.4).
