### ISSUE TITLE
File to import not found or unreadable Bootstrap

### ISSUE THREAD

**Issue by CesarDenis** [yeoman/generator-webapp#438]
My project is giving the following error:

```
[BS] Serving files from: app
[15:07:23] Starting 'styles'...
Error in plugin 'sass'
Message:
    bower_components/bootstrap-sass/vendor/assets/stylesheets/bootstrap/bootstrap.scss
Error: File to import not found or unreadable: bootstrap/variables
       Parent style sheet: /Users/macweb01/Sites/smy/ciab/test/bower_components/bootstrap-sass/vendor/assets/stylesheets/bootstrap/bootstrap.scss
        on line 12 of bower_components/bootstrap-sass/vendor/assets/stylesheets/bootstrap/bootstrap.scss
>> @import "bootstrap/variables"; // Modify this for custom colors, font-sizes, e
   ^

[15:07:23] Finished 'styles' after 67 ms
```

Only change I made was in the version of Bootstrap to v.2.3.2.2

Can someone help me?

**Comment by silvenon** [comment]
> Only change I made was in the version of Bootstrap to v.2.3.2.2

Which version? Did you type that correctly?

**Comment by CesarDenis** [comment]
I changed to the tag [v2.3.2.2 ](https://github.com/twbs/bootstrap-sass/tree/v2.3.2.2)

My *bower.json*:
```
{
  "name": "2016",
  "private": true,
  "dependencies": {
    "modernizr": "~2.8.1",
    "respond": "~1.4.2",
    "bootstrap-sass": "v2.3.2.2",
    "jquery": "~1.11.3"
  },
  "overrides": {
    "bootstrap-sass": {
      "main": [
        "vendor/assets/stylesheets/bootstrap.scss",
        "vendor/assets/fonts/images/*",
        "vendor/assets/javascripts/bootstrap.js"
      ]
    }
  },
  "devDependencies": {
    "chai": "~3.4.2",
    "mocha": "~2.3.4"
  }
}
```

**Comment by silvenon** [comment]
What happens when you run `gulp wiredep`? Does the problematic path to `bootstrap.scss` update?

**Comment by CesarDenis** [comment]
The path looks correct, The path is slightly different from the version 3, before the folder `assest` comes the `vendor`:

Version 2
```
.
├─ ...
├─ bootstrap-sass
│  ├─ vendor
│     └─ assest
└── ...
```

Version 3
```
.
├─ ...
├─ bootstrap-sass
│  └─ assest
└── ...
```

When I run the `gulp wiredep` it does not update the patch like version 3 of bootstrap.

**Comment by silvenon** [comment]
I looked more closely at the error. The problem is that `bootstrap/variables.scss` doesn't exist relative to `bootstrap/bootstrap.scss`. This is a problem with that version of bootstrap-sass (twbs/bootstrap-sass#950), not with this generator.

**Comment by CesarDenis** [comment]
Thanks for your help @silvenon.
