### ISSUE TITLE
How do you integrate components in src/app/components directory

### ISSUE THREAD

**Issue by heenaI** [yeoman/generator-webapp#442]
Hi,
Sorry for the basic question but I cannot seem to figure out how are you integrating different components like navbar in the app? I have not yet changed anything in the code, just studying it.

**Comment by silvenon** [comment]
What do you mean? We don't have components as separate entities, it's all just in `index.html`.

**Comment by heenaI** [comment]
Forexample I created a new service called lineChart.service.js the file is the the components folder like so
app/components/chart_1/lineChart.service.js
I added this to the index.html manually but when I insert lineChartService into the MainController 
function MainController($scope, lineChartService) {});
it sends an error unknown provider  lineChartService

**Comment by silvenon** [comment]
The repo you're looking for is [generator-angular](https://github.com/yeoman/generator-angular), this is generator-gulp-webapp :wink:

**Comment by heenaI** [comment]
Not sure how that happened, but I am quite sure my app is from gulp-angular here is the repository https://github.com/heenaI/pollyvotes I have not yet pushed the service yet but will do so in a bit

**Comment by silvenon** [comment]
My bad, then [this](https://github.com/Swiip/generator-gulp-angular) is the repo you're looking for :smile:
