### ISSUE TITLE
cssnano and htmlmin

### ISSUE THREAD

**Issue by OwenMelbz** [yeoman/generator-webapp#445]
Hi Guys,

Just wondering if there was any intention to upgrade to the actively supported cssnano and htmlmin rather than the current bundled tools?

Many thanks

**Comment by silvenon** [comment]
Don't we [use those already](https://github.com/yeoman/generator-gulp-webapp/blob/143182592cbef254126fdb1d3406382ab9fa915e/app/templates/gulpfile.babel.js#L70-L71)? :smile:

**Comment by OwenMelbz** [comment]
Oh. Very weird

When I ran npm install i got

```
npm WARN deprecated gulp-minify-css@1.2.3: Please use gulp-cssnano instead.
npm WARN deprecated gulp-minify-html@1.0.5: Consider using gulp-htmlmin instead
```

**Comment by silvenon** [comment]
Try upgrading `npm install --global generator-gulp-webapp`.
