### ISSUE TITLE
[Suggestion] Make everything work without a .tmp folder

### ISSUE THREAD

**Issue by alexej-d** [yeoman/generator-webapp#446]
So apparently a gulp core contributer stated that [one does not need temp files in gulp](https://twitter.com/contrahacks/status/656343475743428608). My question is: Does that apply to our watch task? How would we achieve that?
Maybe use some kind of css and js inline injecting like webpack does with it's loaders?

**Comment by UlisesGascon** [comment]
This issue has been open for a while, and it seems no volunteers are currently interested in working on it. I will proceed to close it for now, but we can reopen it if the idea gains more traction in the future.
