### ISSUE TITLE
Browser reloads once per script

### ISSUE THREAD

**Issue by phelma** [yeoman/generator-webapp#447]
In a complex web app with lots of files `app/scripts/*.js`
The `gulp serve` task reloads each browser several times after one of these files is edited. _(This is 20+ times for my project)_

Can we have this task reload the browser only once per file change.

**Comment by silvenon** [comment]
Try removing `'.tmp/scripts/**/*.js',` from the `gulp.watch` command in the `serve` task. I believe that's what's causing the issue.

If it works for you, I'll apply the fix.

**Comment by phelma** [comment]
That has sorted, thanks for the help. The fix should probably go back into the generator.

**Comment by dima-f1** [comment]
I'm have this issue now, with latest release of generator-webapp. Any file I change cause one reload for
 every file  which have same type as edited, no matter what kind of file it was - js, scss. Any help?
![image](https://cloud.githubusercontent.com/assets/5352626/25044784/26320dc8-2131-11e7-92eb-3287b0f32cc1.png)

I'm on Windows 7 64bit, Node 6.10.2, NPM 3.10.10
