### ISSUE TITLE
task styles not create css.map

### ISSUE THREAD

**Issue by jolugama** [yeoman/generator-webapp#451]
there is a problem. if you don't have a css.map, it not create. 
soluction: In the task styles,in the line:
 .pipe($.sourcemaps.write()) it must change to:  .pipe($.sourcemaps.write('.'))

it is a problem? is correct?  
thanks!!!

**Comment by silvenon** [comment]
It creates **inline** maps. You can see them at the end of compiled CSS files. Do sourcemaps not work for you or you just prefer to have them in a separate file?

**Comment by jolugama** [comment]
Umm, interesting. I'll try it right now.

**Comment by jolugama** [comment]
silvenon, You have removed the scripts task today!!! why?

**Comment by silvenon** [comment]
I haven't, make sure you have the latest version of the generator and that the Babel option isn't off for some reason.

**Comment by jolugama** [comment]
Ok. it's all right!. thanks.
