### ISSUE TITLE
Merge with generator-webapp

### ISSUE THREAD

**Issue by SBoudrias** [yeoman/generator-webapp#453]
I think it's time we take these two projects and merge them into a single one.

**Comment by silvenon** [comment]
**YES**. I tried doing that already in yeoman/generator-webapp#565, but it wasn't well received. What did you have in mind exactly? Having both Grunt and Gulp options?

**Comment by SBoudrias** [comment]
I think we could just delete the grunt webapp and completely replace with this one. The other one is not really active anymore, so I think it'd be better to have fewer awesome generator then a lot of "medium" ones.

We could move forward by:
1. Deleting `generator-webapp` repository
2. Renaming `generator-gulp-webapp` repository
3. Renaming `generator-gulp-webapp` to `generator-webapp`
4. Publishing a major version bump of `generator-webapp` to npm
5. Deprecating `generator-gulp-webapp` npm package in favor of `generator-webapp`

Maybe we could keep the old Grunt generator-webapp in a `legacy` or `grunt` branch on the old repo. and publishing hotfixes if needed for a few months.

**Comment by sindresorhus** [comment]
:+1: to what you suggested above.

**Comment by silvenon** [comment]
:+1:

**Comment by SBoudrias** [comment]
Okay, I'll get started on this later today.

**Comment by SBoudrias** [comment]
Okay, legacy generator-webapp is backed up into the [legacy-grunt branch](https://github.com/yeoman/generator-gulp-webapp/tree/legacy-grunt)

**Comment by SBoudrias** [comment]
Temporarily renamed the legacy webapp repository to https://github.com/yeoman/generator-webapp_DEPRECATED

This allows us to access old ticket if need be. I think we can delete it in a week or two.

**Comment by SBoudrias** [comment]
Deprecation warning for generator-gulp-webapp is up:

```
$ npm i -g generator-gulp-webapp
npm WARN deprecated generator-gulp-webapp@1.1.1: Renamed generator-gulp-webapp to generator-webapp. Install the new version by running: npm install generator-webapp@^2.0.0
```

**Comment by SBoudrias** [comment]
So, I think this issue is now completed. Successful migration!

**Comment by silvenon** [comment]
Nice job!

**Comment by alxscms** [comment]
Can we still access and install the old webapp generator with Grunt and Coffeescript support ?

**Comment by SBoudrias** [comment]
@alxscms we do not unpublish old versions from npm.
