### ISSUE TITLE
Pug recipe error

### ISSUE THREAD

**Issue by hiepdd91** [yeoman/generator-webapp#454]
I 've followed your instructions to use Jade but when I use the build problems error:
$ .useref.assets not a function.

**Comment by mckewans** [comment]
You don't need the line of code 
var assets = $.useref.assets({searchPath: ['.tmp', 'app', '.']});
Removing it should solve your problem.

**Comment by silvenon** [comment]
Which version of the generator are you using? Were you getting this error on fresh install as well? This line has nothing to do with the Pug recipe, so there's something else going on here.

I'll be happy to reopen if you provide more info.
