### ISSUE TITLE
Deprecation warnings

### ISSUE THREAD

**Issue by njt1982** [yeoman/generator-webapp#462]
On creation of an app, I got the following warnings.

```
npm WARN deprecated graceful-fs@3.0.8: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated lodash@1.0.2: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated graceful-fs@1.2.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN deprecated npmconf@2.1.2: this package has been reintegrated into npm and is now out of date with respect to npm
npm WARN deprecated lodash.padleft@3.1.1: This package has been renamed. Use lodash.padstart@^4.0.0.
npm WARN deprecated lodash.padright@3.1.1: This package has been renamed. Use lodash.padend@^4.0.0.
npm WARN deprecated graceful-fs@2.0.3: graceful-fs version 3 and before will fail on newer node releases. Please update to graceful-fs@^4.0.0 as soon as possible.
npm WARN prefer global node-gyp@3.3.0 should be installed with -g
```

Do we need to update some packages?

**Comment by silvenon** [comment]
Half of them are coming from gulp, nothing we can do about that. gulpjs/gulp#1485

Not sure where the rest are coming from or how to find that out :confused:

**Comment by jonigl** [comment]
I got the same warnings.

**Comment by rosmcmahon** [comment]
I do not like the look of this one:
`minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`
Does anyone know if this will this insert a security issue into production sites?

It's coming from modules:
generator-yasmine@0.2.2
wiredep@2.2.2
yeoman-generator@0.22.6

Incidentally latest version of yeomon-generator is 0.23.4
and wiredep is at 4.0.0

**Comment by silvenon** [comment]
> Does anyone know if this will this insert a security issue into production sites?

I'm pretty sure that's only a problem if you're using it on a server. In this case you're just using these tools to generate the frontend.

But bumping dependencies is certainly in order…

**Comment by silvenon** [comment]
We're updating dependencies in the next release, but many deprecation warnings will remain. Nothing we can do about that…
