### ISSUE TITLE
Master page concept 

### ISSUE THREAD

**Issue by amgadfahmi** [yeoman/generator-webapp#463]
Hi,
Great job everyone, tried to use the tool on one of the static websites I have and I came across a scenario which i have to apply the generator injection on each page and then was thinking about the master page concept. 
As isolation concept there should a master page which include all the injection and isolate the page content in a separate file (views), on a side note separating the header and footer as well will be great. 
└── app
    └── views (content)
        ├── about.html
        ├── index.html
    └── partials 
        ├── footer.html
        └── header.html 
      index.html (as master)  
This can be implemented as a feature a user can select while running the generator as bootstrap and others ! 
Am welling to contribute, your thoughts will be great.

**Comment by eddiemonge** [comment]
This is more of an implementation detail specific to your use case (Even if others can use it) but not usable but the majority of use cases. Implementing this would require something that builds those pages up. This generator is more meant for simple sites and to quickly scaffold out a basic website. Doing this starts to make it more complex as a templating language has to be used. Thanks for your suggestion though.
