### ISSUE TITLE
Production build

### ISSUE THREAD

**Issue by tobyl** [yeoman/generator-webapp#465]
Hi there - Something may be off, or I might simply be missing something. I'm able to run `gulp serve` and view BrowserSync just fine - But when I run `gulp` the `dist` folder is generated, but there doesn't appear to be a simple way to upload my entire folder to production - I would have to edit paths in the HTML to correct asset locations, or move files around.

Am I missing something? Thanks!

**Comment by silvenon** [comment]
We designed paths to assets to be very portable, so they should work anywhere if you just copy over the contents of `dist`. What doesn't work in particular?

**Comment by tobyl** [comment]
Based on the existing structure of the repo, the `app` directory is where the HTML files live, and the HTML file references scripts and styles in that folder. In order to deploy, it seems the minimal work required each time would be to upload the `app` folder, upload the `dist` folder and then alter the paths in the HTML file (or maintain two HTML files).

The system works perfectly in development, I'm just wondering about best practices for deployment.

Thanks for the response.

**Comment by silvenon** [comment]
In deployment you run `gulp`, then you upload only the generated `dist` directory to production. Why are you also uploading `app`?

**Comment by tobyl** [comment]
Ah - the problem was that I had a linting error in my javascript, which killed the gulp build - the `dist` folder is created, but incomplete. I see now exactly how deployment would work - which is fantastic, btw! Many thanks!

**Comment by silvenon** [comment]
Glad it works :+1: The linting failed silently or did it produce an output in the command line?

**Comment by tobyl** [comment]
it shows in the command line - I guess I didn't glance upwards since the `gulp` command ends with:

```
[10:29:20] Finished 'styles' after 1.34 s
[10:29:20] Finished 'scripts' after 1.08 s
[10:29:20] Finished 'extras' after 829 ms
[10:29:20] Finished 'fonts' after 855 ms
```

Rather than an indication that the entire tasks failed. This is definitely my mistake - I just wasn't sure if I was missing something, which I was..

**Comment by silvenon** [comment]
Yeah, always look in the command line just to be safe :wink:

**Comment by patrickcorrigan** [comment]
Aha this got me too :+1:
