### ISSUE TITLE
Add jshintrc to template, fixes JSLint ES6 warnings

### ISSUE THREAD

**Issue by 47ronin** [yeoman/generator-webapp#466]
- Add routine to build `.jshintrc` during scaffolding process
- Add `jshintrc` to `templates/`

jshintrc should at least contain:
`{
  "esnext": true
}`

Without this, out of the box, a scaffolded project's `gulpfile.babel.js` generates a ton of JSLint warnings.

**Comment by neilhem** [comment]
This generator uses ESLint for linting js files. Make sure that you use latest version available.
