### ISSUE TITLE
gulp command fails. 

### ISSUE THREAD

**Issue by joepegler** [yeoman/generator-webapp#467]
Getting this for a fresh installation on Ubuntu 15.10. 

`/home/xx/node_modules/gulp-util/lib/PluginError.js:73
  if (!this.message) throw new Error('Missing error message');
                           ^
Error: Missing error message
`

[http://i.imgur.com/s7jsm1k.png]

**Comment by joepegler** [comment]
'gulp styles' is the culprit...

**Comment by cvasquez** [comment]
Having the same issue here. Would appreciate any help.

**Comment by joepegler** [comment]
I had to roll back the previous version that uses grunt.

**Comment by silvenon** [comment]
Which Node version are you running? Try using v4 or later.

If that doesn't work, this is a stretch, but try using [gulp-postcss](https://github.com/postcss/gulp-postcss) + [autoprefixer](https://github.com/postcss/autoprefixer) instead of gulp-autoprefixer. So instead of this:

``` js
// in the styles task
.pipe($.autoprefixer({browsers: ['> 1%', 'last 2 versions', 'Firefox ESR']}))
```

write this:

``` js
// along with other imports
import autoprefixer from 'autoprefixer';
```

``` js
// in the styles task
.pipe($.postcss([
  autoprefixer({browsers: ['> 1%', 'last 2 versions', 'Firefox ESR']})
]))
```

**Comment by sassquad** [comment]
I tried the above also, but this fails. Using node v0.10.42 and npm v3.7.3 on Mac OS X El Capitan:

```
TypeError: Object #<Object> has no method 'postcss' at 
Gulp._gulp2.default.task._gulp2.default.src.pipe.pipe.pipe.pipe.pipe.pipe.reload.stream 
(gulpfile.babel.js:22:13)
```

Having used nvm to install node v4.3.1 and switch accordingly, the build now proceeds without incident.

**Comment by cvasquez** [comment]
Thanks so much @sassquad - node 4.3.1 worked for me!

**Comment by silvenon** [comment]
@sassquad before trying the 2nd version you need to install `gulp-postcss` and `autoprefixer`. But I'm glad you got it working with a newer version of Node, that was the problem then :+1: 

I'll reopen if that doesn't fix it for @joepegler.

**Comment by sassquad** [comment]
@cvasquez - Glad to be of help!

@silvenon - I'll look into your suggestion when I get near my computer later.

**Comment by sassquad** [comment]
@silvenon Sorry for the delay - I've only had a short time to look into this. **Notably, I haven't updated the generator to take into account the new update referenced in #471**

I reverted to the prior node version, installed those two npm modules, and did `gulp serve,` but got a new error instead (pathnames truncated) :

```
.../node_modules/gulp-util/lib/PluginError.js:73
    if (!this.message) throw new Error('Missing error message');
                       ^
Error: Missing error message
at new PluginError (.../node_modules/gulp-util/lib/PluginError.js:73:28)
```

When I went back to the newer node, everything worked fine. 

On this basis, looks like it's better to go out with the old and in with the new :smile:

**Comment by silvenon** [comment]
Yeah, it's probably unrealistic to still support 0.x versions, considering apparently our deps are dropping support.
