### ISSUE TITLE
Build-Process totally ignores content of build:js blocks

### ISSUE THREAD

**Issue by tpinne** [yeoman/generator-webapp#469]
In my html-file I have a block like the following. Picking only the components I need from some bower components.

```
<!-- build:js scripts/vendor.js -->
<!-- bower:js -->
    <script src="/bower_components/jquery/dist/jquery.js"></script>
    <script src="/bower_components/sticky-kit/jquery.sticky-kit.min.js"></script>
    <script src="/bower_components/matchHeight/dist/jquery.matchHeight-min.js"></script>
    <script src="/bower_components/FitText.js/jquery.fittext.js"></script>
    <script src="/bower_components/list.js/dist/list.js"></script>
    <script src="/bower_components/formstone/src/js/core.js"></script>
    <script src="/bower_components/formstone/src/js/mediaquery.js"></script>
    <script src="/bower_components/formstone/src/js/swap.js"></script>
    <script src="/bower_components/formstone/src/js/touch.js"></script>
    <script src="/bower_components/formstone/src/js/scrollbar.js"></script>
    <script src="/bower_components/formstone/src/js/dropdown.js"></script>
    <script src="/bower_components/formstone/src/js/checkbox.js"></script>
    <script src="/bower_components/formstone/src/js/tabs.js"></script>
    <script src="/bower_components/bootstrap-sass/assets/javascripts/bootstrap/collapse.js"></script>
<!-- endbower -->
<!-- endbuild -->
```

But the generated file contains **all** files from **each** bower component. Which is not the same behaviour as I recall from the grunt version. And totally breaks the build because there are components with naming conflicts, because for example _formstone_ and _bootstrap_ provide a _dropdown_ jQuery plugin.

Do I miss something or am I doing anything wrong?

**Comment by tpinne** [comment]
A little update:

Even if trim the section down to 

```
<!-- build:js scripts/vendor.js -->
    <script src="/bower_components/jquery/dist/jquery.js"></script>
<!-- endbuild -->
```

all files from the bower components are merged into `vendor.js`. If I clear it up to an empty section

```
<!-- build:js scripts/vendor.js -->
<!-- endbuild -->
```

then no `vendor.js` will be inserted at all.

**To sum it up:** At the moment I only can have everything or nothing merged into vendor.js. Which ends up in conflicts in my current project and is beside from that not the desired behaviour, since one wants to be able to only include the parts of a bower component for production which are really needed.

**Comment by neilhem** [comment]
Why not just exclude bootstrap js files?

**Comment by tpinne** [comment]
@neilhem It's not just bootstrap. I would have to exclude all files from all third party components I don't want in the build file. But I think that's not the place for this common scenario, when there is actually a part in the html file where you reference the needed files that the build process should use.
I would have to exclude all bootstrap files but one, 50% of the formstone components, ...
That's not the process as I recall it from the grunt version of this generator.

**Comment by wa-rren-dev** [comment]
@tpinne I don't know if it's anything to do with the issue you're describing above but we've just diagnosed an issue with the overall concat & uglification of the whole vendor.js file. The only way to avoid was to split the vendor references into smaller groups, thereby excluding the use of wiredep. It's the only way we could get a project to successfully build.

**Comment by silvenon** [comment]
@tpinne `wiredep` will run automatically as soon as you change `bower.json` while running `gulp serve`. You shouldn't change anything between `bower:ext` comments, because wiredep will overwrite those. You should manually select plugins that you need with the `overrides` option, or exclude those that you don't need using the `exclude` option. Check [wiredep's configuration](https://github.com/taptapship/wiredep#configuration) for more info.

How did grunt version work differently? If it let you to manually remove stuff between `bower:ext` comments, that was a bug.

**Comment by tpinne** [comment]
@silvenon thanks for pointing me in the right direction. It seems I totally had luck in the past that there haven't been conflicts or anything. Now it seems everything is up and running right in time. Thanks very much.
