### ISSUE TITLE
Curious: why default in main.scss restricts container to 730px?

### ISSUE THREAD

**Issue by nowherenearithaca** [yeoman/generator-webapp#474]
This is simply a question about the rationale for these lines in main.scss as a default

@media screen and (min-width: 768px) {
  .container {
    max-width: 730px;
  }

When you bring in bootstrap csss before main.scss (which I assume is what you would want to do), this default in main.scss overrides the bootstrap defaults that will let container be larger when the screen is larger.

This results in the .container class being restricted to 730px no matter how large the screen is, as far as I can tell.

Of course one can change it from the default in main.scss (or remove it), but I was wondering if there were some other reason for doing this.

**Comment by silvenon** [comment]
It looks nicer because there aren't multiple columns in the initial design, the default width looks too wide. But thanks for raising this issue, I was wondering the same for a second :smile:
