### ISSUE TITLE
Why there's no gruntfile.js on the project which created with "yo webapp"?? 

### ISSUE THREAD

**Issue by Derekc1031** [yeoman/generator-webapp#475]
HI, all

I'm totally freshman to yeoman, 
I created two projects with yeoman : 
1. one was created with command "yo webapp" (only selected "sass" and "bootstrap")
2. the other was created with command "yo angular". 

After that, I couldn't find any gruntfile.js but gulpfile.babel.js on the project with command "yo webapp",
but I could find the gruntfile.js if I created a project with command "yo angular" .

Why?? Is it normal to "yo webapp" ??

**Comment by neilhem** [comment]
generator-webapp uses [Gulp](http://gulpjs.com/) as a build system instead of [Grunt](http://gruntjs.com/), so it's normal absence of Gruntfile.js file

**Comment by Derekc1031** [comment]
Thx, neilhem!

May I  know that is there any way to use Grunt as default build system if I use generator-wabapp to scaffold a website project?

**Comment by silvenon** [comment]
Yes. You can checkout the `legacy-grunt` branch and `npm link` that as the generator.

``` sh
$ git clone https://github.com/yeoman/generator-webapp
$ cd generator-webapp
$ git checkout legacy-grunt
$ npm link # this will install dependencies and link it as the global package
$ cd path/to/your/project
$ yo webapp
```

Let me know if that works.
