### ISSUE TITLE
Feature Request: wire up test files

### ISSUE THREAD

**Issue by pebcakerror** [yeoman/generator-webapp#477]
Would it be possible to use wiredep (or something else) to wire up files for test/index.html in the same way it wires everything up for app/index.html.

I would expect it to wire up bower, source files, and test files.

**Comment by silvenon** [comment]
We removed Bower (and wiredep) in [v4.0.0-0](https://github.com/yeoman/generator-webapp/releases/tag/v4.0.0-0), so at the moment you have to wire dependencies manually. We hope to remove that in the future by using a module bundler or something.
