### ISSUE TITLE
Handlebars Recipe

### ISSUE THREAD

**Issue by codeofsumit** [yeoman/generator-webapp#480]
just did a fresh install with this generator, created the app and followed [this](https://github.com/yeoman/generator-webapp/blob/master/docs/recipes/handlebars.md) recipe to include handlebars

This is the error I'm getting once I create my first file `intro.hbs` inside `app/templates`.

```
Uncaught Error: Template was precompiled with an older version of Handlebars than the current runtime. Please update your precompiler to a newer version (>= 4.0.0) or downgrade your runtime to an older version (>= 2.0.0-beta.1).
```

I'd like not to use any precompilation. Plain client side templating.

Any ideas what might have changed since writing of the handlebars recipe?

**Comment by pebcakerror** [comment]
https://github.com/lazd/gulp-handlebars#compiling-using-a-specific-handlebars-version

```
npm install --save-dev handlebars
```

```
...
.pipe($.handlebars({
  handlebars: require('handlebars')
}))
...
```

**Comment by codeofsumit** [comment]
thanks! Gonna try that later today.
Do you mind explaining the workflow behind this?
Will the template files get precompiled during the gulp build and the compiled files will get served in the `/dist` folder?

**Comment by codeofsumit** [comment]
my mistake. Everything worked fine when not using the latest handlebars version but the one that is used in gulp-handlebars (3.0.0) as it was written in the recipe. I think I overread that before.

Everything is working now.

Thanks!
