### ISSUE TITLE
Error: Requiring external module babel-register

### ISSUE THREAD

**Issue by timothylombrana** [yeoman/generator-webapp#482]
Getting error when running gulp serve, I've fixed this before by removing the entire webapp repo from local. Any and all help/advice appreciated, also please forgive if I've not formatted this issue as correctly as possible(first issue ever opened). Would like to resolve this without having to do this. gulp serve throws the following: 

`Requiring external module babel-register
node_modules/babel-core/lib/transformation/file/options/option-manager.js:372
          throw new Error("Couldn't find preset " + JSON.stringify(val) + " relative to directory " + JSON.stringify(dirname));
          ^
`

**Comment by silvenon** [comment]
@alphapilgrim sorry for the super late response. These babel-register errors totally bum me out because we've been receiving a lot of them and I have no idea how they happen. Could we set up some kind of screen share or, better yet, a [tmate](https://tmate.io/) session?

**Comment by timothylombrana** [comment]
@silvenon I don't think I could replicate. I removed the generator and did a brand new install. Works fine now, but kind of a pain, since this is the second time I've had to do this.

**Comment by silvenon** [comment]
:confused: Well, let me know if that happens again.

**Comment by Saul3d** [comment]
I"m gettng this same error.  I've provided a screen capture of what I've been getting.
![screen shot 2016-07-27 at 9 59 59 pm](https://cloud.githubusercontent.com/assets/1847649/17199832/9ab1c922-5445-11e6-8e73-85d2e90c4b22.png)

**Comment by neilhem** [comment]
@Saul3d have you already tried to reinstall node modules?

**Comment by silvenon** [comment]
Yeah, babel-preset-es2015 is missing in your case.
