### ISSUE TITLE
UnCSS gulp task

### ISSUE THREAD

**Issue by sjparida** [yeoman/generator-webapp#484]
I am new to automation, using generator-webapp for a simple bootstrap website, need help with the following:
1. how can I add uncss ( can't see **require** in gulp file), 
2. where to add gulp task for Uncss

**Comment by silvenon** [comment]
It's best to put this as part of the production build step, i.e. in the `html` task. Currently we're running cssnano, but you can combine [uncss](https://github.com/ben-eb/gulp-uncss) and cssnano using [lazypipe with gulp-if](https://github.com/robrich/gulp-if#works-great-with-lazypipe).

**Comment by michaeloxborrow** [comment]
Can you provide an example?
Here is my html task:

``` js
gulp.task('html', ['styles', 'scripts'], () => {
  return gulp.src('app/*.html')
    .pipe($.useref({searchPath: ['.tmp', 'app', '.']}))
    .pipe($.if('*.js', $.uglify()))
    .pipe($.if('*.css', $.cssnano()))
    .pipe($.if('*.html', $.htmlmin({collapseWhitespace: true})))
    .pipe(gulp.dest('dist'));
});
```

**Comment by silvenon** [comment]
I haven't tested it, but by following [these docs](https://github.com/robrich/gulp-if#works-great-with-lazypipe) you can do something like this:

``` js
const stylesChannel = lazypipe()
  .pipe($.uncss, { html: 'app/*.html' })
  .pipe($.cssnano);

gulp.task('html', ['styles', 'scripts'], () => {
  return gulp.src('app/*.html')
    .pipe($.useref({searchPath: ['.tmp', 'app', '.']}))
    .pipe($.if('*.js', $.uglify()))
    .pipe($.if('*.css', stylesChannel()))
    .pipe($.if('*.html', $.htmlmin({collapseWhitespace: true})))
    .pipe(gulp.dest('dist'));
});
```

**Comment by michaeloxborrow** [comment]
Thanks, I installed lazypipe and added this line to my gulpfile:
var lazypipe = require('lazypipe');

I get this error:

Invalid call to lazypipe().pipe(): no stream creation function specified at validateStep

**Comment by simonbuehler** [comment]
hi,
reached the same point today, new to this and want to plug uncss into this setup. @michaeloxborrow could you give me a hint on how you succeeded?

**Comment by michaeloxborrow** [comment]
I didn't.
I gave up.
JavaScript uses CSS which can get missed.

**Comment by silvenon** [comment]
Yeah, that's why I shy away from those tools. There's feature coming to Chrome DevTools for auditing CSS, basically you start auditing, click around your app and DevTools highlights which parts of your CSS are not being used. I think that feature is in Canary, Paul Irish talked about it, but I wasn't able to find it.
