### ISSUE TITLE
task html --> css with cssnano (aggressive optimisations by default)

### ISSUE THREAD

**Issue by jolugama** [yeoman/generator-webapp#488]
In the web--> "cssnano enables aggressive optimisations by default, which might not always be what you want. Set options.safe to true if you want to disable this. In future versions, only safe options will be enabled by default, starting from version 4".

I have had several problems when using nano css. I have arranged this way:
  .pipe($.if('*.css', $.cssnano({safe: true})))

That's all folks

**Comment by silvenon** [comment]
@jolugama I agree. Could you submit a PR? :grin: If you don't have time, that's ok.

**Comment by silvenon** [comment]
Fixed with #489.
