### ISSUE TITLE
Task wiredep not including link tags

### ISSUE THREAD

**Issue by lnmunhoz** [yeoman/generator-webapp#493]
I added bootstrap and font-awesome with bower but its not being added to my index file. I'm using less recipe but I need the `bootstrap.css` in the index.

**Comment by lnmunhoz** [comment]
Fixed using .bower.json

**Comment by ryanburnett** [comment]
@lnmunhoz I'm having the same issue. A couple questions:
- Is the location of this `bower.json` in the project root?
- Can you please post the entire code of this `bower.json`?

**Comment by lnmunhoz** [comment]
@ryanburnett 
- Yes
- This is my `bower.json`:

``` json
{
  "name": "package",
  "version": "0.0.0",
  "dependencies": {
    "modernizr": "~2.8.3",
    "normalize-css": "~3.0.2",
    "bootstrap": "^3.3.6",
    "ajaxchimp": "^1.3.0"
  },
   "overrides": {
    "bootstrap": {
      "main": [
        "dist/css/bootstrap.min.css",
        "dist/js/bootstrap.min.js"
      ]
    }
  }
}
```

The `main` configuration of bootstrap uses `bootstrap.less` so this is why we need to do this to use the css file by default. You can check this configs on `bower_components/bootstrap/.bower.json`.

This is my `wiredep` task in case you need it.

``` js
gulp.task('wiredep', function() {
  var wiredep = require('wiredep').stream;

  gulp.src('app/css/*.scss')
    .pipe(wiredep({
      ignorePath: /^(\.\.\/)+/
    }))
    .pipe(gulp.dest('app/css'));

  gulp.src('app/*.html')
    .pipe(wiredep({
      ignorePath: /^(\.\.\/)*\.\./
    }))
    .pipe(gulp.dest('app'));
});
```

Hope this help you! Good luck :)
