### ISSUE TITLE
bower install a package - wiredep not inserting the package into html

### ISSUE THREAD

**Issue by miketricking** [yeoman/generator-webapp#497]
http://yeoman.io/codelab/install-packages.html following this tutorial which references grunt instead of gulp however - after running: bower install --save angular-ui-sortable the package is added to bower_components fine. If i then run gulp serve or gulp and it builds, it has not added the dependency in my index.html file.

It still just shows all the bootstrap scripts

also if I then add it in manually (which I was hoping I didn't need to)

it is no good because the index.html file in dist still references /bower_components for angular ui yet for all the bootstrap js file it only references vendor

**Comment by silvenon** [comment]
You need to `bower install` stuff **after** running `gulp serve`. Read [this section](https://github.com/yeoman/generator-webapp/tree/master/docs#bower) to understand that `gulp serve` watches your `bower.json` for changes and runs `gulp wiredep`. If you ran `bower install` without `gulp serve` running, you can run `gulp wiredep` manually.

**Comment by miketricking** [comment]
I have already ran gulp serve prior to doing this

**Comment by silvenon** [comment]
@miketricking running `gulp wiredep` does nothing? There is no angular-ui-sortable between the `bower:css` comments?

**Comment by miketricking** [comment]
It has been added above all the bootstrap js files so rather than in plugins.js it has been put in vendor.js which probably makes sense to be fair! thanks

**Comment by rizqinizamil** [comment]
@silvenon Sorry if I posted here. I have same issue. Even running `gulp wiredep` it does nothing.
Any thoughts?

**Comment by rizqinizamil** [comment]
@silvenon Oops, sorry my fault. Ignore it. Thanks.
