### ISSUE TITLE
Generator-webapp do not create glupfile, but gruntfile

### ISSUE THREAD

**Issue by mizhdi** [yeoman/generator-webapp#498]
...

**Comment by neilhem** [comment]
Double check if you are using latest version of generator, try to update installed version `npm install --global generator-webapp`

**Comment by mizhdi** [comment]
first: npm install --global yo  
It's ok now

**Comment by lifeonlars** [comment]
I had to run  `npm install generator-webapp@^2.0.0` in order to finally get it working

**Comment by silvenon** [comment]
When updating major versions of npm packages, you should either run `npm install package@2` or `npm install package@latest`.
