### ISSUE TITLE
images problem after renaming or moving

### ISSUE THREAD

**Issue by abumalick** [yeoman/generator-webapp#501]
Hello,
Thanks for your work.
I had a problem when I was moving images or copying them. It was not being copied, or it was copied with its old name. It quite bored me.
The problem comes from the cache.
It was fixex fallowinf this post : 
http://stackoverflow.com/questions/21532903/strange-images-issue-with-gulp-js
using gulp-newer : 

`npm install gulp-newer --save-dev`
and int gulpfile:

```
gulp.task('images', () => {
  return gulp.src('app/images/**/*')
    .pipe($.newer('dist/images'))
    .pipe($.imagemin({
      progressive: true,
      interlaced: true,
      // don't remove IDs from SVGs, they are often used
      // as hooks for embedding and styling
      svgoPlugins: [{cleanupIDs: false}]
    }))
    .pipe(gulp.dest('dist/images'));
});
```

**Comment by UlisesGascon** [comment]
To keep things organized, I’m going to close it for now. If this is still a problem or becomes relevant again, @abumalick, please feel free to reopen it or create a new issue with updated details.
