### ISSUE TITLE
jQuery?

### ISSUE THREAD

**Issue by 3ilguun** [yeoman/generator-webapp#503]
Where can i change the jQuery version? I can't find it in `package.json` file.

**Comment by neilhem** [comment]
Look at `bower.json`

**Comment by 3ilguun** [comment]
Nope.

```
 "private": true,
 "dependencies": {
    "bootstrap-sass": "~3.3.5",
    "modernizr": "~2.8.1",
    "html5shiv": "^3.7.3",
    "d3": "^3.5.16",
    "c3": "^0.4.10",
    "nvd3": "^1.8.2"
  },
  "overrides": {
    "bootstrap-sass": {
      "main": [
        "assets/stylesheets/_bootstrap.scss",
        "assets/fonts/bootstrap/*",
        "assets/javascripts/bootstrap.js"
      ]
    }
  },
  "devDependencies": {
    "chai": "^3.5.0",
    "mocha": "^2.4.5",
    "sortable": "^0.8.0",
    "select2": "^4.0.2",
    "select2-bootstrap-theme": "^0.1.0-beta.4",
    "bootstrap-datepicker": "^1.6.0",
    "jquery-validation": "^1.15.0",
    "bootstrap-validator": "^0.10.1",
    "jquery.cookie": "jquery-cookie#^1.4.1",
    "jquery-confirm": "^2.5.2"
  }
```

**Comment by neilhem** [comment]
If you choose jquery option when you run `yo webapp` it will be added to your bower.json automatically and will be installed to bower_components folder. Also you can install jquery via bower or npm running `bower install jquery --save` or `npm install jquery --save`

**Comment by 3ilguun** [comment]
Yes, I chose option from `yo webapp`.

Also i reinstalled the jQuery with `bower install jquery#1.12.3 --save-dev` and `bower update` all same. Doesn't add automatically into my bower.json.

**Comment by silvenon** [comment]
Bootstrap depends on jQuery, so we don't explicitly add it if Bootstrap is included. It looks like you want to add it as a development dependency, so your command should work just fine. Can you try it in an isolated environment, just `bower install jquery#1.12.3 --save-dev` to see if it was added in dev dependencies?

**Comment by 3ilguun** [comment]
Nope, `bower install jquery#1.12.3 --save-dev` doesn't add in my dev dependencies.

I've reinstalled everything in other folder and this time works. I don't know what problem was but guess it was my fault.
