### ISSUE TITLE
Update Jade recipe

### ISSUE THREAD

**Issue by 3ilguun** [yeoman/generator-webapp#504]
[This](https://github.com/BrowserSync/browser-sync/issues/1059).
#### `jade-watch`

Need a seperate task for watching jade templates:
`gulp.task('jade-watch', ['views'], reload);`
#### `serve`

``` diff
 gulp.task('serve', ['views', 'styles', 'scripts', 'fonts'], () => {
   ...
   gulp.watch([
     'app/*.html',
-    '.tmp/*.html',
     'app/images/**/*',
     '.tmp/fonts/**/*'
   ]).on('change', reload);

-  gulp.watch('app/**/*.jade', ['views']);
+  gulp.watch('app/**/*.jade', ['jade-watch']);
```

**Comment by silvenon** [comment]
There are two possible solutions, other than the one you proposed:
1. `'.tmp/*.html'` shouldn't be in `gulp.watch`, does just removing it solves the problem for you?
2. solution 1 + remove `.pipe(reload({stream: true}))` and add `reload` to the array tasks when watching `.jade` files, i.e. `['views', reload]`

If none of these work, I'll use the solution you proposed.

**Comment by 3ilguun** [comment]
Just checked and both works.

**Comment by silvenon** [comment]
Fixed.
