### ISSUE TITLE
"Automagically wire-up dependencies installed with Bower" <-- does this work

### ISSUE THREAD

**Issue by codeofsumit** [yeoman/generator-webapp#506]
currently no dependencies are automatically wired-up. I have to include everything by hand inside the index.html. Even my own JS files. Is that normal?

**Comment by silvenon** [comment]
Does [this checklist](https://github.com/yeoman/generator-webapp/blob/master/docs/README.md#bower) help? What happens when you run `gulp wiredep`?

**Comment by silvenon** [comment]
Your own JS files are not automatically wired up, because we don't know in which order you might want to put them and whether you are compiling them [with browserify](https://github.com/yeoman/generator-webapp/blob/master/docs/recipes/browserify.md) etc.

**Comment by seb-thomas** [comment]
nb. The gulp wiredep task has to be running for it to notice a bower installed lib. This will be running as part of `gulp serve`

**Comment by silvenon** [comment]
Close due to inactivity. If this is still an issue, I'll reopen.
