### ISSUE TITLE
[$compile:tpload] Failed to load template: components/home.html (HTTP status: 404 Not Found)

### ISSUE THREAD

**Issue by timothylombrana** [yeoman/generator-webapp#508]
Getting this error when I run gulp serve:dist. Works fine with gulp serve, I've tried getting an answer from stackoverflow, no luck. Here is a snippet of the directive which says it cannot find the file.

```
function contentArea() {
'use strict';

console.log('contentArea');

/*global angular:angular */

return {
    restrict: 'E',
    scope: false,
    templateUrl: 'components/home.html'
   };
}

angular
  .module('app')
  .directive('contentArea', contentArea);
```

**Comment by silvenon** [comment]
This is generator-webapp, not [generator-angular](https://github.com/yeoman/generator-angular) (if that's the one you were aiming for).
