### ISSUE TITLE
Compiled CSS outputting random z-index values.

### ISSUE THREAD

**Issue by jaysunwalter123** [yeoman/generator-webapp#509]
I'm getting a very strange issue that I've never seen before. My compiled CSS is outputting incorrect z-index values. For example, I set my z-index to 600, which the temporary CSS outputs correctly, but after a gulp build it gets set to 12. Do you have any idea what might do something like this?

Thanks.

**Comment by neilhem** [comment]
Yeah, it is the result of optimization of your css with [cssnano's](http://cssnano.co/optimisations/) optimise z-index.

**Comment by kevva** [comment]
This should be disabled by default if you have `safe: true` in your options https://github.com/yeoman/generator-webapp/blob/master/app/templates/gulpfile.babel.js#L76.
