### ISSUE TITLE
Font-Awesome don´t get copied & scss ignores variables on build

### ISSUE THREAD

**Issue by frankis** [yeoman/generator-webapp#511]
gulp serve includes font-awesome correctly but generated main.css shows `.fa-glass:before {
  content: "";
}` for each icon instead its value such as `.fa-glass:before {
  content: "\f000";
}`

In addition the related font-files don´t get copied?!
What am I doing wrong?

**REPRO:**
install generator-webapp
create / run webapp
add font-awesome using bower (to bower_components, no overrides)
run gulp serve

The site loads well, all styles are combined but main.css

**Comment by frankis** [comment]
oops... great if the question includes the answer! Override...
Adding the following to the bower.json does the "magic":

`
    "font-awesome": {
      "main": [
      "./scss/font-awesome.scss",
      "./fonts/*"
      ]
    }
`

**Comment by ryanburnett** [comment]
@frankis I'm having the same issue. A couple questions:
- Is the location of this `bower.json` in the project root?
- Can you please post the entire code of this `bower.json` file?

**Comment by frankis** [comment]
Hi Ryan, I used the webapp boilerplate just for learning purposes and didn´t keep the code.
The following hopefully helps to get things sorted for you.
1. Yes - after running "yo webapp" you will find the bower.json in the projects root
2. If you went with bootstrap, your bower.json should look somewhat like this after adding "my solution":
   
   ```
   ...
   "overrides": {
   "bootstrap-sass": {
     "main": [
       "assets/stylesheets/_bootstrap.scss",
       "assets/fonts/bootstrap/*",
       "assets/javascripts/bootstrap.js"
     ]
   },
   "font-awesome": { 
     "main": [ 
       "./scss/font-awesome.scss", 
       "./fonts/*" 
     ] 
   } 
   },
   ...
   ```
