### ISSUE TITLE
gulp build error

### ISSUE THREAD

**Issue by AlexandreKilian** [yeoman/generator-webapp#512]
Hi,

Straight out of the box (yo webapp), I get the following error when trying to build:

```
[20:34:35] Starting 'html'...

events.js:160
      throw er; // Unhandled 'error' event
      ^
Error
    at new JS_Parse_Error (eval at <anonymous> (/Users/alex/www/Webapp/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1526:18)
    at js_error (eval at <anonymous> (/Users/alex/www/Webapp/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:1534:11)
    at croak (eval at <anonymous> (/Users/alex/www/Webapp/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2026:9)
    at token_error (eval at <anonymous> (/Users/alex/www/Webapp/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2034:9)
    at unexpected (eval at <anonymous> (/Users/alex/www/Webapp/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2040:9)
    at expr_atom (eval at <anonymous> (/Users/alex/www/Webapp/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2554:9)
    at maybe_unary (eval at <anonymous> (/Users/alex/www/Webapp/node_modules/uglify-js/tools/node.js:22:1), <anonymous>:2716:19)
```

**Comment by celestial-labs** [comment]
same here. 
When I remove line 58, 59 and 60 it works. (Without minified and compressed html, js, css)

.pipe($.if('_.js', $.uglify()))
.pipe($.if('_.css', $.cssnano()))
.pipe($.if('*.html', $.htmlmin({collapseWhitespace: true})))

**Comment by romanenko** [comment]
I had this error after updating my `node` version to `6.0.0`. Upgrading version of `gulp-if` in `package.json` fixed issue for me:

```
"gulp-if": "^2.0.0",
```

**Comment by TheCulprit** [comment]
Can confirm romanenko's fix.

**Comment by AlexandreKilian** [comment]
yes, that fixes it

**Comment by joshuamanns** [comment]
Confirming that updating gulp-if to ^2.0.0 worked. Thanks @romanenko

**Comment by riteshetymon** [comment]
Also worked for me after updating gulp-if@2.0.1 Thanks **@romanenko**

**Comment by hamidhadi** [comment]
@romanenko  I have nodejs with `5.1.0` version. after I changed `"gulp-if"` in `package.json` file and run `npm install`, I still have problem.

**Comment by MohamadAbbas** [comment]
@Hamiid Please install gulp-util and check on error logs for more detail.

**Comment by hamidhadi** [comment]
@MohamadAbbas Sorry, but how can I use `gulp-util` in yeoman project. I have this in my `node_modules` folder.

**Comment by MohamadAbbas** [comment]
you need to install it using npm install gulp-util

**Comment by hamidhadi** [comment]
@MohamadAbbas Thanks. I just installed that with `npm install` command. Is this log errors on terminal with `gulp` command or I should define another `gulp` task?
When I run `gulp` command, I don't get any additional log error :(.
I also update my node version.

**Comment by MohamadAbbas** [comment]
``` js
var gutil = require('gulp-util');

gulp.task('coffee', function() {
   gulp.src(testfiles)
      .pipe(coffee())
      .on('error', gutil.log);
}
```

check above usage of gulp-util.

**Comment by hamidhadi** [comment]
@MohamadAbbas Thanks. I had problem in my html files.

**Comment by lesliebuying** [comment]
@romanenko Thanks!

**Comment by ghost** [comment]
Thanks very much! @romanenko

**Comment by Nidhi-Garg1** [comment]
@anyone Please help. I am also getting this error
events.js:160
      throw er; // Unhandled 'error' event
      ^
 Error: templates.js: error: couldn't process source due to parse error
Bad character escape sequence (150:38)

After commenting the following code in gulpfile.js it works perfectly.

.pipe(concatJs('templates.js'))
  .pipe(ngAnnotate())
 .pipe(uglify())
