### ISSUE TITLE
HTTPS and pathing problems after deploying to a sub-directory

### ISSUE THREAD

**Issue by moneytree-doug** [yeoman/generator-webapp#512]
I am deploying to a sub-directory (example.com/staging/) and it keeps trying to compile my SASS web fonts the wrong way. All my fonts and templates are being attempted on ``example.com/styles/fonts/font-awesome.scss`` instead of ``example.com/staging/styles/fonts/font-awesome.scss``. Also, it's not using HTTPS to grab these assets. I spend a few hours trying to get the Gruntfile correct with no avail. Can anyone direct me towards the right direction?

**Comment by silvenon** [comment]
Support questions are best asked on [StackOverflow](http://stackoverflow.com/questions/tagged/yeoman) under the tag `yeoman`. After posting the question there, you can link it here and I'll answer. But please provide more information, how you are including FontAwesome, what does your Gruntfile look like etc.

**Comment by moneytree-doug** [comment]
@silvenon  I posted it here: http://stackoverflow.com/questions/28781500/how-to-deploy-a-yeoman-project-to-a-sub-directory
