### ISSUE TITLE
Split tasks across multiple files

### ISSUE THREAD

**Issue by seb-jean** [yeoman/generator-webapp#516]
Hello,

On github of Gulpjs, a best practise is to splitted tasks across multiple files : [https://github.com/gulpjs/gulp/blob/master/docs/recipes/split-tasks-across-multiple-files.md](url)

It might be interesting to put this in place :)

**Comment by silvenon** [comment]
I already tried this with Grunt and it didn't work out. The fatigue of having to categorize tasks and jumping between files is greater than the small benefit of doing this. Also, gulpfiles are much smaller, therefore easier to manage.

**Comment by silvenon** [comment]
Also, those don't seem to be best practice, they are just recipes for those who want it.
