### ISSUE TITLE
Using external config file

### ISSUE THREAD

**Issue by seb-jean** [yeoman/generator-webapp#517]
Hello,

On github of Gulpjs, a best practise is to using external config file: https://github.com/gulpjs/gulp/blob/master/docs/recipes/using-external-config-file.md.

It might be interesting to put this in place :)

**Comment by silvenon** [comment]
@sindresorhus @kevva because this has been requested multiple times (#472, #295…), do you think we should finally add it?

**Comment by seb-jean** [comment]
Yes, i think that it's a good thing :).

**Comment by sindresorhus** [comment]
It being requested multiple times doesn't necessarily mean it's a good thing. People request it because it's a popular pattern. It can indeed make sense if you have a really huge gulpfile, but I still think it's a premature modularization in this case.
