### ISSUE TITLE
Wiredep problems

### ISSUE THREAD

**Issue by musdy** [yeoman/generator-webapp#519]
I install packages with bower, and then link them to the via the footer:

```
<!-- bower:js -->
<script src="/bower_components/jquery/dist/jquery.js"></script>
<script src="/bower_components/slick-carousel/slick/slick.js"></script>
<!-- endbower -->
```

But everytime i install a new dependency, bower links get removed. This applies for css as well. Any idea how to solve it?

**Comment by silvenon** [comment]
The dependencies should be injecting automatically. If you have to manually add them, something is wrong, `gulp wiredep` should work.

Please list the exact steps, what you're doing and you expected to happen. (Reproduce this from the fresh install.)

**Comment by datnordstrom** [comment]
gulp wiredep doesn't get called during "gulp" or "gulp serve"

**Comment by neilhem** [comment]
Yeah, wiredep runs only on running `gulp serve` command and `bower.json` file changes. Otherwise run `gulp wiredep` manually

**Comment by silvenon** [comment]
We should run wiredep as a part of the `serve` task to avoid these problems. Currently gulp can't run tasks in sequence, but we can get around it by creating an `assets` task containing `styles`, `scripts` and `fonts`, which will depend on `wiredep`, then `serve` would simply depend on `assets`.

Not sure if there are drawbacks to this approach. If anyone's up for a PR, speak! 😉

**Comment by Trost123** [comment]
Alternatively, we could use [run-sequence](https://www.npmjs.com/package/run-sequence) to run gulp tasks in sequence.

**Comment by silvenon** [comment]
@Trost123 yeah, that's also a good workaround. 👍
