### ISSUE TITLE
Misunderstanding issues

### ISSUE THREAD

**Issue by thepossumstudio** [yeoman/generator-webapp#520]
These are minor issues from us but it easy to misunderstanding for a newbie.

It have 2 issues
1. Right now gulp file that generates from this generator is using es6 syntax so if we run gulp after we fresh install "yo webapp" it won't run by gulp until we change it from _gulpfile.js_ to _gulpfile.babel.js_

![yo_webapp_gulpfile_babel](https://cloud.githubusercontent.com/assets/19283344/15290616/e29607ba-1ba3-11e6-8c19-1e7e08718c2e.png)
1. during generator work it will ask us about to choose _BDD_ or _TDD_ for our mocha test code but once we choose _TDD_ style it generates a _describe_ syntax for us. (describe is in _BDD_ interface not _TDD_ according to from mocha official website https://mochajs.org/ interface section)

![yo_webapp_tdd_bdd](https://cloud.githubusercontent.com/assets/19283344/15290700/7b3cadd4-1ba4-11e6-99ef-df18af1135bd.png)
![yo_webapp_tdd_bdd_2](https://cloud.githubusercontent.com/assets/19283344/15290701/7b43797a-1ba4-11e6-9229-7536ad1b74a2.png)

Maybe this is our mistake from using the generator but if it didn't we think it good to help newbie use this generator easier.

Feel free to share the idea.
Thank you in advance.

**Comment by silvenon** [comment]
@thepossumstudio hey, thanks for being so clear and detailed!
1. This one puzzles me, Gulp is supposed to detect both `gulpfile.js` and `gulpfile.babel.js`, the difference being that `gulpfile.babel.js` should be parsed with Babel. I tried this myself and it works fine 😕
2. There is an open PR for this: yeoman/generator-mocha#40

I'll keep this open until these are resolved. Not sure what to do about the 1st issue. Does Gulp report that it cannot find the gulpfile?

**Comment by thepossumstudio** [comment]
Hi @silvenon .

that's a mystery too. gulp didn't report that it _cannot find_ but it reports SyntaxError.

After the fresh install from a generator  I use a command
"_gulp_" for build it then it throws this

>  Uncaught SyntaxError: Unexpected token () =>

![gulp_syntax_error](https://cloud.githubusercontent.com/assets/19283344/15309822/71e0adb0-1c14-11e6-86eb-e265d1694de3.png)

as we know that syntax came with es6 so I have to change _gulpfile.js_ to _gulpfile.babel.js_ and its work fine.

Anyway, I don't think  this will happen with everyone because I found the issues only some machines at my work but it good to leave some information for newbie guys.

**Comment by neilhem** [comment]
@thepossumstudio Double check that you use node version 4 or higher with latest version of generator-webapp

**Comment by silvenon** [comment]
What @neilhem said 😁

**Comment by thepossumstudio** [comment]
@neilhem Thanks for the advice.

I think that is the root cause of the problem since I found somehow my 

_node_ version at my workplace is lower than 4.X.X

after update to the latest version. it works well.

**Comment by neilhem** [comment]
@thepossumstudio glad that we helped you.
