### ISSUE TITLE
Keep repo info when new dist files generated.

### ISSUE THREAD

**Issue by calidion** [yeoman/generator-webapp#522]
to most of us, files in dist will be versionized with a git repo.

it would be nice to keep to the repo when new dist files generated.

**Comment by sindresorhus** [comment]
Can you elaborate? Not clear what you're asking.

**Comment by kevva** [comment]
Are you saying that you're having a git repository inside the `dist` folder that's getting deleted upon running gulp? It's not a good idea to version generated files.

**Comment by calidion** [comment]
@kevva  yes.

To versionize the generated files may not be a good idea, but it is very useful for sites in production, It enables the abilitiy to revoke what has distributed when errors found.

**Comment by calidion** [comment]
Here's one of my cases which is open source.
I use 
https://github.com/3gcnbeta/www (use yo webapp)
as the site's source code,
use 
https://github.com/3gcnbeta/3gcnbeta.github.io
as the site's  production code.

**Comment by kevva** [comment]
Change the clean task to not remove the whole `dist` directory but rather all files inside it (except `.git`).

``` js
gulp.task('clean', del.bind(null, ['.tmp', 'dist/**/*']));
```

**Comment by calidion** [comment]
thanks.
