### ISSUE TITLE
gulp-bower

### ISSUE THREAD

**Issue by seb-jean** [yeoman/generator-webapp#523]
Hello,
When we want to install components from bower of a new project, we forced use to the command bower install. While I think it would be nice that in a command line.

So, the idea would be to use https://www.npmjs.com/package/gulp-bower, create a new task with bower to install the components and use this task with serve gulp, gulp serve: test, gulp ...

**Comment by silvenon** [comment]
We removed Bower in [v4.0.0-0](https://github.com/yeoman/generator-webapp/releases/tag/v4.0.0-0) because it's deprecated.
