### ISSUE TITLE
generator without browserSync on gulp

### ISSUE THREAD

**Issue by Physium** [yeoman/generator-webapp#529]
I'm not sure if I'm the only one here that actually gets annoyed by the sync-ing functionality that browserSync provides. I wish to be able to open 2 separate browsers with the ability for each to do its own specific actions and not mimic each other actions. Is there a possibility to use gulp without the browser-sync-ing functionality of browserSync?

**Comment by silvenon** [comment]
You're not the only one, I don't find it particularly useful either. I think simply passing [`ghostMode: false`](https://www.browsersync.io/docs/options/#option-ghostMode) to Browsersync should work.

**Comment by Physium** [comment]
Thank you! that option has been helpful!
