### ISSUE TITLE
Error runing gulp

### ISSUE THREAD

**Issue by jrioscloud** [yeoman/generator-webapp#533]
When I run `gulp serve` everything works as it should. But everytime I run just `gulp` I get the following error. 

```
events.js:154
      throw er; // Unhandled 'error' event
      ^
Error: /var/www/html/nextrobotix.com/styles/vendor.css:1:1: Unknown word
wOFF

```

I even tryied commenting out all the files in main.scss but it still appears.

Here is the link to [the repo](https://github.com/papaponmx/next/tree/bourbon)

**Comment by neilhem** [comment]
Hi, your app has injection of font file instead of style file in https://github.com/papaponmx/next/blob/bourbon/app/index.html#L13

**Comment by jrioscloud** [comment]
Thanks so much. I apprecieate it, @neilhem
