### ISSUE TITLE
FR: PWA as a sub generator.

### ISSUE THREAD

**Issue by hemanth** [yeoman/generator-webapp#534]
It would be great if we would integrate [generator-pwa](https://github.com/hemanth/generator-pwa) as a sub generator?

//cc @addyosmani @SBoudrias @mklabs @sindresorhus

**Comment by mklabs** [comment]
What's a progressive web app ?

**Comment by mklabs** [comment]
I still need to read through @codepo8 article on their [regressive approach](https://www.christianheilmann.com/2016/05/31/progressive-web-apps-and-our-regressive-approach/)

**Comment by addyosmani** [comment]
Some getting started resources to understand what they are:
- https://developers.google.com/web/progressive-web-apps/
- https://addyosmani.com/blog/getting-started-with-progressive-web-apps/

**Comment by mklabs** [comment]
I quickly got through the App shell part to init a project recently. used https://github.com/GoogleChrome/application-shell I really liked the JS app shell (App controller, etc.)

**Comment by hemanth** [comment]
@mklabs I thought it was a #sarcasm :P you may also check [awesome-pwa](https://github.com/hemanth/awesome-pwa).

**Comment by UlisesGascon** [comment]
This issue has been open for a while, and it seems no volunteers are currently interested in working on it. I will proceed to close it for now, but we can reopen it if the idea gains more traction in the future.
