### ISSUE TITLE
Problem with adding own js-files

### ISSUE THREAD

**Issue by abondarenko** [yeoman/generator-webapp#535]
I've just tried to create and use my own js-file. I've placed it in /app/scripts/ folder. But gulp doesn't inject it to index.html. Nor 'scripts', nor 'serve' tasks didn't help.
Am I doing something wrong?

**Comment by neilhem** [comment]
hi, add path to your own js file manually in index.html

``` html
<!-- build:js scripts/main.js -->
<script src="scripts/main.js"></script>
<script src="scripts/own-file.js"></script>
<!-- endbuild -->
```

**Comment by abondarenko** [comment]
Yep, it works.
I thought I need to place my scripts somewhere outside of "build:js" section.

**Comment by silvenon** [comment]
If you don't want them concatenated and minified on build step. Otherwise why would you need to?

**Comment by abondarenko** [comment]
Do you propose to place all stuff in one place (main.js)?? :-o

**Comment by silvenon** [comment]
Just in production, which is a common performance pattern. That's what those `build` comments do.

**Comment by sscarduzio** [comment]
Please add this to the docs, I've been struggling in the past about this and today after 2 years.

**Comment by silvenon** [comment]
@sscarduzio thanks for letting us know, I've [added it](https://github.com/yeoman/generator-webapp/tree/master/docs#adding-new-assets) to the docs. Let me know if it's clear enough.
