### ISSUE TITLE
Use Web.gitattributes from Danimoth/gitattributes

### ISSUE THREAD

**Issue by wrumsby** [yeoman/generator-webapp#536]
Danimoth/gitattributes provides a collection of useful `.gitattributes` files.

Theoretically this generator could use the `Web.gittatributes` file from that project as the `.gitattributes` file it generates.

**Comment by sindresorhus** [comment]
I don't really see the point. Git is very good at detecting text/binary files, so manually specifying everything feels like a bloated anti-pattern.
