### ISSUE TITLE
Add BrowserSync

### ISSUE THREAD

**Issue by shakyShane** [yeoman/generator-webapp#54]
Considering this generator isn't doing anything fancy with the server, BrowserSync would be a good alternative to live reload.

Resources:

https://github.com/shakyShane/browser-sync
http://shakyshane.com/gulpjs-sass-browsersync-ftw/
https://github.com/quagliero/generator-gulp-webapp

Happy to send a PR if this would be of interest.

**Comment by sindresorhus** [comment]
Fixed in https://github.com/yeoman/generator-gulp-webapp/commit/b4878dc1306d52ba58b0226e8a9870600004209b
