### ISSUE TITLE
Working with JSON-files in jade-templates

### ISSUE THREAD

**Issue by mortennh** [yeoman/generator-webapp#541]
Thank you for your jade-receip, it really helped me!
For my navigation.jade i want to create a JSON-file so i can keep everything maintainable

ul.nav
-- li.nav__item
---- a.nav__link
------ svg.nav__icon
------ span.nav__title

How can I pass the this JSON to my jade-template?

**Comment by neilhem** [comment]
You can use https://www.npmjs.com/package/gulp-data to get data from json file

**Comment by silvenon** [comment]
Actually, it would be a bit silly for us to add gulp-data to every template recipe, and implementation of gulp-data is very arbitrary, so we will trust our users to figure it out on their own, or alternatively stumble upon this issue. 😄
