### ISSUE TITLE
Style of DSL

### ISSUE THREAD

**Issue by thany** [yeoman/generator-webapp#545]
First-time user here. Never used yeoman before. So I create a new project:

```
> yo webapp
```

And then at some point it asks me:

```
? Choose your style of DSL
```

What is DSL, apart from alright-speed internet? Ten years of experience, and I've never heard of this term in webdev context. Also what do the options TDD and BDD mean?

I know this makes this issue mostly a support question, so here's the actual issue: make it clear what things mean if there's the odd-chance that it might possibly be unclear.

**Comment by sindresorhus** [comment]
DSL => https://en.wikipedia.org/wiki/Domain-specific_language
TDD => https://en.wikipedia.org/wiki/Test-driven_development
BDD => https://en.wikipedia.org/wiki/Behavior-driven_development

## 

Definitely agree we should make that clearer.

**Comment by silvenon** [comment]
I bumped to a newer version of generator-mocha which includes a more verbose message:

```
Choose your style of test DSL for Mocha (bdd, tdd)
```

**Comment by Ryan-ED** [comment]
![image](https://user-images.githubusercontent.com/23261294/28867246-abd984ac-7775-11e7-9374-56316eded5df.png)
Still says the same thing for me. And I literally just installed it 10 mins ago. My first yo app and I'm new to webdev so this threw me off a little.

**Comment by thibmaek** [comment]
This is very bad practice

**Comment by ghost** [comment]
Wtf?..

**Comment by silvenon** [comment]
I thought I fixed that, but I see now that the message is the same (I only fixed the description instead of the actual question). We're in the process of upgrading the generator and this issue will definitely be resolved in the process.

**Comment by birozso** [comment]
that would be great. For a first time user it is hard to understand.

**Comment by ekntrtmz** [comment]
still is still an issue...

**Comment by silvenon** [comment]
Hey, sorry about this, I'm in the finishing stages of writing my thesis and then it's finally goodbye college. Afterwards I'll be able to fix urgent issues, including this one.

**Comment by 47ronin** [comment]
Anyone have a recommendation for a default response? Basically, which one of these cryptic acronyms is similar to what we have all unknowingly used in previous projects?

**Comment by silvenon** [comment]
@47ronin [BDD](https://mochajs.org/#bdd).

**Comment by MarkOSullivan94** [comment]
Still an issue - had to search what it is and the result lead me here 👋

**Comment by jozefizso** [comment]
This really caught me off guard. I just want to create a new project.

Without any context, this question is a showstopper even for a senior developer.

![image](https://user-images.githubusercontent.com/287778/60205374-4fcb3080-9851-11e9-8ed6-87a9a341cc0a.png)

**Comment by birozso** [comment]
> This really caught me off guard. I just want to create a new project.
> 
> Without any context, this question is a showstopper even for a senior developer.
> 
> ![image](https://user-images.githubusercontent.com/287778/60205374-4fcb3080-9851-11e9-8ed6-87a9a341cc0a.png)

sure , ---> Test Driven Development , would be more talkative

**Comment by silvenon** [comment]
@birozso try with the latest release, [v4.0.0-6](https://github.com/yeoman/generator-webapp/releases/tag/v4.0.0-6).

**Comment by TheBox193** [comment]
+1 this is confusing. Just say:

```
? Choose your style of Domain specific language (Use arrow keys)
❯ Behavior driven development 
  Test driven development 
```

At least you could google it. 😂
