### ISSUE TITLE
Compiling CSS and JS to different folders

### ISSUE THREAD

**Issue by jaysunwalter123** [yeoman/generator-webapp#546]
I'm using generator-webapp and trying to figure out how to compile my styles and scripts to a different folder outside of the dist folder on build, reason being I'm working directly within a drupal theme folder that requires those assets in 'styles' and 'scripts' folders.

I've noticed that the styles and scripts build tasks appear to be attached to the html task, and I'm having trouble separating them. Anyone know how this can be done?

Thanks

**Comment by neilhem** [comment]
If you want to just change location of styles & scripts on build, you can just change 'dist' references in `Gulpfile.js` to whatever you want

**Comment by jaysunwalter123** [comment]
Thanks, but in that case, how would I exclude the HTML being output into the root? I can get main.css and main.js to output to their own folders by creating separate functions for them, thereby excluding the html from being output, but the vendor.js appears to need to be compiled along with the html as it's created by the bower components listed within the html file.

What I'm trying now, but am not sure is something that gulp can do, is to leave the default build as is but add a function that copies the css and js files to where I need them after the build has completed.

Do you know if that's possible?

Thanks for the help.

**Comment by jaysunwalter123** [comment]
Nevermind. I've just realised that drupal has it's own built in compiler so no need to ever run a build.

I did figure out how to run a function that copies the files to my chosen folder after all the other functions have run though, so not a complete waste of time trying to figure it out.

Thanks for the help.
