### ISSUE TITLE
'gulp serve' not opening app in Chrome on Ubuntu

### ISSUE THREAD

**Issue by jeffreysbrother** [yeoman/generator-webapp#547]
When I run `gulp serve` with FireFox set as my default browser, my app opens up just as expected. However, with Chrome set as default, a new blank browser window is opened. There is no URL in the omnibox, but it has focus.

I get the same result when running `gulp serve:dist` in Chrome.

I have used generator-webapp in the past almost exclusively with Chrome, on Windows and Mac, with no issues.

Ubuntu 16.04 LTS (running a virtual instance)
Chrome version 51.0.2704.106 unknown (64-bit)
npm 3.10.3
node 6.3.0
Gulp (CLI version 1.2.1 ... local version 3.9.1)
yo 1.8.4

**Comment by neilhem** [comment]
Tested on notebook with Ubuntu 16.04 LTS Chrome 51.0.2704.106 (64-bit) after `gulp serve` it opens a new tab with `localhost:9000`

**Comment by silvenon** [comment]
This sounds like an obscure bug specific to your environment. We're using [BrowserSync](https://github.com/BrowserSync/browser-sync) as our server, you could try searching through issues there. Also, try with the [BrowserSync's CLI](https://browsersync.io/docs/command-line).
