### ISSUE TITLE
Gulp does not move scripts, images and styles to dist folder!

### ISSUE THREAD

**Issue by hamidhadi** [yeoman/generator-webapp#552]
After running the `gulp` command, the `dist` folder is just included with `fonts` folder, yeoman icons and robot file! The scripts and styles do not move to Dist folder!!!!

**Comment by hamidhadi** [comment]
I just add `.pipe(gulp.dest('dist/styles'))` for `styles` task and add `.pipe(gulp.dest('dist/scripts'))` for `scripts` task and solve my problem.
Why you don't have these lines of code on project??!!!!!

**Comment by neilhem** [comment]
Seems like you have deleted something from `gulpfile.js` or `index.html`, by default everything copies into dist folder on `gulp`

**Comment by silvenon** [comment]
If you provide valid steps for reproducing this bug (from fresh install), I'll reopen and we'll fix this. But it seems like you modified something, which makes it no longer work.

**Comment by koltejas** [comment]
This happens when following these steps: 
1. yo webapp [selected all 3 [sass, bs, modernizr]]
2. BDD or TDD
In the generated gulpfile only `html` task has `.pipe(gulp.dest('dist'));` 
styles, scripts, font only have ` .pipe(gulp.dest('.tmp/styles'))` etc
using generator-webapp 2.3.2

**Comment by silvenon** [comment]
@koltejas sorry, I didn't quite understand. Could you describe the expected vs. actual `dist` directory?

**Comment by neilhem** [comment]
@koltejas Yeah, right. All copy from `.tmp -> dist` are done in html task. So what is the result? When you run `gulp` task you do not have built styles, scripts in dist folder?

**Comment by Michael-Reich** [comment]
I also have this problem, the files are in .tmp but not in my dist folder.

Tried this:
`.pipe($.useref({searchPath: ['.tmp', 'app', '.', '.tmp/scripts', '.tmp/styles']}))`

but didn't work.

**Comment by SeedyROM** [comment]
### Found this problem earlier this evening.

**Here's what I did in desperation, it seems to work:**

Change:
```
...
gulp.task('html', ['styles', 'scripts'], () => {
  return gulp.src('app/*.html')
...
```
To:
```
...
gulp.task('html', ['styles', 'scripts'], () => {
  return gulp.src('app/**/*[.js, .html, .css]')
...
```
