### ISSUE TITLE
Gulp Build Error

### ISSUE THREAD

**Issue by MorizelHodges** [yeoman/generator-webapp#553]
I receive the error below when attempting to run the gulp build command. I've updated permissions on myapp directory, but no change.

events.js:160
throw er: // Unhandled 'error' event
ERROR: spawn c:\myapp\node_modules\optipng-bin\vendor\optipng.exe ENOENT
... 

additional info
Windows Server 2008
npm version 3.9.5
gulp version: 3.9.1; cli version 1.2.1

**Comment by neilhem** [comment]
Hi, can you check your node dependencies are up-to-date via `npm outdated`?

**Comment by MorizelHodges** [comment]
Thanks @neilhem,  I see that my gulp-node-inspector is missing which I am working to correct at the moment. Hopefully that will correct the build issue.

**Comment by neilhem** [comment]
@MorizelHodges hope you have found out what caused the error, feel free to reopen if you still have the error
