### ISSUE TITLE
Intro question: "which more would you like?"

### ISSUE THREAD

**Issue by danhawkes** [yeoman/generator-webapp#554]
(when offering sass/bootstrap/modernizr as additional features)

This sentence isn't quite right - it sounds unwieldy and implies that these features might be offered instead of the defaults, rather than in addition to. 

Suggest changing it to something like: "Select additional features:", or "Which optional features would you like to include?"

**Comment by silvenon** [comment]
How about "Which _additional_ features would you like to include?"

**Comment by danhawkes** [comment]
Yeah, that's better.
