### ISSUE TITLE
Handlebars compiled to .tmp but not dist

### ISSUE THREAD

**Issue by seb-thomas** [yeoman/generator-webapp#556]
Hi guys, thanks for your great work here in support, been reading quite a bit but now have a question of my own! 

I'm using Handlebars with this Yo as per [this recipe](https://github.com/yeoman/generator-webapp/blob/master/docs/recipes/handlebars.md), and it works great with `gulp serve`. 

I can create a .hbs file, reference it in the html and append it to the DOM; but when I use `gulp` to create the dist, the gulpfile described in the recipe doesn't do anything involving dist and therefore I'm rightly getting `Failed to load resource: http://localhost:9000/templates/index.js 404`.  

Am I fundamentally misunderstanding how Handlebars is used here? My understanding is you can either compile your hbs as a js function and inject the strings on the namespaced object into your page, or you can compile the Handlebars and render it in your html, baked in. The recipe seems to be following the former concept, but I can't see anyway it would work in production (dist) without also writing to `dist`. Unless I'm missing something. Happy to contribute a change, just not sure I'm getting it.

Apologies if this has been covered before, I searched quite a bit and the only thing I found was [this mention](https://github.com/yeoman/generator-webapp/pull/201) of Nunjucks templates to be compiled to `.tmp` instead of `app`. 

FYI, my setup:

`app/templates/index.hbs`

```
<div class="entry">
    <h1>{{title}}</h1>
    <div class="body">
        {{body}}
    </div>
</div>
```

`app/index.html`

```
    <script src="templates/index.js"></script>
    <script>
        var context = {title: "My New Post", body: "This is my first post!"};
        var html = MyApp.templates.index(context);
        /*append to body stuff here*/
    </script>
```

**Comment by silvenon** [comment]
You're right, the build step is not taken care of. Yes, the recipe is following the former approach, where templates are compiled into JavaScript. If you'd like to complete the recipe with the build step, it would be greatly appreciated 👍 Let me know if you need help.

**Comment by eBaeza** [comment]
Where exactly I need to add the path "templates/*.js" to export the files to "dist" ?

**Comment by eBaeza** [comment]
I did it! I just add `<!--build:js templates/index.js-->(rendered templates)<!-- endbuild -->` to uglify and export to "dist"

**Comment by amobrem** [comment]
I cant seem to get the recipe to work. Any eta on this? Thanks in advance

**Comment by silvenon** [comment]
@amobrem does #565 help?

**Comment by amobrem** [comment]
Yes, I just grabbed the template dir and followed the directions, it worked after I update the handlebars version in gulp-handlebars to 4.0.5.

**Comment by amobrem** [comment]
I cant seem to get the partials to load. Is there a step missing?

**Comment by silvenon** [comment]
@amobrem not sure, I'll have to try out the recipe myself, next week.

**Comment by AurelioDeRosa** [comment]
Completing the guide with info to use Handlebars to create static HTML pages would be really helpful.

**Comment by silvenon** [comment]
@AurelioDeRosa that would be useful. In the meantime, you could try [gulp-compile-handlebars](https://www.npmjs.com/package/gulp-compile-handlebars) or [gulp-handlebars-html](https://www.npmjs.com/package/gulp-handlebars-html).

**Comment by silvenon** [comment]
#565 is merged and corrected in master. Let me know if there are any problems with it.
