### ISSUE TITLE
SyntaxError: Unexpected token: name on import function

### ISSUE THREAD

**Issue by hamidhadi** [yeoman/generator-webapp#558]
After I logging uglify task errors, I got this line: 
`/app/scripts/main.js: SyntaxError: Unexpected token: name (initHome)',`

Here is my `main.js`: 

``` javascript
import initHome from './controllers/home';
......
```

and in my `home.js`

``` javascript
    export default function(){
    ......}
```

**Comment by neilhem** [comment]
Uglify task cannot run because of js syntax error

**Comment by hamidhadi** [comment]
I had some problem in my gulpfile. 
I close this issue, because I solved my problem.
