### ISSUE TITLE
Using the compass with new version

### ISSUE THREAD

**Issue by bdadev** [yeoman/generator-webapp#560]
Hello.
I have old projects developed with compass. It is a huge structure functions and mixins using the compass libraries.
I'm trying to bring new projects to gulp more I have difficulty using the compass. I tried setting using gulp-compass more without success.

Some light for me? I researched extensively and found something solid able to meet my needs.

Thank you!

I'm sorry the English, translated by google translate!

```
Error in plugin 'sass'
Message:
    app\styles\main.scss
Error: File to import not found or unreadable: compass
```

**Comment by neilhem** [comment]
Hi, have you tried to install this [plugin](https://www.npmjs.com/package/gulp-compass)?

**Comment by bdadev** [comment]
Hi @neilhem yes i tried.

**Comment by silvenon** [comment]
We should write a Compass recipe, I'm surprised that there isn't one already.
