### ISSUE TITLE
Unexpected token error using require

### ISSUE THREAD

**Issue by vijaywm** [yeoman/generator-webapp#570]
I am trying to use this template for an angular js project using the browserify recipe from [here](https://github.com/yeoman/generator-webapp/blob/master/docs/recipes/browserify.md)  

I have modified the main.js file as below

```
const component = {
    template : require('./app.html')
 }

const module = angular.module('app', [])
    .component('app', component)
```

The require line brings up an error 

> events.js:141
>       throw er; // Unhandled 'error' event
>       ^
>  SyntaxError: Unexpected token

How do I use require in my modules?

**Comment by silvenon** [comment]
The recipe configures browserify to only understand JS modules. Have you tried [searching for a transform](https://github.com/substack/node-browserify/wiki/list-of-transforms) suitable for this job? I'm not sure how Angular wants those HTML modules processed.

**Comment by silvenon** [comment]
We just teach you how to set it up, you customize it. 😉
