### ISSUE TITLE
Dirty app/scripts folder as a result of js.map files (solved)

### ISSUE THREAD

**Issue by jolugama** [yeoman/generator-webapp#571]
It doesn't make sense to keep the .map in the app/scripts folder. This makes dirty sources.

The js.map files should be saved in the tmp folder.
This is the wrong line:
.pipe ($. sourcemaps.write ('.'))
And this is the solution:
.pipe ($. sourcemaps.write ('../ scripts'))

Thus, it is saved in tmp/scripts and not in app/scripts.
Chrome does not yet work but I've checked from firefox adding a file js coding something es6

It works!

**Comment by silvenon** [comment]
On my machine `.map.js` file ends up in `.tmp/scripts` as expected. 😕 Also, I don't understand why would `'.'` write the map to `app/scripts`, but `'../scripts'` would write it to `.tmp/scripts`…?

**Comment by silvenon** [comment]
Have you tried updating `gulp-sourcemaps` to v2? Our version is a bit outdated…

**Comment by neilhem** [comment]
With version gulp-sourcemaps v2.2 sourcemap file is generated in .tmp folder
