### ISSUE TITLE
Babel pre-compile test specs

### ISSUE THREAD

**Issue by weltonrodrigo** [yeoman/generator-webapp#574]
I need to run my tests on some weird environments like IE10.

Js files hosted on `app/scripts` runs fine because babel takes care of them, but if I use some es2015 syntax on my spec files, like spread operators, tests don't even run on IE10.

Is it even possible to run mocha and chai tests with Babel compiled files? If true, would it be a good idea to pass spec files through Babel first?

Thanks for this great project!

**Comment by neilhem** [comment]
Hi, it's possible
1. Change gulpfile.js to compile spec files with Babel
2. Put them into `.tmp/scripts/spec` for example
3. Make server look into this folder
4. Then run `gulp serve:test`

**Comment by silvenon** [comment]
@weltonrodrigo I hope you managed to solve this problem using @neilhem's suggestion. This use case is too uncommon for us to add it to the generator. I was thinking of eventually revamping the test generators, but that's not related to this one.

Let us know if we can help further!
