### ISSUE TITLE
not generating in the current directory

### ISSUE THREAD

**Issue by SakoMe** [yeoman/generator-webapp#578]
launch terminal:
cd desktop
mkdir test
cd test
yo webapp
it runs but the scaffolding is created on my desktop and not in the test folder...

**Comment by SakoMe** [comment]
Found the bug... I had to show the hidden files on the desktop. I had a .yo-rc.json on the desktop. Once deleted it's back to normal...

**Comment by silvenon** [comment]
@SakoMe glad that you solved your problem! In future, `yo doctor` can detect stuff like that. 😉
