### ISSUE TITLE
Inline-block spacing when running "serve" vs "serve:dist".

### ISSUE THREAD

**Issue by Trost123** [yeoman/generator-webapp#580]
I find this a bit inconvenient.
When I test my page via "serve", inline-block elements have a whitespace between them.
When I upload a dist to hosting, a page looks a bit different, because html is minified now, and inline-blocks have no whitespace between.

Maybe "serve" should remove whitespaces from html too for consistency?
How do you deal with this in your projects?

**Comment by neilhem** [comment]
Hi, use floats or flexbox, so you will not have such a problem.

**Comment by ksiabani** [comment]
Or [fight the space between](https://css-tricks.com/fighting-the-space-between-inline-block-elements/). Usually `font-size: 0` is enough.
