### ISSUE TITLE
TypeError: this.env.adapter.prompt(...).then is not a function

### ISSUE THREAD

**Issue by aheinhoang** [yeoman/generator-webapp#581]
I meet problem when running yo webapp:

$ node -v
v5.9.0
$ yo --version
1.7.0
$ yo doctor
Everything looks all right!
$ yo webapp

> ? Which additional features would you like to include? (Press <space> to select)  
> (_) Sass  
>  (_) Bootstrap  
>  (*) Modernizr                                                                                                 

events.js:154  
      throw er; // Unhandled 'error' event  
      ^                                                                                                        

TypeError: this.env.adapter.prompt(...).then is not a function  
    at Base.prompt (C:\Users\Hein Hoang\AppData\Roaming\npm\node_modules\generator-webapp\node_modules\yeoman-g
enerator\lib\base.js:240:45)  
    at module.exports.generators.Base.extend.prompting (C:\Users\Hein Hoang\AppData\Roaming\npm\node_modules\ge
nerator-webapp\app\index.js:88:17)  
    at Object.<anonymous> (C:\Users\Hein Hoang\AppData\Roaming\npm\node_modules\generator-webapp\node_modules\y
eoman-generator\lib\base.js:439:23)  
    at C:\Users\Hein Hoang\AppData\Roaming\npm\node_modules\generator-webapp\node_modules\yeoman-generator\node
_modules\run-async\index.js:26:25  
    at C:\Users\Hein Hoang\AppData\Roaming\npm\node_modules\generator-webapp\node_modules\yeoman-generator\node
_modules\run-async\index.js:25:19  
    at C:\Users\Hein Hoang\AppData\Roaming\npm\node_modules\generator-webapp\node_modules\yeoman-generator\lib\
base.js:440:9  
    at processImmediate [as _immediateCallback](timers.js:516:17)

**Comment by silvenon** [comment]
@heinhoang try updating yo (FountainJS/generator-fountain-webapp#56). If that didn't help, I'll reopen.
