### ISSUE TITLE
Deployed but nothing happened

### ISSUE THREAD

**Issue by rizqinizamil** [yeoman/generator-webapp#586]
Hi everyone,
I have question, when I deploy webapp to github page (master branch) it's nothing happen, but deploy task ran without error. It works fine when I deploy to gh-pages branch instead.
Anyone knows why?

Thanks.

**Comment by neilhem** [comment]
Hi, do you use this [recipe](https://github.com/yeoman/generator-webapp/blob/master/docs/recipes/gh-pages.md)?

**Comment by rizqinizamil** [comment]
Hi @neilhem,
Thank you for your response.
Yes, I used that recipe. But then I use `gulp-gh-pages`, it works now.

**Comment by silvenon** [comment]
I'll reopen this as a reminder to incorporate `gulp-gh-pages` if it indeed there is something wrong with the recipe.
