### ISSUE TITLE
Integrate recipes as features into the generator

### ISSUE THREAD

**Issue by silvenon** [yeoman/generator-webapp#592]
The idea of recipes was to avoid a lot of maintenance, but over time I got a feeling that they actually might require **more** maintenance, because:

- they can easily become out-of-date, since I can't regularly check every snippet of every recipe all the time
- we can't write tests for them
- if there's a problem with a recipe, I usually have to follow every step myself to check what isn't working well, if it was a feature I could just scaffold my project
- writing new recipes takes a _lot_ of time, I would argue that it takes longer than implementing them as a feature because we have to spend time writing a tutorial

I didn't have experience with this, so I'm not sure if this is a good idea. Do you guys have any thoughts?

@sindresorhus @kevva @eddiemonge @neilhem

**Comment by eddiemonge** [comment]
It would be better if recipes were community maintained

**Comment by silvenon** [comment]
@eddiemonge what do you mean?

**Comment by eddiemonge** [comment]
meaning we didnt have to do them. adding them as features to the generator means our maintenance level goes way up having to support all these different combinations

**Comment by neilhem** [comment]
Yeah, adding as a feature in generator significantly increases app logic. How about maintaining separate generators which have the same base, but support some functionality from recipe as difference?

**Comment by silvenon** [comment]
It still sucks to have outdated docs lying around. But yeah, I see how silly my idea was, especially because some recipes can't be fully integrated, like the CoffeeScript one which involves changing tests.

Thanks for the talk.
