### ISSUE TITLE
Error: 'TypeError: browserSync is not a function' when running 'gulp serve'

### ISSUE THREAD

**Issue by probablyabear** [yeoman/generator-webapp#594]
After a fresh install of this generator, I receive the following error after running gulp-serve:

```
/Users/Stephen/Sites/wunder/gulpfile.js:81
    browserSync({
    ^

TypeError: browserSync is not a function
    at runSequence (/Users/Stephen/Sites/wunder/gulpfile.js:81:5)
    at finish (/Users/Stephen/Sites/wunder/node_modules/run-sequence/index.js:60:5)
    at runNextSet (/Users/Stephen/Sites/wunder/node_modules/run-sequence/index.js:88:5)
    at Gulp.onTaskEnd (/Users/Stephen/Sites/wunder/node_modules/run-sequence/index.js:75:5)
    at emitOne (events.js:101:20)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (/Users/Stephen/Sites/wunder/node_modules/orchestrator/index.js:264:8)
    at /Users/Stephen/Sites/wunder/node_modules/orchestrator/index.js:275:23
    at finish (/Users/Stephen/Sites/wunder/node_modules/orchestrator/lib/runTask.js:21:8)
    at /Users/Stephen/Sites/wunder/node_modules/orchestrator/lib/runTask.js:52:4
```

Running the following:
Node 7
NPM 3.10.8
Gulp Local/CLI 3.9.1
Bower 1.8.0
macOS Sierra 10.12.1

**Edit**
After seeing @silvenon's [commit](https://github.com/yeoman/generator-webapp/commit/7534f5c58f8b4769cf5c6140cc84534b8b53313b#diff-2cf705703194a09fc142722b487ff82c), I tried removing the `.create()` method from the module dependencies in gulpfile.js, and that fixed `gulp serve`.

Unsure if this is specific to my environment, or related to browser-sync. Please let me know if I can provide any additional information to identify the issue.

**Edit 2**
After reading more of the browser-sync API documentation on [create](https://www.browsersync.io/docs/api#api-create), I noticed the `bs.init` method was missing from gulpfile.js.

This looks to be necessary to start the browser-sync server.

I updated the browserSync portion of gulpfile.js to what's below. This allows you to run `grunt serve` and `grunt serve:dist` with browser-sync's 2.0.0 `.create()` syntax.

```
// Previous gulp tasks
 
gulp.task('serve', () => {
  runSequence(['clean', 'wiredep'], ['styles', 'fonts'], () => {
    // Added init method on next line
    browserSync.init(({
          notify: false,
          port: 9000,
          server: {
            baseDir: ['.tmp', 'app'],
            routes: {
              '/bower_components': 'bower_components'
            }
          }
        }));

    gulp.watch([
      'app/*.html',
      'app/scripts/**/*.js',
      'app/images/**/*',
      '.tmp/fonts/**/*'
    ]).on('change', reload);

    gulp.watch('app/styles/**/*.scss', ['styles']);
    gulp.watch('app/fonts/**/*', ['fonts']);
    gulp.watch('bower.json', ['wiredep', 'fonts']);
  });
});

gulp.task('serve:dist', ['default'], () => {
  // Added init method on next line
  browserSync.init(({
      notify: false,
      port: 9000,
      server: {
        baseDir: ['dist']
      }
    }));
});
```

**Comment by stephenrust** [comment]
After seeing @silvenon's [commit](https://github.com/yeoman/generator-webapp/commit/7534f5c58f8b4769cf5c6140cc84534b8b53313b#diff-2cf705703194a09fc142722b487ff82c), I tried removing the `.create()` method from the module dependencies, and that fixed `gulp serve`.

Unsure if this is specific to my environment, or related to browser-sync. Please let me know if I can provide any additional information to identify the issue.

**Comment by stephenrust** [comment]
After reading more of the browser-sync API documentation on [create](https://www.browsersync.io/docs/api#api-create), I noticed the `bs.init` method was missing from gulpfile.js.

This looks to be necessary to start the browser-sync server.

I updated the browserSync portion of gulpfile.js to what's below. This allows you to run `grunt serve` and `grunt serve:dist` with browser-sync's 2.0.0 `.create()` syntax.

```
// Previous gulp tasks
 
gulp.task('serve', () => {
  runSequence(['clean', 'wiredep'], ['styles', 'fonts'], () => {
    // Added init method on next line
    browserSync.init(({
          notify: false,
          port: 9000,
          server: {
            baseDir: ['.tmp', 'app'],
            routes: {
              '/bower_components': 'bower_components'
            }
          }
        }));

    gulp.watch([
      'app/*.html',
      'app/scripts/**/*.js',
      'app/images/**/*',
      '.tmp/fonts/**/*'
    ]).on('change', reload);

    gulp.watch('app/styles/**/*.scss', ['styles']);
    gulp.watch('app/fonts/**/*', ['fonts']);
    gulp.watch('bower.json', ['wiredep', 'fonts']);
  });
});

gulp.task('serve:dist', ['default'], () => {
  // Added init method on next line
  browserSync.init(({
      notify: false,
      port: 9000,
      server: {
        baseDir: ['dist']
      }
    }));
});
```

**Comment by neilhem** [comment]
Fixed, will be released ASAP in the next patch version.

**Comment by probablyabear** [comment]
Awesome, thanks for the quick fix @neilhem.

**Comment by silvenon** [comment]
[v2.3.2](https://github.com/yeoman/generator-webapp/releases/tag/v2.3.2) released.

**Comment by didiraja** [comment]
Tried gulp-connect-php7 & browserSync and had the same problem, solved with the same solution
