### ISSUE TITLE
Font awesome fonts does't copy to font folder when building

### ISSUE THREAD

**Issue by iamchathu** [yeoman/generator-webapp#597]
Previously I had grunt based web app generator generated app. I have migrated it to new generator generatered webapp.

Add bower dependancies and did install.Then moved app folder content to new webapp.

But when i build the site font folder doesn't contain font awesome fonts

**Comment by stibay** [comment]
Add this to bower.json

```
  "overrides": {
    "bootstrap-sass": {
      "main": [
        "assets/stylesheets/_bootstrap.scss",
        "assets/fonts/bootstrap/*",
        "assets/javascripts/bootstrap.js"
      ]
    },
    "font-awesome": {
      "main": [
        "./scss/font-awesome.scss",
        "./fonts/*"
      ]
    }
  },
```

**Comment by silvenon** [comment]
@stibay thanks!

**Comment by mtompkins** [comment]
This issue continues to exist in the simplified CSS template version (i.e. no SASS)
