### ISSUE TITLE
can't update generator-webapp

### ISSUE THREAD

**Issue by aheinhoang** [yeoman/generator-webapp#602]
wins 8
`node -v`
v6.9.1
`npm -v`
3.10.9
`yo --version`
1.8.5

I try to update generator-webapp to latest version by `npm install -g generator-webapp`
but it pulls out

> npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
> C:\Users\Hein Hoang\AppData\Local\npm
> +-- generator-webapp@2.3.2
> `-- UNMET PEER DEPENDENCY yo@>=1.7.1
> npm WARN generator-webapp@2.3.2 requires a peer of yo@>=1.7.1 but none was installed.

**Comment by neilhem** [comment]
Hi, have you tried to scaffold project via `yo webapp`? What errors do you get when you run this command?

**Comment by aheinhoang** [comment]
it outputs WARNING

```
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents): npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.15: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: is-gif@1.0.0 (node_modules\is-gif):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Error: EPERM: operation not permitted, rename 'E:\_toolkit-static-web\bootstrap-scaffolding\bootstrap3\node_modules\.staging\is-gif-160bba7c\package.json.3823358805' -> 'E:\_toolkit-static-web\bootstrap-scaffolding\bootstrap3\node_modules\.staging\is-gif-160bba7c\package.json'
'bower' is not recognized as an internal or external command,
operable program or batch file.
```

**Comment by silvenon** [comment]
I think generator-webapp upgraded successfully, what does `npm ls -g generator-webapp` say?

This `bower` error looks like you don't have Bower installed globally. What does `bower --version` say?

**Comment by aheinhoang** [comment]
1. `npm ls -g generator-webapp`

```
C:\Users\Hein Hoang\AppData\Local\npm
`-- generator-webapp@2.3.2
```
1. 'bower --version'

```
'bower' is not recognized as an internal or external command,
operable program or batch file.
```

thanks, but why it pulls out above WARNINGS?

**Comment by silvenon** [comment]
To install Bower:

```
npm install --global bower
```

I'm not exactly sure about the warnings, though the last warning means you don't have permissions set properly there.

**Comment by silvenon** [comment]
The key question here is: does it work? 😉

**Comment by silvenon** [comment]
#606
