### ISSUE TITLE
generate a grunt file instead a gulp file

### ISSUE THREAD

**Issue by nouredine** [yeoman/generator-webapp#604]
When I use yeoman to generate the webapp, I obtain the project with a grunt file instead the expected gulp file.
Thank you in advance

**Comment by silvenon** [comment]
You're using an old version of generator-webapp. Please upgrade:

```
npm install --global generator-webapp
```

**Comment by nouredine** [comment]
Thanks for your answer,
removing the old version manually from my disc resolved me the Problem
