### ISSUE TITLE
Changing bootstrap theme

### ISSUE THREAD

**Issue by gsportelli** [yeoman/generator-webapp#609]
Hi, I'm just starting using yeoman to develop a simple web application.

I created a webapp using the tutorial, but I wan to change bootstrap theme, e.g., by choosing one of the [bootswatch](https://bootswatch.com/) themes.

How am I supposed to do that without corrupting any of the auto-generated stuff?

**Comment by gsportelli** [comment]
The less invasive way to achieve it was to download the **_variables.scss** file from bootswatch to the app/styles folder and to modify the initial part of **app/styles/main.scss** from

```
$icon-font-path: '../fonts/';

// bower:scss
@import "bower_components/bootstrap-sass/assets/stylesheets/_bootstrap.scss";
// endbower
```

to

```
$icon-font-path: '../fonts/';

// bower:scss
@import "_variables.scss";
@import "bower_components/bootstrap-sass/assets/stylesheets/_bootstrap.scss";
// endbower
```

**Comment by neilhem** [comment]
Hi, I use the same rule. Also you can import files without `_` & file extension, e.g. `_variables.scss` -> `variables`.

**Comment by silvenon** [comment]
@gsportelli you should import `variables.scss` **outside** of `bower:css` block comments, otherwise that `@import` statement will disappear as soon as wiredep is ran. Do this instead:

```scss
$icon-font-path: '../fonts/';

@import "variables.scss";
// bower:scss
@import "bower_components/bootstrap-sass/assets/stylesheets/_bootstrap.scss";
// endbower
```

Btw, do all these themes consist only of `_variable.scss`?

**Comment by gsportelli** [comment]
If I import only _variable.scss I see that the theme looks like what I wanted, but there is also a _bootswatch.scss file too, which should be included.

Out of curiosity, what is the software that parses the `// bower:scss` directive? Is it bower itself?

**Comment by silvenon** [comment]
@gsportelli no, it's [wiredep](https://github.com/taptapship/wiredep), we're calling it in [this task](https://github.com/yeoman/generator-webapp/blob/076f4666ecc47da86fa0d2289e9119b1f4149b7a/app/templates/gulpfile.js#L167-L182).

**Comment by silvenon** [comment]
Concerning the `_bootswatch.scss` file, you should probably import it _after_ the comment block.
