### ISSUE TITLE
Wiredep not working

### ISSUE THREAD

**Issue by Frondor** [yeoman/generator-webapp#612]
If I do `bower install --save vue`, my `index.html` is not getting the updates automatically. Even if I re-run `gulp serve` seems like neither `js` or `css` files are being inserted in the HTML.

I'm using last version of this generator.

Seems like this issue is still valid #506

**Comment by silvenon** [comment]
@Frondor unfortunately the [vue repo](https://github.com/vuejs/vue) doesn't seem to have a `bower.json` defined at all. Usually wiredep reads the `main` field of `bower.json` and injects those files. You could raise an issue there to create a `bower.json` with the correct `main` field.
