### ISSUE TITLE
Task Images

### ISSUE THREAD

**Issue by bdadev** [yeoman/generator-webapp#614]
I'm sorry but I'm having trouble with the images task.

Using the default settings nothing happens, so scouring some issues I found ways to make this work more unsuccessfully.

Code created by the generator is initially so

``` javascript
gulp.task('images', () => {
  return gulp.src('app/images/**/*')
    .pipe($.cache($.imagemin()))
    .pipe(gulp.dest('dist/images'));
});
```

My code update

``` javascript
gulp.task('images', () => {
  return gulp.src('app/images/**/*')
	.pipe($.imagemin({
			optimizationLevel: 3,
			progressive: true,
			interlaced: true,
		}))
	.pipe(gulp.dest('dist/images'))
	.pipe($.size());
});
```
Here the task return

![webapp-imagemin](https://cloud.githubusercontent.com/assets/3835895/21455350/c664e866-c906-11e6-9569-4736c9725c3c.jpg)

Windows 10
Node v6.3.1
Npm v4.0.5
YO v1.8.5

Thanks!

**Comment by silvenon** [comment]
> Using the default settings nothing happens

The expected behavior is that `dist/images` is populated with optimized copies of images in `app/images`. Run `gulp clean`, then run `gulp images`, does `dist/images` exist and does it contain images?

**Comment by mtompkins** [comment]
I believe part of this issue is that during development, images do not resolve as they aren't copied in to .tmp

**Comment by bdadev** [comment]
Yes there is.
But anyway, I changed the images and it worked, I do not know what to say ...

Sorry for the delay, I was on vacation. Thank you for your attention and I'm sorry for that.

**Comment by outaTiME** [comment]
Hi guys, 
gulp-cache 0.5 (released 12 days ago) breaks the image task execution without any output any ideas? 

(by the moment I just remove cache task execution)

thanks !!!

**Comment by silvenon** [comment]
Didn't verify, but I'll reopen to remember to check later. Thanks for reporting.
