### ISSUE TITLE
webapp showing too small in mobile when published to Ubuntu server

### ISSUE THREAD

**Issue by jocan3** [yeoman/generator-webapp#617]
So I created a web app using Yeoman webapp template with bootstrap. When I deploy it locally with 'gulp build' in my Windows PC and run it using 'gulp serve' everything looks good in mobile (using browser emulator and also publishing it with XAMP and viewing it from my iPhone). However, when I 'gulp build' and upload the 'dist' folder to my ubuntu server, the page looks good in desktop but in mobile everything looks very small. Bootstrap grid reorganizes panels as expected but font and Facebook comments plugin appear very small. Again, using Windows 10 as server everything looks nice in mobile and, as mentioned in many other posts, I am using the meta:

`<meta name="viewport" content="width=device-width, initial-scale=1">`

You can see the full index.html and full app [here ](https://github.com/jocan3/slash1/blob/master/app/index.html)and the published page here: http://jocan3.com/1.

The apache version on both Windows and Ubuntu machines is 2.4. 

Something I noticed is that the page published in Ubuntu somehow contains "framesets" in the code which I understand is a tag not supported in HTML5. Because of this we see multiple head/body tags... Now why does this frameset got inserted in there? Checked on apache/Windows10 and those framesets do not appear in the page source code.

Any ideas on what could be happening?

Thanks!

**Comment by jocan3** [comment]
**SOLUTION**: It ended up that problem was not related neither to code nor to Ubuntu/apache. I am using a domain purchased in GoDaddy and they have a feature for "masking forwarding" which means that the domain is automatically redirected to my IP address but this option inserts "framesets" into the code to keep the URL masked with the domain name. To solve the problem, you need to disable any kind of forwarding in GoDaddy (remove any redirect configuration you have) and instead add an A record as described [here](https://www.godaddy.com/help/add-an-a-record-19238).

**Comment by neilhem** [comment]
Hi, Happy New Year. Nice that you have solved your problem
