### ISSUE TITLE
Do we still need bower?

### ISSUE THREAD

**Issue by alexej-d** [yeoman/generator-webapp#618]
I am sincerely curious as to why this generator still uses bower. Reading [discussions like this](https://www.reddit.com/r/javascript/comments/5ls30m/is_bower_dead_should_we_start_using_other/) keep me wondering if npm or yarn isn't enough or even superior.
BTW, I am not trying to start a rant. Maybe bower is indispensable and I just don't know all the reasons which led to it being a dependency.

**Comment by neilhem** [comment]
Hi, using npm means we need tools like [Rollup](https://github.com/rollup/rollup) or [Browserify](https://github.com/substack/node-browserify) in our build process. Which requires a lot of changes, so this should be integrated when time comes.

**Comment by silvenon** [comment]
Personally I like npm + webpack (haven't tried Rollup yet) over bower + wiredep. On one hand adding a module bundler adds complexity, on the other wiredep was confusing to many users, and with a module bundler people can even require stuff like fonts and images. But a module bundler would probably limit this generator to only single page applications.

I would love to hear opinions about this.

**Comment by alexej-d** [comment]
I would also prefer npm + webpack over the current bower workflow but it may be too complex for this kind of generator. Also I like my useref blocks for static assets when coding static pages, not sure how a webpack equivalent would look like…

EDIT: [Would that not be a good start on a way to replace bower and use webpack](https://webpack.github.io/docs/usage-with-gulp.html)? I can see that that still implies several additional changes to different tasks and other files like package.json. But I believe the advantages would outweigh the difficulties of refactoring this generator.

**Comment by alexej-d** [comment]
Bower is now officially deprecated https://github.com/bower/bower/issues/2298

**Comment by silvenon** [comment]
Thanks for pushing this important issue @alexej-d. Unfortunately Yeoman still hasn't come up with a solution for this problem (see yeoman/yeoman#1521 and taptapship/wiredep#234). The most sensible solution is probably to add npm support to wiredep.

**Comment by capitola-dev** [comment]
Bootstrap 4 beta 2 [dropped bower support](http://getbootstrap.com/docs/4.0/migration/#beta-2-changes)

> Dropped Bower support as the package manager has been deprecated for alternatives (e.g., Yarn or npm). See bower/bower#2298 for details.

So it might be the time to let it die.

**Comment by silvenon** [comment]
Removed Bower in [v4.0.0-0](https://github.com/yeoman/generator-webapp/releases/tag/v4.0.0-0)!
