### ISSUE TITLE
Changing Sass files and reloading browser

### ISSUE THREAD

**Issue by stibay** [yeoman/generator-webapp#625]
Is there an issue when reloading sass files?
When I do a change in the main.scss file and save the file the gulp task kicks inn and after running the styles task the browser reloads but there is something wrong with the formatting. It doesn't look like the css have been applied because after a manual refresh in the browser it looks fine again and the style changes have been applied.

Noticing this message in the console: `Resource interpreted as Stylesheet but transferred with MIME type text/html: "http://localhost:9001/styles/main.css?rel=1486545106999".`

**Comment by silvenon** [comment]
Does this happen with a fresh install or did you change some things? Could you provide steps to reproduce this?

**Comment by stibay** [comment]
After trying to reproduce this I see that it's not happening on a fresh install.
I see the problem is because I am using html5 mode and to get this working with browser sync I have added the connect-modrewrite package and this breaks it.

package.json
`"connect-modrewrite": "^0.9.0",`

gulpfile.js
`const modRewrite = require('connect-modrewrite');`

then under gulp task serve
```
        ...
        baseDir: ['.tmp', 'app'],
        middleware: [
          modRewrite([
            '!\\.\\w+$ /index.html [L]'
          ])
        ],
        routes: {
        ...
```

Is there an easy fix for this?

**Comment by silvenon** [comment]
I'm not sure what you mean by "html5 mode" and I'm not familiar with connect-modrewrite, but assuming you're trying to build a single-page application, have you tried using [connect-history-api-fallback](https://github.com/bripkens/connect-history-api-fallback)?

**Comment by stibay** [comment]
Nice, that worked perfectly!

Html5 mode removes the # in the url

Enables it by setting `$locationProvider.html5Mode(true);` in the route config and adding `<base href="/" /> `to the index <head> tag
