### ISSUE TITLE
Bootstrap 4 overrides

### ISSUE THREAD

**Issue by illycz** [yeoman/generator-webapp#632]
Bootstrap v4 main field is same as overrides in webapp bower.json. 
Is there some reason for overrides same values?

Thanks

Bootstrap v4 main filed: https://github.com/twbs/bootstrap/blob/v4-dev/bower.json#L17

**Comment by silvenon** [comment]
I don't think there's a reason for that, thanks for noticing. You can send a PR removing [these lines](https://github.com/yeoman/generator-webapp/blob/master/app/index.js#L180-L187).

**Comment by illycz** [comment]
Fork -> changes -> PR to master?

**Comment by illycz** [comment]
Another reason is default bootstrap exclude: https://github.com/yeoman/generator-webapp/blob/master/app/templates/gulpfile.js#L186 so overrides does not make sense...

**Comment by illycz** [comment]
@silvenon https://github.com/yeoman/generator-webapp/pull/633

**Comment by silvenon** [comment]
Merged, thanks!
