### ISSUE TITLE
"Gulp Serve" is not recognized?

### ISSUE THREAD

**Issue by DanJ210** [yeoman/generator-webapp#637]
I am following the getting started completely and when it says to run the "$ gulp serve" command I get what's below. Any suggestions?

```
_gulp : The term 'gulp' is not recognized as the name of a cmdlet, function, script file, or
operable program. Check the spelling of the name, or if a path was included, verify that
the path is correct and try again.
At line:1 char:1
+ gulp serve
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (gulp:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException_
```

**Comment by silvenon** [comment]
Have you installed gulp-cli globally? `npm install --global gulp-cli`? This issue is definitely not about this generator, so I'm closing this issue, but will stick around to help with this problem. 😉

**Comment by DanJ210** [comment]
That was totally what I needed. I didn't do that to begin with because I thought that was a shortcut version of going through yeoman and installing the webapp manually. Thanks a lot for the help I appreciate it.

I am a newbie so still getting grips on things.

**Comment by silvenon** [comment]
Our documentation [instructs](https://github.com/yeoman/generator-webapp#getting-started) to install it globally, but perhaps it's easy to miss.

**Comment by DanJ210** [comment]
I would say that the instructions are well done and I didn't necessarily miss it... I only _thought_ I had already done that first step another way. It was a mistake on my part not on this end. I respect what has been done for us here so thanks for all the work to whom it applies!
