### ISSUE TITLE
How can i properly edit bootstrap-sass variables?

### ISSUE THREAD

**Issue by s3c0nDD** [yeoman/generator-webapp#645]
**I want for example change navbar defaut height from 50px to i.e. 75px;**

here are those [variables to see at boostrap repo](https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/bootstrap/_variables.scss#L365)

i tried adding: `$navbar-height: 75px;` in main scss file on bottom of it, but id didn't help at all.

**Comment by neilhem** [comment]
@s3c0nDD create file for your variables, for example `_custom.scss` and copy/paste `_variables.scss` file content into that file. Import `custom.scss` before the import of bootstrap, so it will overwrite bootstrap variables.

**Comment by s3c0nDD** [comment]
i did just like you wrote:
1. i created _variables.scss with `$navbar-height: 75px;`
2. imported it in main.scss

In my main.scss i firstly import bootstrap then my variables/fonts/shared partials, then components partials. Is that a good way?

**Comment by neilhem** [comment]
Your variables should go first, then bootstrap imports
