### ISSUE TITLE
Lodash not found in dist folder

### ISSUE THREAD

**Issue by tuannguyenminh2086** [yeoman/generator-webapp#648]
Hello,

I installed the Lodash lib by: bower install lodash --save. 
After I run : gulp build. the lodash look like not include in plugins.js 

here is how I add lodash in **app** folder.
![screen shot 2017-03-22 at 10 26 36 am](https://cloud.githubusercontent.com/assets/1555621/24180894/1f4ee340-0eea-11e7-9e8f-2318df00ba5d.png)

Hope to see your feedback

**Comment by silvenon** [comment]
So you have lodash available in development, but not in production, or not at all? Maybe all you need to do is override your `bower.json` to include that file. Something like:

```json
{
  "dependencies": {
    "lodash": "~4.17.4"
  },
  "overrides": {
    "lodash": {
      "main": "dist/lodash.min.js"
    }
  }
}
```

**Comment by tuannguyenminh2086** [comment]
I have lodash available in developement. but not in production. when I run in production mode by the  command: gulp serve:dist .  The browser will say : **_ is not defined**

Thanks for your quick help. I will do like you show and come back later. Many thanks

**Comment by tuannguyenminh2086** [comment]
Thanks, It works.
