### ISSUE TITLE
Gulp watch task fires for files that wasn't changed

### ISSUE THREAD

**Issue by dima-f1** [yeoman/generator-webapp#656]
I'm have this issue now, with latest release of generator-webapp. Any file I change cause one reload for
every file which have same type as edited, no matter what kind of file it was - js, scss. Any help?
![image](https://cloud.githubusercontent.com/assets/5352626/25044784/26320dc8-2131-11e7-92eb-3287b0f32cc1.png)

I'm on Windows 7 64bit, Node 6.10.2, NPM 3.10.10

**Comment by Trost123** [comment]
You might want to look at gulp-cached or gulp-newer.
If I recall correctly, generator-webapp doesn't use any of above, therefore all files get processed each time.

**Comment by UlisesGascon** [comment]
I assume that this bug was fixed in #737. If not we can re-open it again 😃
