### ISSUE TITLE
Gulp build error on new clone

### ISSUE THREAD

**Issue by nickyweare** [yeoman/generator-webapp#658]
Hi,
Thanks for the great tool. Just having a problem with running gulp build..
I'm running node v6.10.2, ran npm install to see if it fixed app-scripts but with no joy.
File size is 115MB so it doesn't exceed node max memory limit.
Running gulp build off of two fresh clones on two os's gives the same results:-

`FATAL ERROR: invalid table size Allocation failed - JavaScript heap out of memory
 1: node::Abort() [gulp]
 2: 0x10d2fbc [gulp]
 3: v8::Utils::ReportApiFailure(char const*, char const*) [gulp]
 4: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [gulp]
 5: v8::internal::Dictionary<v8::internal::SeededNumberDictionary, v8::internal::SeededNumberDictionaryShape, unsigned int>::New(v8::internal::Isolate*, int, v8::internal::PretenureFlag) [gulp]
 6: 0xc392ea [gulp]
 7: 0xc39452 [gulp]
 8: v8::internal::JSObject::NormalizeElements(v8::internal::Handle<v8::internal::JSObject>) [gulp]
 9: v8::internal::Runtime_NormalizeElements(int, v8::internal::Object**, v8::internal::Isolate*) [gulp]
10: 0x3400082092a7
Aborted
`

**Comment by nickyweare** [comment]
After updating npm globally then locally, and running npm install again, the issue seems to have resolved itself.
`npm update -g`
`npm update` - locally
`npm install`

**Comment by akshayvinchurkar1** [comment]
after doing this I still get this error

```
<--- Last few GCs --->

   35594 ms: Scavenge 171.4 (311.6) -> 156.4 (311.6) MB, 5.4 / 0.0 ms [allocation failure].
   36088 ms: Mark-sweep 631.5 (786.6) -> 442.0 (533.1) MB, 14.7 / 0.0 ms (+ 89.5 ms in 3 steps since start of marking, biggest step 77.2 ms) [GC interrupt] [GC in old space requested].
   40136 ms: Mark-sweep 1154.5 (1213.6) -> 505.9 (879.3) MB, 46.4 / 0.0 ms (+ 185.1 ms in 43 steps since start of marking, biggest step 108.6 ms) [GC interrupt] [GC in old space requested].


<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 00000207837CF791 <JS Object>
    1: DoJoin(aka DoJoin) [native array.js:~129] [pc=000000F7929D377F] (this=0000020783704381 <undefined>,w=00000163E94FF361 <JS Array[17998088]>,x=17998088,N=00000207837043C1 <true>,J=0000013EE5904221 <String[8]\: ,\n      >,I=00000207837B7941 <JS Function ConvertToString (SharedFunctionInfo 00000207837526E1)>)
    2: Join(aka Join) [native array.js:180] [pc=000000F791BC6FF2] (this=000002078...

FATAL ERROR: invalid table size Allocation failed - JavaScript heap out of memory
```
