### ISSUE TITLE
Scss files getting deleted from Main.scss and not getting compiled

### ISSUE THREAD

**Issue by akash-d** [yeoman/generator-webapp#665]
Hi ,

I cloned the repo. I removed chai and mocha devdependencies. I added a line  in main.scss
**"@import "_common-styles.scss";"**

Everytime i compile i get the same error.
![err](https://cloud.githubusercontent.com/assets/16605014/26342669/985d8398-3fb6-11e7-8438-f966486e2502.jpg)

Sometimes it is removing all the scss files.

**Comment by neilhem** [comment]
Hi, when you import sass partial files do not include leading `_`.
Instead of `@import "_common-styles.scss"` use `@import "common-styles.scss"`. You can even remove file extension like this `@import "common-styles"`

**Comment by akash-d** [comment]
It works now.
Thanks 👍
