### ISSUE TITLE
Import, Export from ES6/7

### ISSUE THREAD

**Issue by futureinapps** [yeoman/generator-webapp#666]
Hi, how can i use import, exports from ES6 in ./scripts?

**Comment by neilhem** [comment]
Hi, you need to use tools like Browserify to use imports. We have [tutorial](https://github.com/yeoman/generator-webapp/blob/master/docs/recipes/browserify.md) how to integrate browserify.

**Comment by silvenon** [comment]
For that we would need a module bundler. We should probably integrate one soon, and it should probably be browserify, because it integrates well with Gulp. I will close this in favor of #618, because removing Bower will imply some kind of module bundling, which will imply ES6 imports. 😃
