### ISSUE TITLE
gulp-sass version in package.json is too old to install.

### ISSUE THREAD

**Issue by islishude** [yeoman/generator-webapp#669]
node v8.0
npm v5.0
generator-webapp v3.0.0
windows 10 x64

Run `gulp html` errors, tell me that need install gulp-sass

![image](https://cloud.githubusercontent.com/assets/24730006/26727667/36cf18fe-47da-11e7-896d-a0f51f1c285e.png)

But the gulp-sass version in package.json is too old to install.

![image](https://cloud.githubusercontent.com/assets/24730006/26727653/2dc7b9d2-47da-11e7-9f01-12589dde085b.png)

And when I run this `npm i -D gulp-sass@latest`,It's OK,and run `gulp html` is also.

So,I think that gulp-sass version in package.json is too old

same error I think #664

**Comment by isLishude** [comment]
#664
