### ISSUE TITLE
Migrate to yarn

### ISSUE THREAD

**Issue by ryzokuken** [yeoman/generator-webapp#673]
Bower is a pretty outdated choice for package management compared to yarn and even npm. Moreover, while installing, bower shows this warning message: 

```
warning bower@1.8.0: ..psst! While Bower is maintained, we recommend Yarn and Webpack for *new* front-end projects! Yarn's advantage is security and reliability, and Webpack's is support for both CommonJS and AMD projects. Currently there's no migration path but we hope you'll help us figure out one.
```

P.S. Just checked out, there's a notice on their website too.

**Comment by silvenon** [comment]
Hi @ryzokuken, thanks for raising this issue. 👍 The process is not as easy as switching package managers, we need a way to easily consume them. I'm closing this in favor of #618.
