### ISSUE TITLE
Recipe for adding custom JS and CSS files into project if they are not in bower or npm

### ISSUE THREAD

**Issue by akshayvinchurkar1** [yeoman/generator-webapp#677]
ok so this is not an issue this is my solution for this problem
1 ) make a new folder in your project we called this "lib".
2 ) next Add your js or CSS files in it simple.
3 ) and then update your gulp file this code

`gulp.task('scripts', () => {
  return gulp.src('{app/scripts,lib}/**/*.js')   // before it looks like this app/scripts/**/*.js
    .pipe($.plumber())
    .pipe($.if(dev, $.sourcemaps.init()))
    .pipe($.babel())
    .pipe($.if(dev, $.sourcemaps.write('.')))
    .pipe(gulp.dest('.tmp/scripts'))
    .pipe(reload({stream: true}));
});`

same for styles block I search the solution on internet but doesn't find a good help so I created a solution.
hope this will help some peoples who try to do the same thing: ) 

only one issue is gulp serve command doesn't recognize the js file outside the app folder if you make that work any help will be appreciated. right now temp solution I adding file twice in app/scripts and also in a lib folder :(

**Comment by neilhem** [comment]
Hi, why not just use some folder inside scripts, e.g. `app/scripts/libs`? If want to use plugin which is not in npm or bower just copy source file into this folder.

**Comment by akshayvinchurkar1** [comment]
@neilhem I didn't get you. did you mean manually copy the js file in disk folder after production release if not then how to configure gulp serve task in a development phase? help with code pls.

**Comment by neilhem** [comment]
Usually if I have a code of some plugin/library which in some way can't be installed with npm/bower I just put them into `scripts/libs` folder. Then just include in html like this:
```html
...
    <!-- build:js scripts/main.js -->
    <script src="scripts/main.js"></script>
    <script src="scripts/libs/old-plugin.js></script>
    <!-- endbuild -->
  </body>
</html>
```
Hope I helped you!

**Comment by akshayvinchurkar1** [comment]
@neilhem thanks this works
