### ISSUE TITLE
Page nesting not  building Bower Components

### ISSUE THREAD

**Issue by lukebrewerton** [yeoman/generator-webapp#678]
pages nested in a different folder structure i.e. root/tools/page.html has errors of /bower_components/bootstrap/js/dist/componentname.js 404 so this is not building correctly as it cannot see the /scripts/plugins.js reference

**Comment by silvenon** [comment]
We removed Bower (and wiredep) in [v4.0.0-0](https://github.com/yeoman/generator-webapp/releases/tag/v4.0.0-0).
