### ISSUE TITLE
Favicon does not update

### ISSUE THREAD

**Issue by akshayvinchurkar1** [yeoman/generator-webapp#679]
I don't know why but my favicon does not update on a site I change that with a new one with the same name but it shows the old one the default one. any suggestions.

**Comment by neilhem** [comment]
This is the problem of browsers which cache favicons, try to pass params of filehash, so when it will change you will get a new one.
```html
<link rel="icon" type="image/x-icon" href="/favicon.ico?hash=8799864">
```

**Comment by silvenon** [comment]
Yeah, this is an unfortunate browser annoyance. Any unique GET param will work, people usually go with `?v=1` then increase that number as they change favicons.
