### ISSUE TITLE
Use gulp-postcss with other postcss plugins to easily add a new plugins

### ISSUE THREAD

**Issue by neilhem** [yeoman/generator-webapp#682]
Instead of using [gulp-autoprefixer](https://github.com/sindresorhus/gulp-autoprefixer) + [gulp-cssnano](https://github.com/ben-eb/gulp-cssnano) I think better to use [gulp-postcss](https://github.com/postcss/gulp-postcss) and other postcss plugins directly. There are advantages like easy extensibility of default config with other postcss plugins.

**Comment by silvenon** [comment]
I totally agree, 👍 using them as separate plugins always seemed unnecessarily inflexible to me.
