### ISSUE TITLE
(BUG) Installing in wrong folder

### ISSUE THREAD

**Issue by dertuerke** [yeoman/generator-webapp#686]
Hi, if i starte a new Project, they install it always on my Desktop not in the folder where i am.

I am here
 ~/Desktop/lala >> yo webapp

but the project installed on 
 ~/Desktop

Node: v8.2.1
OS: macOS Sierra
npm: 5.3.0 
yarn: 0.27.5

**Comment by neilhem** [comment]
Hi, looks like you have `.yo-rc.json` in `Desktop` folder, try to remove this file.

**Comment by dertuerke** [comment]
Thx for the Help. Can Closed
