### ISSUE TITLE
Fonts not moving on build

### ISSUE THREAD

**Issue by jamilalisgandarov** [yeoman/generator-webapp#692]
Hi, It was solved before but it's not moving fonts from 'fonts' folder again on 'gulp build'.

**Comment by neilhem** [comment]
Hello, have you modified gulpfile.js?

**Comment by ivoba** [comment]
Fonts are moving to '.tmp' on build since build is dev mode.
Are you looking for them in 'dist'?
Then use default, default is not dev mode.

See: https://github.com/yeoman/generator-webapp/blob/master/app/templates/gulpfile.js#L95

**Comment by M-Fasciano** [comment]
I solved this removing **gulp.dest('.tmp/fonts')**.

My code looks like this now `.pipe($.if(dev, gulp.dest('dist/fonts')));`

**Comment by UlisesGascon** [comment]
I assume that this bug was fixed in #737. If not we can re-open it again 😃
