### ISSUE TITLE
add uikit framework

### ISSUE THREAD

**Issue by NoLiveKMS** [yeoman/generator-webapp#696]
Hello everyone!
This is generator very good, maybe someone can add in this generator uikit framework.

**Comment by neilhem** [comment]
Hi, recipe will be nice addition. PR would be great!

**Comment by UlisesGascon** [comment]
@NoLiveKMS do you want to help us to update the Docs and cover this case? 🙏

**Comment by silvenon** [comment]
As far as recipes are concerned, we only accept PRs. 🙂
