### ISSUE TITLE
Are there any plans to update the webapp generator to NOT use Bower?

### ISSUE THREAD

**Issue by gingell** [yeoman/generator-webapp#698]
I am trying to update an existing webapp project to use Bootstrap v4.0.0-beta.2 and it won't install with Bower.

Are there any plans to update the webapp generator to NOT use Bower?

Failing that, is there a documented workaround that will keep webapp projects prior to Bootstrap v4.0.0-beta.2, running beta.2 and beyond?

Thanks

gingell

**Comment by neilhem** [comment]
Hi, we are planning to update this generator to use npm instead of bower. As a temporary solution I recommend you editing Gulpfile.js to use `node_modules` on gulp tasks. For example `gulp serve`
```js
gulp.task('serve', () => {
  runSequence(['clean', 'wiredep'], ['styles', 'scripts', 'fonts'], () => {
    browserSync.init({
      notify: false,
      port: 9000,
      server: {
        baseDir: ['.tmp', 'app'],
        routes: {
          '/bower_components': 'bower_components',
          '/node_modules': 'node_modules' // Add this line
        }
      }
    });
```
then add references to js file/files in index.html

**Comment by gingell** [comment]
thank you!
