### ISSUE TITLE
[RFC] Switch to webpack?

### ISSUE THREAD

**Issue by silvenon** [yeoman/generator-webapp#708]
There are a couple of major issues with this generator:

- Bower has been deprecated, which disables us from using wiredep, so we'll have to get more creative if we want to include modules like Modernizer and _especially_ Bootstrap (because of CSS)
- many people report fatal errors which I often can't reproduce, and it makes me sad that people have errors
- `gulpfile.js` is hard to read, I haven't used Gulp in a while and it's hard for me to follow what's going to because lots of it is jumping through hoops

Solving these problems with the current toolset is very hard.

I have been working with [webpack](https://webpack.js.org/) for a long time now and, while I'm aware that it may be intimidating for beginners, it's much easier to pick up now that module bundlers have become very popular. I believe that we can reduce the codebase and make the toolset easier to use if we replace Gulp with webpack. I'm interested in making this generator simpler, so if that doesn't turn out to be the case with my proposal, I would not go down that route.

This would be a major change because Gulp has been the fundamental tool of this generator (before that was Grunt), so I'm asking for your opinions if you folks would be open for that.

👍 or 👎 ?

**Comment by grommas** [comment]
👍

**Comment by CesarDenis** [comment]
@silvenon you can count on me, if you want, to make this new version.

**Comment by silvenon** [comment]
Great! I think we've received enough 👍s considering that this generator probably doesn't have many active users.

- I'd definitely like to use Webpack v4 because of its awesome defaults.
- I'd also like to add support for Jest because of its popularity, not sure if we should do compose it as a separate generator or directly as a part of this one.
- We should use `babel-preset-env` instead of `babel-preset-es2015`
- We can finally add proper cachebusting because webpack is up to the task, unlike Gulp.

These changes are the first that come to mind, there will probably be many more. I'm open to ideas.

**Comment by CesarDenis** [comment]
To start is perfect. When do we start? 😄

**Comment by silvenon** [comment]
Hm, we're also way behind on the version of yeoman-generator, a full major version. Since I'm very much out of the loop because I haven't actively maintained generator-webapp a long time, maybe you'll have a better idea than me.

Maybe we could start by updating yeoman-generator?

**Comment by CesarDenis** [comment]
Maybe before that remove the bower and leave the generator running without error, to lessen the frustration of the people who are starting.

Then update the yeoman-generator and start migrating to the webpack.

What do you think?

**Comment by silvenon** [comment]
I believe the generator is running without error, I tried it recently. Also, how would we remove Bower while keeping Bootstrap integrated? I feel like this removing Bower should be part of the webpack change.

**Comment by CesarDenis** [comment]
Last time I used the generator (so I created a private repo with a boilerplate without bower and generator) was giving an error with bootstrap that had removed support for bower.

I tested it now and saw that it is ok, better to update the yeoman-generator.

**Comment by silvenon** [comment]
Great! Not sure how complicated that task is, especially because we're composing other generators too, which might have to be updated as well. If you're interested, you can explore that, otherwise I will.

**Comment by CesarDenis** [comment]
Okay, I'll venture the upgrade. 😄

**Comment by CesarDenis** [comment]
@silvenon a question, can I use the generator-generator model to bring the new file structure?

**Comment by StfBauer** [comment]
I use this generator-webapp mostly as a boilerplate for quick development where I don't need to use webpack at all.

Wouldn't it make more sense to have webpack as a separate option?

I actually don't use bower anymore, despite wiredep, there is no real advantage on using bower anymore so I already switch to native npm.

**Comment by silvenon** [comment]
@CesarDenis sure, just try to make commits as gradual as possible (i.e. avoid big commits with multiple purposes). Thanks! ❤️ 

@StfBauer gulp/webpack would be the integral parts of the generator, I feel like it would be difficult to maintain both options (I might be wrong, though).

It would be very helpful in making these decisions if you could provide some example(s) of how you use this generator, and how you switched from Bower to npm while still keeping gulp?

**Comment by StfBauer** [comment]
Pretty easy thou. Created a sample project for you. You will find this on my GitHub.
https://github.com/StfBauer/webappgulp

To embed bootstrap for example I installed the npm package:

```sh
npm install bootstrap-sass --save-dev
```
Instead of using the bower component at all I referenced the node_modules folder directly in CSS.

```sass
$icon-font-path: '../fonts/';
// bower:scss
@import "bower_components/bootstrap-sass/assets/stylesheets/_bootstrap.scss";
// endbower
```
The code then looks like this:

```scss
$icon-font-path: '../fonts/';
@import "node_modules/bootstrap-sass/assets/stylesheets/_bootstrap";
```

In addition, I disabled wiredep because this was just exclusive to bower components. So this wiredep doesn't work anymore and the few dependencies I really have I can even add manually. The same works with jQuery, Modernizer, ... you name it.
Not that convenient anymore but is a valid approach. In addition, yarn has support for what bower recently did.

When I really want to use webpack. I use a generator for webpack, that actually already exist out there. I don't see any reason why to build up another web app webpack generator when there are dozens of them are already out there. 
When I like to use webpack with ReactJS I use that generator.
When I like to use webpack with AngularJS I use that generator.

Search for a [generator using web pack](http://yeoman.io/generators/) and you will find of dozens of already configured webpack generators.

**Comment by silvenon** [comment]
I'm aware that many generators use webpack, I just want to make this generator stable and manageable.

Hm, I guess linking to `node_modules` could work, would useref still concatenate those files?

What do you think about this, @CesarDenis? In this case we would pretty much only have to update to newest Yeoman generator.

**Comment by StfBauer** [comment]
Yes - `useref` will exactly use all the scripts defined in the blocks and merge them. 
This is independent of any bower, yarn or npm packaging.

Simply all files in a blog will be merged together.

**Comment by CesarDenis** [comment]
@silvenon believes that webpack is easier to maintain than gulp, besides it brings some advantages in version 4. Particularly webpack would be better than gulp.

I'm trying to imagine how hard it would be to make a generator with both of them.

**Comment by silvenon** [comment]
> I'm trying to imagine how hard it would be to make a generator with both of them.

I agree, that is not an option. Either all gulp or all webpack. I'll give it some more thought.

**Comment by CesarDenis** [comment]
For me all webpack.

**Comment by silvenon** [comment]
Yeah, I like webpack + npm scripts workflow, I often find gulp awkward. Plus we don't have cache-busting because it was very hard to do with gulp, this is one of the many reasons I wanted to switch to webpack.

Anyway, we'll continue with updating to new yeoman-generator first.

**Comment by rbudiharso** [comment]
👍 any update on this?

**Comment by silvenon** [comment]
I think we won’t have to move to webpack in order to get rid of Bower and resolve some burning issues, so that’s one migration less. Thay’s all I can say for now.

**Comment by rajo-vilo** [comment]
@silvenon , what generator do you propose to migrate ?
i found this one : https://github.com/Sanchez3/generator-h5package based on webpack but am not realy sure if it meets the needs of developers

**Comment by silvenon** [comment]
Since creating this RFC I decided to just remove Bower for now. I'll see if we're going to implement a module bundler down the road and which one, but for now we just want to avoid Bower because it's deprecated.

If that doesn't answer your question, please clarify what you meant.

**Comment by rajo-vilo** [comment]
Yes, it's clear.
I was just thinking about a repository (like webapp) ready-to-install and configured which is not deprecating and which contains all the tools that a frontend developer needs to start his project.
The goal being to avoid wasting time to configure webpack.

**Comment by silvenon** [comment]
We're not planning to compose another generator, that would be too big and stressful, because then we depend too much on their output. Our Jasmine and Mocha containers are within our control. And, like I said in one of my previous comments, we probably won't be adding webpack. It was just an idea, but it would introduce too much complexity for people using this project.

**Comment by silvenon** [comment]
I'm closing this because I believe the discussion ran its course. New insights still welcome.
