### ISSUE TITLE
Issues with Getting Started examples

### ISSUE THREAD

**Issue by raszkiewicz** [yeoman/generator-webapp#710]
I have followed steps from [Getting Started ](https://github.com/yeoman/generator-webapp/blob/master/docs/README.md) but it came up that 

`$ gulp serve:dist`

is not working due to missing mocha.js file

> mocha.js Failed to load resource: the server responded with a status of 404 (Not Found)

from test example index.html 

`<script src="../bower_components/mocha/mocha.js"></script>`

Also if you want to run demo application it throws an error

`Uncaught ReferenceError: $ is not defined`

Any tips on that?

Thanks

**Comment by silvenon** [comment]
We releassed [v4.0.0-0](https://github.com/yeoman/generator-webapp/releases/tag/v4.0.0-0) which removes Bower, now you should link manually from `node_modules`. Let me know if that works and reopen the issue if it doesn't.
