### ISSUE TITLE
To Do App example fails when running 'npm run serve'

### ISSUE THREAD

**Issue by olliebaum** [yeoman/generator-webapp#711]
I was following the To Do app example on http://yeoman.io/codelab/ and there's an error in some of the code that prevents the website from being served.

The page displays the following error text:
![screen shot 2018-03-06 at 16 15 02](https://user-images.githubusercontent.com/4048746/37059004-21835c4c-2184-11e8-849a-fc0c55453279.png)

**FIX**: The problem can be fixed by navigating to ToDoTextInput.js and removing the quotes around 'edit' on line 40. _N.B. Don't assume the classname on line 41 should be unquoted as well. If you do, the site will throw an error again when run._

**Comment by UlisesGascon** [comment]
Hi @olliebaum! I think that you're looking for [generator-fountain-webapp](https://github.com/FountainJS/generator-fountain-webapp)... But It seems that [is not maintained](https://github.com/FountainJS/generator-fountain-webapp/issues/222) :-(
