### ISSUE TITLE
yo webapp stoped on the step "choose your style of DSL"

### ISSUE THREAD

**Issue by ericwang1902** [yeoman/generator-webapp#712]
![tim 20180307152107](https://user-images.githubusercontent.com/7867163/37078714-51489a9a-221b-11e8-8393-e26394762d5d.png)

I've read the early issue of this problem, but I can't find the solution.

**Comment by neilhem** [comment]
Hi, what is the problem? I can't identify a problem from the screenshot

**Comment by ericwang1902** [comment]
@neilhem hi, when I use yo webapp, at the step of  "choose your style of DSL"，I can't use arrow keys to choose BDD or TDD，can't go to next step.

**Comment by GaryStanton** [comment]
I had the same problem - though in my case I was using a mapped drive on an SMB share.
To resolve, I ended up remoting into the computer on which the drive was actually mounted and running from there - which worked fine. 
Not sure if that'll help you, but that was my situation.

**Comment by UlisesGascon** [comment]
I assume that this bug was fixed, If not we can re-open it again 😃
