### ISSUE TITLE
Can't build from node_modules

### ISSUE THREAD

**Issue by rizqinizamil** [yeoman/generator-webapp#713]
Sorry if this is outdated question because the hot issue is switching to Webpack 😄 
But I have a problem, and I think I need help. Why I can't build from node_modules folder?
This code is ok when i run `gulp serve` though.
```
<!-- build:js scripts/plugins.js -->
    <script src=/node_modules/eqcss/EQCSS.js></script>
    <script src=/node_modules/eqcss/EQCSS-polyfills.js></script>
<!-- endbuild -->
```

**Comment by rizqinizamil** [comment]
Sorry, that's totally my fault. Please ignore this :|

**Comment by mitchleung** [comment]
@rizqinizamil how do u resolve libraries from node_modules? I have the similar issue when I tried to move away from bower and all the way to npm. anything from node_modules will not show up in build:js

**Comment by rizqinizamil** [comment]
@mitchleung I put wrong address at first. Then changed it into this:
```
<!-- build:js scripts/plugins.js -->
    <script src="../node_modules/eqcss/EQCSS.js"></script>
    <script src="../node_modules/eqcss/EQCSS-polyfills.js"></script>
<!-- endbuild -->
```

**Comment by mitchleung** [comment]
I'm trying to switch all libraries to npm from bower.
But using neither 
    <script src="../node_modules/..."></script>
nor
    <script src="/node_modules/..."></script>
will not build plugins.js from build:js

**Comment by neilhem** [comment]
You should modify gulpfile.js to malke node_modules folder work properly
```js
server: {
  baseDir: ['.tmp', 'app'],
  routes: {
    '/node_modules': 'node_modules', <--- This line
    '/bower_components': 'bower_components',
  }
}
```

**Comment by mitchleung** [comment]
@neilhem Yes, I do have that line already to resolve the directory for gulp serve. But what I really want is to running "gulp build" to combine all the linked js lib into plugins.js but it seems all files from node_modules are omitted and I don't know what options to enable it.

**Comment by mitchleung** [comment]
Turns out it's one of the JS lib using ES6 and uglify doesn't like it and stopped outputting plugins.js
The solution is switching to gulp-uglify-es to replace gulp-uglify and it's works.
