### ISSUE TITLE
Adding multiple files to main.js

### ISSUE THREAD

**Issue by josephbona** [yeoman/generator-webapp#714]
`gulp build` concatenates and minifies 2 scripts between `<!-- build:js scripts/main.js -->` and `<!-- endbuild -->`. 

When I add a third file it does not get added to `main.js`

My HTML looks like this:
```
<!-- build:js scripts/main.js -->
<script src="scripts/main.js"></script>
<script src="scripts/data.js"></script>
<script src="scripts/venmo.js"></script>
<!-- endbuild -->
```

`main.js` and `data.js` get concatenated and minified into `/dist/scripts/main.js` but the code for `venmo.js` is not.

**Comment by UlisesGascon** [comment]
I assume that this bug was fixed in #737. If not we can re-open it again 😃
