### ISSUE TITLE
error jquery in bracktes

### ISSUE THREAD

**Issue by Sadi-222** [yeoman/generator-webapp#717]
error $ is not defined and bocument.
in jquery

**Comment by igorbelikov** [comment]
+1

After generating with (Bootstrap 4) jQuery, Popper and import from bootstrap.scss is not defined.

**Comment by brenohq** [comment]
same issue here

**Comment by kapasal** [comment]
nice，bro。好神奇的。

**Comment by igorbelikov** [comment]
Any news? It's critical issue.

**Comment by silvenon** [comment]
Could you see if the issue persists in [v4.0.0-0](https://github.com/yeoman/generator-webapp/releases/tag/v4.0.0-0)? Reopen the issue if it does.
