### ISSUE TITLE
Cannot change gulp-imagemin options

### ISSUE THREAD

**Issue by SergiArias** [yeoman/generator-webapp#719]
I tried all the documentation (gulp-imagemin) options with no satisfaction. I even put verbose with no luck. 

This is the code:

```
const pngquant = require('imagemin-pngquant');

 gulp.task('images', () => {
  return gulp.src('app/images/**/*')
    .pipe($.cache($.imagemin(
      [pngquant({quality: '50'})], {verbose: true}
    )))
    .pipe(gulp.dest('dist/images'));
});
```
I don't know if it's a bug or my own lack of expertise, so please, if it's not an issue tell me and I will post it where it belongs.

**Comment by UlisesGascon** [comment]
I assume that this bug was fixed in #737. If not we can re-open it again 😃
