### ISSUE TITLE
build:css styles/main.css 

### ISSUE THREAD

**Issue by Ecllyps** [yeoman/generator-webapp#720]
Hi everyone,

I have a question about css generation. I'va named in my app style folder my scss : style.scss. In my dist folder it is not generated. But when I change build:css styles/main.css into build:css styles/style.css that works fine. I don't understand why.

Thanks in adavnce.
Regards

**Comment by joshkpeterson** [comment]
I'm experiencing something similar. main.scss isn't showing up in dist (as main.css) at all, and neither are fonts. But they're both in the tmp directory, however! Looks like they're not getting piped in for some reason :/

**Comment by UlisesGascon** [comment]
I assume that this bug was fixed in #737. If not we can re-open it again 😃
