### ISSUE TITLE
Running gulp serve:test browser fails to load mocha library

### ISSUE THREAD

**Issue by bishi3000** [yeoman/generator-webapp#725]
Hi,

I created a new project, selected the BDD option for testing, however when I run gulp serve:test the test page faile to load the mocha library: 

http://localhost:9000/bower_components/mocha/mocha.js

It appears that the path /bower_components is not being served when running gulp serve:test.

I'm using the following versions:

Node: 9.0.0
NPM: 4.1.2
Yo: 2.0.4
gulp: 3.9.1

What am I doing wrong ?

**Comment by silvenon** [comment]
Could you test if the issue persists in [v4.0.0-0](https://github.com/yeoman/generator-webapp/releases/tag/v4.0.0-0)? Reopen the issue if it does.
