### ISSUE TITLE
Do we want to include by default Google Analytics?

### ISSUE THREAD

**Issue by UlisesGascon** [yeoman/generator-webapp#735]
Hi! 

Right now we embed Google Analytics into de generated HTML...

Do we want to add this behaviour as an option? Also it can be interesting to populate the Number from the user's input (`UA-XXXXX-X`).

What do you think?

**Comment by silvenon** [comment]
If we make it configurable, then we need to make it optional, and I don't think it's that big of a deal to just delete it if you don't want it.

Did I understand you correctly? Or did you mean that we could include Google Analytics in a different way?

**Comment by UlisesGascon** [comment]
Yes... my idea was to add it as optional like Modernizer ;-)

**Comment by silvenon** [comment]
I don't have strong opinions either way. If you want to submit a PR to make it optional, just make sure that it's on by default. Concerning specifying ID, I'm not sure if at that point people generally know it in advance, in my mind they usually create one afterwards. While I like to give people as much power as possible, I also don't want the number of questions to be overwhelming.

**Comment by UlisesGascon** [comment]
Awesome, I will generate a PR after I finish with #700 ;-)
