### ISSUE TITLE
Modernizr build limitations

### ISSUE THREAD

**Issue by UlisesGascon** [yeoman/generator-webapp#736]
I am working on the migration from Bower #700 and I am using npm to install modernizr. This will require an additional compilation, based on the [current documentation](https://www.npmjs.com/package/modernizr). 

**We have several options:**
- Not include Modernizr anymore
- Use another source like cdnjs or similar to get the valid build version
- Add an additional step in the generation to perform this build
- Install the dependency and let the final user to perform the build, using [Terminal option](https://www.npmjs.com/package/modernizr#to-generate-everything-in-config-alljson) or [method exposed](https://www.npmjs.com/package/modernizr#building)
- More options... ?

What do you think?

**Comment by silvenon** [comment]
This would probably be the "right" way to do it:

- add the `modernizr` dependency
- add a `modernizr.json` file containing a couple of example options from [config-all.json](https://github.com/Modernizr/Modernizr/blob/master/lib/config-all.json)
- somehow ensure that `gulp serve` and `gulp` trigger Modernizr to build using `modernizr.json` as configuration

Maybe this would be a good time to create two npm scripts, `start` and `build`, which would contain something like:

- `"start": "modernizr -c modernizr.json && gulp serve"`
- `"build": "modernizr -c modernizr.json && gulp"`

I'm just brainstorming here. I think including all of Modernizr would be kinda wasteful, but on the other hand allowing people to fine-tune the build might be a lot of work from our side… What do you think?

**Comment by UlisesGascon** [comment]
yeah! Let me explore this option. I think NPM Scripts is the best solution even for the future in order to keep the same way of working ^^. Thanks for your support!

**Comment by silvenon** [comment]
No problem, thanks for fixing all these problems!

I just found out about [gulp-modernizr](https://www.npmjs.com/package/gulp-modernizr), which seems like the best fit for this project.

**Comment by silvenon** [comment]
Actually, AFAICT, it doesn't detect CSS. I want people to be able to use selectors like `.no-touchevents .app {}`, but I don't think that gulp-modernizr is able to discover that and build appropriately.

**Comment by UlisesGascon** [comment]
Yeah! I have some issues with modernizer....
I had the idea to build it from node_modules but there are some problems with the routes, `./node_modules/modernizr/bin/modernizr -c modernizr.json -d app/scripts/modernizr.js` 

```
ulisesgascon:~/workspace/EXPERIMENTER (feature-700) $ ./node_modules/modernizr/bin/modernizr -c modernizr.json -d app/scripts/modernizr.js
{ Error: Error: ENOENT: no such file or directory, open '/home/ubuntu/workspace/EXPERIMENTER/node_modules/modernizr/lib/../feature-detects/audio/autoplay.js'
In module tree:
    modernizr-init

    at Object.openSync (fs.js:436:3)

    at /home/ubuntu/workspace/EXPERIMENTER/node_modules/requirejs/bin/r.js:30099:19
    at /home/ubuntu/workspace/EXPERIMENTER/node_modules/requirejs/bin/r.js:3081:39
    at /home/ubuntu/workspace/EXPERIMENTER/node_modules/requirejs/bin/r.js:3021:25
    at Function.prim.nextTick (/home/ubuntu/workspace/EXPERIMENTER/node_modules/requirejs/bin/r.js:29929:9)
    at Object.errback (/home/ubuntu/workspace/EXPERIMENTER/node_modules/requirejs/bin/r.js:3020:26)
    at Object.callback (/home/ubuntu/workspace/EXPERIMENTER/node_modules/requirejs/bin/r.js:3006:23)
    at Object.then (/home/ubuntu/workspace/EXPERIMENTER/node_modules/requirejs/bin/r.js:3060:23)
    at build (/home/ubuntu/workspace/EXPERIMENTER/node_modules/requirejs/bin/r.js:30056:12)
    at runBuild (/home/ubuntu/workspace/EXPERIMENTER/node_modules/requirejs/bin/r.js:32006:17)
    at Object.execCb (/home/ubuntu/workspace/EXPERIMENTER/node_modules/requirejs/bin/r.js:1941:33)
  originalError:
   { Error: ENOENT: no such file or directory, open '/home/ubuntu/workspace/EXPERIMENTER/node_modules/modernizr/lib/../feature-detects/audio/autoplay.js'
       at Object.openSync (fs.js:436:3)
       at Object.readFileSync (fs.js:341:35)
       at Object.readFile (/home/ubuntu/workspace/EXPERIMENTER/node_modules/requirejs/bin/r.js:3760:27)
       at Object.readFileAsync (/home/ubuntu/workspace/EXPERIMENTER/node_modules/requirejs/bin/r.js:3774:32)
       at Function.require._cacheReadAsync (/home/ubuntu/workspace/EXPERIMENTER/node_modules/requirejs/bin/r.js:29948:25)
       at /home/ubuntu/workspace/EXPERIMENTER/node_modules/requirejs/bin/r.js:29506:48
       at /home/ubuntu/workspace/EXPERIMENTER/node_modules/requirejs/bin/r.js:3063:37
       at /home/ubuntu/workspace/EXPERIMENTER/node_modules/requirejs/bin/r.js:3011:25
       at Function.prim.nextTick (/home/ubuntu/workspace/EXPERIMENTER/node_modules/requirejs/bin/r.js:29929:9)
       at Object.callback (/home/ubuntu/workspace/EXPERIMENTER/node_modules/requirejs/bin/r.js:3010:26)
     errno: -2,
     syscall: 'open',
     code: 'ENOENT',
     path:
      '/home/ubuntu/workspace/EXPERIMENTER/node_modules/modernizr/lib/../feature-detects/audio/autoplay.js',
     fileName:
      '/home/ubuntu/workspace/EXPERIMENTER/node_modules/modernizr/lib/../feature-detects/audio/autoplay.js',
     moduleTree: [ 'modernizr-init' ] } }
```

So... I created a new tasks in the script in order to compile from the library, and it is working fine!
```
javascript
const modernizr = require("modernizr");
const fs = require("fs");

modernizr.build({}, function (data) {
    fs.writeFileSync("./scripts/modernizr.js", data, "utf8")
});
```

 but... once I pass the json file as an argument... again we face the same path issue. So maybe the only solution right now is to implement Modernizr as a Global dependency

**Comment by UlisesGascon** [comment]
@silvenon I closed the issue by mistake, sorry 😓

**Comment by silvenon** [comment]
The error indicated what the problem was. I gave you a link for a configuration file on `master` branch of Modernizr, which is not released yet. The latest Modernizr version is 3.6.0, so if you check out feature detects on [that tag](https://github.com/Modernizr/Modernizr/tree/v3.6.0/feature-detects), you'll notice that `audio/autoplay` isn't released yet.

[This config file](https://github.com/Modernizr/Modernizr/blob/v3.6.0/lib/config-all.json) should be an accurate summary of currently released feature detects.

**Comment by UlisesGascon** [comment]
Awesome! You're right! Wrong config file. I will commit the change soon ;-)

**Comment by JelmarBosscher** [comment]
I ran your 700 feature branch and got in to a little trouble concerning this fix.
Perhaps you get the same issue now if you create a new webapp with modernizr selected.

```
H:\Personal\jelmar
λ npm start

> @ start H:\Personal\jelmar
> npm run build:modernizr && gulp serve


> @ build:modernizr H:\Personal\jelmar
> ./node_modules/modernizr/bin/modernizr -c modernizr.json -d app/scripts/modernizr.js

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build:modernizr: `./node_modules/modernizr/bin/modernizr -c modernizr.json -d app/scripts/modernizr.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ build:modernizr script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jelmar\AppData\Roaming\npm-cache\_logs\2018-11-08T05_07_42_978Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ start: `npm run build:modernizr && gulp serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Jelmar\AppData\Roaming\npm-cache\_logs\2018-11-08T05_07_43_008Z-debug.log

```

My thought would be that the following way of putting paths in the package.json scripts isn't going smoothly.
`    "build:modernizr": "./node_modules/modernizr/bin/modernizr -c modernizr.json -d app/scripts/modernizr.js",`

Other findings I'll be posting in #737

**Comment by UlisesGascon** [comment]
Thanks @JelmarBosscher for share this info and the context! I will check it asap ^^

**Comment by silvenon** [comment]
@UlisesGascon I'm about to post a review where I'll suggest a cleaner approach, so probably no need to investigate.
