### ISSUE TITLE
We need some refactor

### ISSUE THREAD

**Issue by UlisesGascon** [yeoman/generator-webapp#740]
I was using Code Climate and Codacy in order to understand better our source code. I will perform fast refactor in order to reduce the complexity and bad things, manly in `app/index.js`.

[This is my starting point](https://codeclimate.com/github/UlisesGascon/generator-webapp/issues?category=complexity&engine_name%5B%5D=structure&engine_name%5B%5D=duplication). I will send a PR asap 👍 

Maybe @silvenon... can grant access to this tool so we can add this checks in the PRs using Travis if you like this idea ^^

**Comment by silvenon** [comment]
Never used Code Climate before, I guess we could add it, I haven't seen it around much lately, though. I was thinking of introducing ESLint + Prettier or something.

**Comment by UlisesGascon** [comment]
Yeah! I can work on that too... 👍

**Comment by silvenon** [comment]
Fixed with #741.
