### ISSUE TITLE
Let's update the dependencies

### ISSUE THREAD

**Issue by UlisesGascon** [yeoman/generator-webapp#743]
Once we install all the dependencies in the generated project, I discovered `162 vulnerabilities (152 low, 6 moderate, 4 high)` using `npm audit`. 

This is a good first issue 👍 

**Who want to do the PR?**

**Comment by silvenon** [comment]
Released this change in [v4.0.0-0](https://github.com/yeoman/generator-webapp/releases/tag/v4.0.0-0)!
