### ISSUE TITLE
Typescript?

### ISSUE THREAD

**Issue by Ivanca** [yeoman/generator-webapp#745]
Now that TypeScript is used by Angular by default and by a lot of React developers it would be a good idea to make TypeScript an optional dependency/gulp-task

**Comment by silvenon** [comment]
Maybe, if someone wants to implement it as an option 😄

**Comment by UlisesGascon** [comment]
This issue has been open for a while, and it seems no volunteers are willing to work on it. Therefore, I will proceed to close it.
