### ISSUE TITLE
unusable generator: dist (or docs how to build dist) is buggy

### ISSUE THREAD

**Issue by azol** [yeoman/generator-webapp#752]
very minimal install leads to buggy result.

Steps to reproduce:
- scaffold
- build dist as per documentation
- check result

```
$ ls -al
total 0
drwxr-xr-x   2 az  staff   64 Feb 27 08:41 .
drwxr-xr-x  16 az  staff  512 Feb 27 08:41 ..
$ yo webapp
$ npm run build
$ tree dist/
dist/
├── apple-touch-icon.png
├── favicon.ico
├── fonts
├── images
├── index.html
├── robots.txt
├── scripts
│   ├── main.js
│   └── vendor.js
└── styles
    └── main.css
4 directories, 7 files
```
at least two problems here:

```
$ grep -l modernizr dist/index.html 
dist/index.html
$ grep -l node_modules dist/index.html 
dist/index.html
```
`<script src="scripts/vendor/modernizr.js"></script>` is what I get in the `dist/index.html`, but the file is missing

`<link rel="stylesheet" href="/node_modules/bootstrap/dist/css/bootstrap.min.css">` is what is get in the `dist/index.html,` which is obviously totally wrong.

opening `dist/index.html` in regular browser visually confirms that at least styling is missing.

Fixes:

- either fix docs for proper dist generation
- or fix the code to generate usable result

**Comment by silvenon** [comment]
These critical problems have hopefully been all fixed in [v4.0.0-3](https://github.com/yeoman/generator-webapp/releases/tag/v4.0.0-3)! Let me know if there are any more problems.
