### ISSUE TITLE
Unexpected token in package.json during install

### ISSUE THREAD

**Issue by richhauck** [yeoman/generator-webapp#755]
When including only Sass, then "Yes" to jQuery a stray comma is inserted before jQuery in the dependencies in package.json. I've found that including Bootstrap resolves this. 

<img width="987" alt="screenshot" src="https://user-images.githubusercontent.com/111928/55295141-d483eb00-53d7-11e9-85ec-2ee191dd5bf9.png">

**Comment by silvenon** [comment]
Thanks, fixed in latest release.
