### ISSUE TITLE
Why vendor.css takes the highest level

### ISSUE THREAD

**Issue by roeliman** [yeoman/generator-webapp#756]
I love this generator for its simplicity since booststrap 3 version.
but when update come, it's got me frustrated
i try to change background color of the body on main,css to black
but the browser still put white color on vendor.css as the highest level

please help me :(

why its happen?
![Capture](https://user-images.githubusercontent.com/11880924/55613367-bd1c7780-57b4-11e9-8aa0-6b3d455ea504.PNG)

**Comment by roeliman** [comment]
I love this generator for its simplicity since booststrap 3 version.
but when update come, it's got me frustrated
i try to change background color of the body on main,css to black
but the browser still put white color on vendor.css

why its happen?

**Comment by roeliman** [comment]
important property is not a a solution
how to make my main css to be the first level css
i already put main.css on the top on html structure, but it goes nothing

**Comment by silvenon** [comment]
Thanks for spotting this. Place `vendor.css` comment block before your `main.css` block and things should be fine. See f2624c4c79b4ab188267dccbd8d0965201428f59 for reference. (This has been fixed now in the latest prerelease.)

**Comment by roeliman** [comment]
wow it did worked
thanks @silvenon 

one more question, on previous version yeoman use bower, but now its not using bower anymore?
here's the thing, when i use bower, everytime i install new package, slick for example
bower will automatically add the dependecy slick file into html. like css and js file on bower.json

can we do that on this yeoman version?
coz, now i have to add manually the css and js file

**Comment by silvenon** [comment]
Yeah, I liked that too, but Bower has been deprecated so we had to remove it sooner or later. The tool that was automatically injecting dependencies in your HTML file was [wiredep](https://github.com/taptapship/wiredep), but it only works for Bower. For now you'll have to add dependencies manually because this is not possible to do automatically with npm, but we'll see if we can remedy this downgrade down the road with Parcel.

**Comment by roeliman** [comment]
that's a wise decision, i have to used to it
thanks for your great job

**Comment by silvenon** [comment]
Thanks!
