### ISSUE TITLE
jhipster 5.28.0 add Bootswatch Themes tell "You don't seem to have a generator with the name “jhipster:modules” installed" 

### ISSUE THREAD

**Issue by sinrt** [yeoman/generator-webapp#757]
cant add Bootswatch Themes  to my project from this "https://www.npmjs.com/package/generator-jhipster-bootswatch" guid. its tell "You don't seem to have a generator with the name “jhipster:modules” installed"

**Comment by silvenon** [comment]
You should run `yo jhipster-modules`, not `jhipster:modules` (so it should be "-" instead of ":"). And make sure you have it installed globally, `npm install --global generator-jhipster-modules`.
