### ISSUE TITLE
TDD test file is the same as BDD, so it doesn't work because Mocha expects a different interface

### ISSUE THREAD

**Issue by flaviodut** [yeoman/generator-webapp#768]
I'm trying to run test (TDD) in my application but it's returning "Uncaught ReferenceError: describe is not defined" in console. Even in a brand new scaffolding project this error shows up. Am I missing something? Thanks.

**Comment by UlisesGascon** [comment]
Thanks @flaviodut for reporting it. 

What SO are you using? and Nodejs version?

**Comment by flaviodut** [comment]
Hello @UlisesGascon: Windows 7 Pro with Node v10.15.1.

**Comment by silvenon** [comment]
I guess people use TDD so rarely that this bug hasn't surfaced until now. @flaviodut as you can see in Mocha's docs, [TDD](https://mochajs.org/#tdd) doesn't use `describe`, it uses `suite`, `test` etc. Those are the ones that are available globally.

We'll fix this in [generator-mocha](https://github.com/yeoman/generator-mocha).

**Comment by silvenon** [comment]
Ok, fix published in [4.0.0-7](https://github.com/yeoman/generator-webapp/releases/tag/v4.0.0-7).

To fix this locally you can either follow the TDD style from Mocha's docs manually, or:

- `rm -r test`
- `yarn global add generator-mocha`
- `yo mocha`
- select `TDD` as before

**Comment by flaviodut** [comment]
It works! Thanks.
