### ISSUE TITLE
lint infinite loop.

### ISSUE THREAD

**Issue by erniehs-zz** [yeoman/generator-webapp#769]
I have noticed when running the test server the lint goes into an infinite loop, perhaps it is related to this line below.  we watch for a script change, and then lint and the linting process changes the script etc.

https://github.com/yeoman/generator-webapp/blob/c62391b8a58237d9f52f2763497d2e6c049e5833/app/templates/gulpfile.js#L217

**Comment by UlisesGascon** [comment]
Hi @erniehs! Thanks for reporting it 😄 

Do you want to fix it? I can help you with the PR if you need help 👍

**Comment by erniehs-zz** [comment]
yes let me have a go at a simple PR for this. :)
