### ISSUE TITLE
run with ES%

### ISSUE THREAD

**Issue by xavierartot** [yeoman/generator-webapp#782]
Hi,
How can I setup to run ES5 and jQuery?
Thanks

**Comment by silvenon** [comment]
I'm not sure what you mean by "ES5", but for jQuery you can install it:

```sh
yarn add jquery
```

then in your `index.html` add jQuery between the `build:js scripts/vendor.js` comment directives:

```html
<!-- build:js scripts/vendor.js -->
<script type="text/javascript" src="/node_modules/jquery/dist/jquery.js"></script>
<!-- endbuild -->
```
