### ISSUE TITLE
Vulnerabilities - Node Latest version installed 16.13.1 LTS

### ISSUE THREAD

**Issue by michael-oxborrow** [yeoman/generator-webapp#785]
<img width="374" alt="Screenshot 2021-12-05 at 15 34 30" src="https://user-images.githubusercontent.com/68651469/144753122-590139f1-fa5e-4d5f-8041-8623afe5aad8.png">

**Comment by silvenon** [comment]
Hi Michael, did you check how many of this vulnerabilities are problematic in the context of generator-webapp? Generally vulnerabilities are much more serious when using a dependency on the server, these are used mostly locally and some on the client.

**Comment by UlisesGascon** [comment]
To keep things organized, I’m going to close it for now. If this is still a problem or becomes relevant again, @michael-oxborrow, please feel free to reopen it or create a new issue with updated details.
